// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: monarchic_agent_protocol.proto
// Protobuf Java Version: 4.32.1

package ai.monarchic.agent_protocol.v1;

@com.google.protobuf.Generated
public interface AgentRunnerPreferenceOrBuilder extends
    // @@protoc_insertion_point(interface_extends:monarchic.agent_protocol.v1.AgentRunnerPreference)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string runner_id = 1;</code>
   * @return The runnerId.
   */
  java.lang.String getRunnerId();
  /**
   * <code>string runner_id = 1;</code>
   * @return The bytes for runnerId.
   */
  com.google.protobuf.ByteString
      getRunnerIdBytes();

  /**
   * <code>optional string model = 2;</code>
   * @return Whether the model field is set.
   */
  boolean hasModel();
  /**
   * <code>optional string model = 2;</code>
   * @return The model.
   */
  java.lang.String getModel();
  /**
   * <code>optional string model = 2;</code>
   * @return The bytes for model.
   */
  com.google.protobuf.ByteString
      getModelBytes();

  /**
   * <code>optional string provider = 3;</code>
   * @return Whether the provider field is set.
   */
  boolean hasProvider();
  /**
   * <code>optional string provider = 3;</code>
   * @return The provider.
   */
  java.lang.String getProvider();
  /**
   * <code>optional string provider = 3;</code>
   * @return The bytes for provider.
   */
  com.google.protobuf.ByteString
      getProviderBytes();

  /**
   * <code>optional string reasoning_effort = 4;</code>
   * @return Whether the reasoningEffort field is set.
   */
  boolean hasReasoningEffort();
  /**
   * <code>optional string reasoning_effort = 4;</code>
   * @return The reasoningEffort.
   */
  java.lang.String getReasoningEffort();
  /**
   * <code>optional string reasoning_effort = 4;</code>
   * @return The bytes for reasoningEffort.
   */
  com.google.protobuf.ByteString
      getReasoningEffortBytes();

  /**
   * <code>repeated string required_capabilities = 5;</code>
   * @return A list containing the requiredCapabilities.
   */
  java.util.List<java.lang.String>
      getRequiredCapabilitiesList();
  /**
   * <code>repeated string required_capabilities = 5;</code>
   * @return The count of requiredCapabilities.
   */
  int getRequiredCapabilitiesCount();
  /**
   * <code>repeated string required_capabilities = 5;</code>
   * @param index The index of the element to return.
   * @return The requiredCapabilities at the given index.
   */
  java.lang.String getRequiredCapabilities(int index);
  /**
   * <code>repeated string required_capabilities = 5;</code>
   * @param index The index of the value to return.
   * @return The bytes of the requiredCapabilities at the given index.
   */
  com.google.protobuf.ByteString
      getRequiredCapabilitiesBytes(int index);

  /**
   * <code>repeated string labels = 6;</code>
   * @return A list containing the labels.
   */
  java.util.List<java.lang.String>
      getLabelsList();
  /**
   * <code>repeated string labels = 6;</code>
   * @return The count of labels.
   */
  int getLabelsCount();
  /**
   * <code>repeated string labels = 6;</code>
   * @param index The index of the element to return.
   * @return The labels at the given index.
   */
  java.lang.String getLabels(int index);
  /**
   * <code>repeated string labels = 6;</code>
   * @param index The index of the value to return.
   * @return The bytes of the labels at the given index.
   */
  com.google.protobuf.ByteString
      getLabelsBytes(int index);

  /**
   * <code>.google.protobuf.Struct extensions = 7;</code>
   * @return Whether the extensions field is set.
   */
  boolean hasExtensions();
  /**
   * <code>.google.protobuf.Struct extensions = 7;</code>
   * @return The extensions.
   */
  com.google.protobuf.Struct getExtensions();
  /**
   * <code>.google.protobuf.Struct extensions = 7;</code>
   */
  com.google.protobuf.StructOrBuilder getExtensionsOrBuilder();
}
