// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: monarchic_agent_protocol.proto
// Protobuf Java Version: 4.32.1

package ai.monarchic.agent_protocol.v1;

@com.google.protobuf.Generated
public interface BootstrapTemplateConnectionContextOrBuilder extends
    // @@protoc_insertion_point(interface_extends:monarchic.agent_protocol.v1.BootstrapTemplateConnectionContext)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string from_slot_id = 1;</code>
   * @return The fromSlotId.
   */
  java.lang.String getFromSlotId();
  /**
   * <code>string from_slot_id = 1;</code>
   * @return The bytes for fromSlotId.
   */
  com.google.protobuf.ByteString
      getFromSlotIdBytes();

  /**
   * <code>string to_slot_id = 2;</code>
   * @return The toSlotId.
   */
  java.lang.String getToSlotId();
  /**
   * <code>string to_slot_id = 2;</code>
   * @return The bytes for toSlotId.
   */
  com.google.protobuf.ByteString
      getToSlotIdBytes();

  /**
   * <code>string kind = 3;</code>
   * @return The kind.
   */
  java.lang.String getKind();
  /**
   * <code>string kind = 3;</code>
   * @return The bytes for kind.
   */
  com.google.protobuf.ByteString
      getKindBytes();

  /**
   * <code>bool required = 4;</code>
   * @return The required.
   */
  boolean getRequired();

  /**
   * <code>optional string description = 5;</code>
   * @return Whether the description field is set.
   */
  boolean hasDescription();
  /**
   * <code>optional string description = 5;</code>
   * @return The description.
   */
  java.lang.String getDescription();
  /**
   * <code>optional string description = 5;</code>
   * @return The bytes for description.
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();
}
