// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: monarchic_agent_protocol.proto
// Protobuf Java Version: 4.32.1

package ai.monarchic.agent_protocol.v1;

/**
 * Protobuf type {@code monarchic.agent_protocol.v1.CampaignPipelineSpec}
 */
@com.google.protobuf.Generated
public final class CampaignPipelineSpec extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:monarchic.agent_protocol.v1.CampaignPipelineSpec)
    CampaignPipelineSpecOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 32,
      /* patch= */ 1,
      /* suffix= */ "",
      CampaignPipelineSpec.class.getName());
  }
  // Use CampaignPipelineSpec.newBuilder() to construct.
  private CampaignPipelineSpec(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private CampaignPipelineSpec() {
    contractVersion_ = "";
    pipelineId_ = "";
    version_ = "";
    objective_ = "";
    projectKey_ = "";
    connections_ = java.util.Collections.emptyList();
    tasks_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ai.monarchic.agent_protocol.v1.MonarchicAgentProtocolV1.internal_static_monarchic_agent_protocol_v1_CampaignPipelineSpec_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ai.monarchic.agent_protocol.v1.MonarchicAgentProtocolV1.internal_static_monarchic_agent_protocol_v1_CampaignPipelineSpec_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ai.monarchic.agent_protocol.v1.CampaignPipelineSpec.class, ai.monarchic.agent_protocol.v1.CampaignPipelineSpec.Builder.class);
  }

  private int bitField0_;
  public static final int CONTRACT_VERSION_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object contractVersion_ = "";
  /**
   * <code>string contract_version = 1;</code>
   * @return The contractVersion.
   */
  @java.lang.Override
  public java.lang.String getContractVersion() {
    java.lang.Object ref = contractVersion_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      contractVersion_ = s;
      return s;
    }
  }
  /**
   * <code>string contract_version = 1;</code>
   * @return The bytes for contractVersion.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getContractVersionBytes() {
    java.lang.Object ref = contractVersion_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      contractVersion_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PIPELINE_ID_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object pipelineId_ = "";
  /**
   * <code>string pipeline_id = 2;</code>
   * @return The pipelineId.
   */
  @java.lang.Override
  public java.lang.String getPipelineId() {
    java.lang.Object ref = pipelineId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      pipelineId_ = s;
      return s;
    }
  }
  /**
   * <code>string pipeline_id = 2;</code>
   * @return The bytes for pipelineId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPipelineIdBytes() {
    java.lang.Object ref = pipelineId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      pipelineId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int VERSION_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object version_ = "";
  /**
   * <code>string version = 3;</code>
   * @return The version.
   */
  @java.lang.Override
  public java.lang.String getVersion() {
    java.lang.Object ref = version_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      version_ = s;
      return s;
    }
  }
  /**
   * <code>string version = 3;</code>
   * @return The bytes for version.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getVersionBytes() {
    java.lang.Object ref = version_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      version_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int OBJECTIVE_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object objective_ = "";
  /**
   * <code>optional string objective = 4;</code>
   * @return Whether the objective field is set.
   */
  @java.lang.Override
  public boolean hasObjective() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional string objective = 4;</code>
   * @return The objective.
   */
  @java.lang.Override
  public java.lang.String getObjective() {
    java.lang.Object ref = objective_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      objective_ = s;
      return s;
    }
  }
  /**
   * <code>optional string objective = 4;</code>
   * @return The bytes for objective.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getObjectiveBytes() {
    java.lang.Object ref = objective_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      objective_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PROJECT_KEY_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object projectKey_ = "";
  /**
   * <code>optional string project_key = 5;</code>
   * @return Whether the projectKey field is set.
   */
  @java.lang.Override
  public boolean hasProjectKey() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional string project_key = 5;</code>
   * @return The projectKey.
   */
  @java.lang.Override
  public java.lang.String getProjectKey() {
    java.lang.Object ref = projectKey_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      projectKey_ = s;
      return s;
    }
  }
  /**
   * <code>optional string project_key = 5;</code>
   * @return The bytes for projectKey.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getProjectKeyBytes() {
    java.lang.Object ref = projectKey_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      projectKey_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CONTINUE_ON_ERROR_FIELD_NUMBER = 6;
  private boolean continueOnError_ = false;
  /**
   * <code>bool continue_on_error = 6;</code>
   * @return The continueOnError.
   */
  @java.lang.Override
  public boolean getContinueOnError() {
    return continueOnError_;
  }

  public static final int GATE_POLICY_FIELD_NUMBER = 7;
  private ai.monarchic.agent_protocol.v1.CampaignPipelineGatePolicy gatePolicy_;
  /**
   * <code>optional .monarchic.agent_protocol.v1.CampaignPipelineGatePolicy gate_policy = 7;</code>
   * @return Whether the gatePolicy field is set.
   */
  @java.lang.Override
  public boolean hasGatePolicy() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>optional .monarchic.agent_protocol.v1.CampaignPipelineGatePolicy gate_policy = 7;</code>
   * @return The gatePolicy.
   */
  @java.lang.Override
  public ai.monarchic.agent_protocol.v1.CampaignPipelineGatePolicy getGatePolicy() {
    return gatePolicy_ == null ? ai.monarchic.agent_protocol.v1.CampaignPipelineGatePolicy.getDefaultInstance() : gatePolicy_;
  }
  /**
   * <code>optional .monarchic.agent_protocol.v1.CampaignPipelineGatePolicy gate_policy = 7;</code>
   */
  @java.lang.Override
  public ai.monarchic.agent_protocol.v1.CampaignPipelineGatePolicyOrBuilder getGatePolicyOrBuilder() {
    return gatePolicy_ == null ? ai.monarchic.agent_protocol.v1.CampaignPipelineGatePolicy.getDefaultInstance() : gatePolicy_;
  }

  public static final int METADATA_FIELD_NUMBER = 8;
  private com.google.protobuf.Struct metadata_;
  /**
   * <code>.google.protobuf.Struct metadata = 8;</code>
   * @return Whether the metadata field is set.
   */
  @java.lang.Override
  public boolean hasMetadata() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <code>.google.protobuf.Struct metadata = 8;</code>
   * @return The metadata.
   */
  @java.lang.Override
  public com.google.protobuf.Struct getMetadata() {
    return metadata_ == null ? com.google.protobuf.Struct.getDefaultInstance() : metadata_;
  }
  /**
   * <code>.google.protobuf.Struct metadata = 8;</code>
   */
  @java.lang.Override
  public com.google.protobuf.StructOrBuilder getMetadataOrBuilder() {
    return metadata_ == null ? com.google.protobuf.Struct.getDefaultInstance() : metadata_;
  }

  public static final int CONNECTIONS_FIELD_NUMBER = 9;
  @SuppressWarnings("serial")
  private java.util.List<ai.monarchic.agent_protocol.v1.CampaignPipelineConnection> connections_;
  /**
   * <code>repeated .monarchic.agent_protocol.v1.CampaignPipelineConnection connections = 9;</code>
   */
  @java.lang.Override
  public java.util.List<ai.monarchic.agent_protocol.v1.CampaignPipelineConnection> getConnectionsList() {
    return connections_;
  }
  /**
   * <code>repeated .monarchic.agent_protocol.v1.CampaignPipelineConnection connections = 9;</code>
   */
  @java.lang.Override
  public java.util.List<? extends ai.monarchic.agent_protocol.v1.CampaignPipelineConnectionOrBuilder>
      getConnectionsOrBuilderList() {
    return connections_;
  }
  /**
   * <code>repeated .monarchic.agent_protocol.v1.CampaignPipelineConnection connections = 9;</code>
   */
  @java.lang.Override
  public int getConnectionsCount() {
    return connections_.size();
  }
  /**
   * <code>repeated .monarchic.agent_protocol.v1.CampaignPipelineConnection connections = 9;</code>
   */
  @java.lang.Override
  public ai.monarchic.agent_protocol.v1.CampaignPipelineConnection getConnections(int index) {
    return connections_.get(index);
  }
  /**
   * <code>repeated .monarchic.agent_protocol.v1.CampaignPipelineConnection connections = 9;</code>
   */
  @java.lang.Override
  public ai.monarchic.agent_protocol.v1.CampaignPipelineConnectionOrBuilder getConnectionsOrBuilder(
      int index) {
    return connections_.get(index);
  }

  public static final int TASKS_FIELD_NUMBER = 10;
  @SuppressWarnings("serial")
  private java.util.List<ai.monarchic.agent_protocol.v1.CampaignPipelineTaskRef> tasks_;
  /**
   * <code>repeated .monarchic.agent_protocol.v1.CampaignPipelineTaskRef tasks = 10;</code>
   */
  @java.lang.Override
  public java.util.List<ai.monarchic.agent_protocol.v1.CampaignPipelineTaskRef> getTasksList() {
    return tasks_;
  }
  /**
   * <code>repeated .monarchic.agent_protocol.v1.CampaignPipelineTaskRef tasks = 10;</code>
   */
  @java.lang.Override
  public java.util.List<? extends ai.monarchic.agent_protocol.v1.CampaignPipelineTaskRefOrBuilder>
      getTasksOrBuilderList() {
    return tasks_;
  }
  /**
   * <code>repeated .monarchic.agent_protocol.v1.CampaignPipelineTaskRef tasks = 10;</code>
   */
  @java.lang.Override
  public int getTasksCount() {
    return tasks_.size();
  }
  /**
   * <code>repeated .monarchic.agent_protocol.v1.CampaignPipelineTaskRef tasks = 10;</code>
   */
  @java.lang.Override
  public ai.monarchic.agent_protocol.v1.CampaignPipelineTaskRef getTasks(int index) {
    return tasks_.get(index);
  }
  /**
   * <code>repeated .monarchic.agent_protocol.v1.CampaignPipelineTaskRef tasks = 10;</code>
   */
  @java.lang.Override
  public ai.monarchic.agent_protocol.v1.CampaignPipelineTaskRefOrBuilder getTasksOrBuilder(
      int index) {
    return tasks_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(contractVersion_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, contractVersion_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(pipelineId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, pipelineId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(version_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, version_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 4, objective_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 5, projectKey_);
    }
    if (continueOnError_ != false) {
      output.writeBool(6, continueOnError_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeMessage(7, getGatePolicy());
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      output.writeMessage(8, getMetadata());
    }
    for (int i = 0; i < connections_.size(); i++) {
      output.writeMessage(9, connections_.get(i));
    }
    for (int i = 0; i < tasks_.size(); i++) {
      output.writeMessage(10, tasks_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(contractVersion_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, contractVersion_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(pipelineId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, pipelineId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(version_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, version_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(4, objective_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(5, projectKey_);
    }
    if (continueOnError_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(6, continueOnError_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, getGatePolicy());
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(8, getMetadata());
    }
    for (int i = 0; i < connections_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(9, connections_.get(i));
    }
    for (int i = 0; i < tasks_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(10, tasks_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ai.monarchic.agent_protocol.v1.CampaignPipelineSpec)) {
      return super.equals(obj);
    }
    ai.monarchic.agent_protocol.v1.CampaignPipelineSpec other = (ai.monarchic.agent_protocol.v1.CampaignPipelineSpec) obj;

    if (!getContractVersion()
        .equals(other.getContractVersion())) return false;
    if (!getPipelineId()
        .equals(other.getPipelineId())) return false;
    if (!getVersion()
        .equals(other.getVersion())) return false;
    if (hasObjective() != other.hasObjective()) return false;
    if (hasObjective()) {
      if (!getObjective()
          .equals(other.getObjective())) return false;
    }
    if (hasProjectKey() != other.hasProjectKey()) return false;
    if (hasProjectKey()) {
      if (!getProjectKey()
          .equals(other.getProjectKey())) return false;
    }
    if (getContinueOnError()
        != other.getContinueOnError()) return false;
    if (hasGatePolicy() != other.hasGatePolicy()) return false;
    if (hasGatePolicy()) {
      if (!getGatePolicy()
          .equals(other.getGatePolicy())) return false;
    }
    if (hasMetadata() != other.hasMetadata()) return false;
    if (hasMetadata()) {
      if (!getMetadata()
          .equals(other.getMetadata())) return false;
    }
    if (!getConnectionsList()
        .equals(other.getConnectionsList())) return false;
    if (!getTasksList()
        .equals(other.getTasksList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CONTRACT_VERSION_FIELD_NUMBER;
    hash = (53 * hash) + getContractVersion().hashCode();
    hash = (37 * hash) + PIPELINE_ID_FIELD_NUMBER;
    hash = (53 * hash) + getPipelineId().hashCode();
    hash = (37 * hash) + VERSION_FIELD_NUMBER;
    hash = (53 * hash) + getVersion().hashCode();
    if (hasObjective()) {
      hash = (37 * hash) + OBJECTIVE_FIELD_NUMBER;
      hash = (53 * hash) + getObjective().hashCode();
    }
    if (hasProjectKey()) {
      hash = (37 * hash) + PROJECT_KEY_FIELD_NUMBER;
      hash = (53 * hash) + getProjectKey().hashCode();
    }
    hash = (37 * hash) + CONTINUE_ON_ERROR_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getContinueOnError());
    if (hasGatePolicy()) {
      hash = (37 * hash) + GATE_POLICY_FIELD_NUMBER;
      hash = (53 * hash) + getGatePolicy().hashCode();
    }
    if (hasMetadata()) {
      hash = (37 * hash) + METADATA_FIELD_NUMBER;
      hash = (53 * hash) + getMetadata().hashCode();
    }
    if (getConnectionsCount() > 0) {
      hash = (37 * hash) + CONNECTIONS_FIELD_NUMBER;
      hash = (53 * hash) + getConnectionsList().hashCode();
    }
    if (getTasksCount() > 0) {
      hash = (37 * hash) + TASKS_FIELD_NUMBER;
      hash = (53 * hash) + getTasksList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ai.monarchic.agent_protocol.v1.CampaignPipelineSpec parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ai.monarchic.agent_protocol.v1.CampaignPipelineSpec parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ai.monarchic.agent_protocol.v1.CampaignPipelineSpec parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ai.monarchic.agent_protocol.v1.CampaignPipelineSpec parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ai.monarchic.agent_protocol.v1.CampaignPipelineSpec parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ai.monarchic.agent_protocol.v1.CampaignPipelineSpec parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ai.monarchic.agent_protocol.v1.CampaignPipelineSpec parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static ai.monarchic.agent_protocol.v1.CampaignPipelineSpec parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static ai.monarchic.agent_protocol.v1.CampaignPipelineSpec parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static ai.monarchic.agent_protocol.v1.CampaignPipelineSpec parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ai.monarchic.agent_protocol.v1.CampaignPipelineSpec parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static ai.monarchic.agent_protocol.v1.CampaignPipelineSpec parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ai.monarchic.agent_protocol.v1.CampaignPipelineSpec prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code monarchic.agent_protocol.v1.CampaignPipelineSpec}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:monarchic.agent_protocol.v1.CampaignPipelineSpec)
      ai.monarchic.agent_protocol.v1.CampaignPipelineSpecOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ai.monarchic.agent_protocol.v1.MonarchicAgentProtocolV1.internal_static_monarchic_agent_protocol_v1_CampaignPipelineSpec_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ai.monarchic.agent_protocol.v1.MonarchicAgentProtocolV1.internal_static_monarchic_agent_protocol_v1_CampaignPipelineSpec_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ai.monarchic.agent_protocol.v1.CampaignPipelineSpec.class, ai.monarchic.agent_protocol.v1.CampaignPipelineSpec.Builder.class);
    }

    // Construct using ai.monarchic.agent_protocol.v1.CampaignPipelineSpec.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetGatePolicyFieldBuilder();
        internalGetMetadataFieldBuilder();
        internalGetConnectionsFieldBuilder();
        internalGetTasksFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      contractVersion_ = "";
      pipelineId_ = "";
      version_ = "";
      objective_ = "";
      projectKey_ = "";
      continueOnError_ = false;
      gatePolicy_ = null;
      if (gatePolicyBuilder_ != null) {
        gatePolicyBuilder_.dispose();
        gatePolicyBuilder_ = null;
      }
      metadata_ = null;
      if (metadataBuilder_ != null) {
        metadataBuilder_.dispose();
        metadataBuilder_ = null;
      }
      if (connectionsBuilder_ == null) {
        connections_ = java.util.Collections.emptyList();
      } else {
        connections_ = null;
        connectionsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000100);
      if (tasksBuilder_ == null) {
        tasks_ = java.util.Collections.emptyList();
      } else {
        tasks_ = null;
        tasksBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000200);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ai.monarchic.agent_protocol.v1.MonarchicAgentProtocolV1.internal_static_monarchic_agent_protocol_v1_CampaignPipelineSpec_descriptor;
    }

    @java.lang.Override
    public ai.monarchic.agent_protocol.v1.CampaignPipelineSpec getDefaultInstanceForType() {
      return ai.monarchic.agent_protocol.v1.CampaignPipelineSpec.getDefaultInstance();
    }

    @java.lang.Override
    public ai.monarchic.agent_protocol.v1.CampaignPipelineSpec build() {
      ai.monarchic.agent_protocol.v1.CampaignPipelineSpec result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ai.monarchic.agent_protocol.v1.CampaignPipelineSpec buildPartial() {
      ai.monarchic.agent_protocol.v1.CampaignPipelineSpec result = new ai.monarchic.agent_protocol.v1.CampaignPipelineSpec(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(ai.monarchic.agent_protocol.v1.CampaignPipelineSpec result) {
      if (connectionsBuilder_ == null) {
        if (((bitField0_ & 0x00000100) != 0)) {
          connections_ = java.util.Collections.unmodifiableList(connections_);
          bitField0_ = (bitField0_ & ~0x00000100);
        }
        result.connections_ = connections_;
      } else {
        result.connections_ = connectionsBuilder_.build();
      }
      if (tasksBuilder_ == null) {
        if (((bitField0_ & 0x00000200) != 0)) {
          tasks_ = java.util.Collections.unmodifiableList(tasks_);
          bitField0_ = (bitField0_ & ~0x00000200);
        }
        result.tasks_ = tasks_;
      } else {
        result.tasks_ = tasksBuilder_.build();
      }
    }

    private void buildPartial0(ai.monarchic.agent_protocol.v1.CampaignPipelineSpec result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.contractVersion_ = contractVersion_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.pipelineId_ = pipelineId_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.version_ = version_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.objective_ = objective_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.projectKey_ = projectKey_;
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.continueOnError_ = continueOnError_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.gatePolicy_ = gatePolicyBuilder_ == null
            ? gatePolicy_
            : gatePolicyBuilder_.build();
        to_bitField0_ |= 0x00000004;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.metadata_ = metadataBuilder_ == null
            ? metadata_
            : metadataBuilder_.build();
        to_bitField0_ |= 0x00000008;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ai.monarchic.agent_protocol.v1.CampaignPipelineSpec) {
        return mergeFrom((ai.monarchic.agent_protocol.v1.CampaignPipelineSpec)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ai.monarchic.agent_protocol.v1.CampaignPipelineSpec other) {
      if (other == ai.monarchic.agent_protocol.v1.CampaignPipelineSpec.getDefaultInstance()) return this;
      if (!other.getContractVersion().isEmpty()) {
        contractVersion_ = other.contractVersion_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getPipelineId().isEmpty()) {
        pipelineId_ = other.pipelineId_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getVersion().isEmpty()) {
        version_ = other.version_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (other.hasObjective()) {
        objective_ = other.objective_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (other.hasProjectKey()) {
        projectKey_ = other.projectKey_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      if (other.getContinueOnError() != false) {
        setContinueOnError(other.getContinueOnError());
      }
      if (other.hasGatePolicy()) {
        mergeGatePolicy(other.getGatePolicy());
      }
      if (other.hasMetadata()) {
        mergeMetadata(other.getMetadata());
      }
      if (connectionsBuilder_ == null) {
        if (!other.connections_.isEmpty()) {
          if (connections_.isEmpty()) {
            connections_ = other.connections_;
            bitField0_ = (bitField0_ & ~0x00000100);
          } else {
            ensureConnectionsIsMutable();
            connections_.addAll(other.connections_);
          }
          onChanged();
        }
      } else {
        if (!other.connections_.isEmpty()) {
          if (connectionsBuilder_.isEmpty()) {
            connectionsBuilder_.dispose();
            connectionsBuilder_ = null;
            connections_ = other.connections_;
            bitField0_ = (bitField0_ & ~0x00000100);
            connectionsBuilder_ =
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 internalGetConnectionsFieldBuilder() : null;
          } else {
            connectionsBuilder_.addAllMessages(other.connections_);
          }
        }
      }
      if (tasksBuilder_ == null) {
        if (!other.tasks_.isEmpty()) {
          if (tasks_.isEmpty()) {
            tasks_ = other.tasks_;
            bitField0_ = (bitField0_ & ~0x00000200);
          } else {
            ensureTasksIsMutable();
            tasks_.addAll(other.tasks_);
          }
          onChanged();
        }
      } else {
        if (!other.tasks_.isEmpty()) {
          if (tasksBuilder_.isEmpty()) {
            tasksBuilder_.dispose();
            tasksBuilder_ = null;
            tasks_ = other.tasks_;
            bitField0_ = (bitField0_ & ~0x00000200);
            tasksBuilder_ =
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 internalGetTasksFieldBuilder() : null;
          } else {
            tasksBuilder_.addAllMessages(other.tasks_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              contractVersion_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              pipelineId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              version_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              objective_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              projectKey_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 48: {
              continueOnError_ = input.readBool();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            case 58: {
              input.readMessage(
                  internalGetGatePolicyFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000040;
              break;
            } // case 58
            case 66: {
              input.readMessage(
                  internalGetMetadataFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000080;
              break;
            } // case 66
            case 74: {
              ai.monarchic.agent_protocol.v1.CampaignPipelineConnection m =
                  input.readMessage(
                      ai.monarchic.agent_protocol.v1.CampaignPipelineConnection.parser(),
                      extensionRegistry);
              if (connectionsBuilder_ == null) {
                ensureConnectionsIsMutable();
                connections_.add(m);
              } else {
                connectionsBuilder_.addMessage(m);
              }
              break;
            } // case 74
            case 82: {
              ai.monarchic.agent_protocol.v1.CampaignPipelineTaskRef m =
                  input.readMessage(
                      ai.monarchic.agent_protocol.v1.CampaignPipelineTaskRef.parser(),
                      extensionRegistry);
              if (tasksBuilder_ == null) {
                ensureTasksIsMutable();
                tasks_.add(m);
              } else {
                tasksBuilder_.addMessage(m);
              }
              break;
            } // case 82
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object contractVersion_ = "";
    /**
     * <code>string contract_version = 1;</code>
     * @return The contractVersion.
     */
    public java.lang.String getContractVersion() {
      java.lang.Object ref = contractVersion_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        contractVersion_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string contract_version = 1;</code>
     * @return The bytes for contractVersion.
     */
    public com.google.protobuf.ByteString
        getContractVersionBytes() {
      java.lang.Object ref = contractVersion_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        contractVersion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string contract_version = 1;</code>
     * @param value The contractVersion to set.
     * @return This builder for chaining.
     */
    public Builder setContractVersion(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      contractVersion_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string contract_version = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearContractVersion() {
      contractVersion_ = getDefaultInstance().getContractVersion();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string contract_version = 1;</code>
     * @param value The bytes for contractVersion to set.
     * @return This builder for chaining.
     */
    public Builder setContractVersionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      contractVersion_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object pipelineId_ = "";
    /**
     * <code>string pipeline_id = 2;</code>
     * @return The pipelineId.
     */
    public java.lang.String getPipelineId() {
      java.lang.Object ref = pipelineId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        pipelineId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string pipeline_id = 2;</code>
     * @return The bytes for pipelineId.
     */
    public com.google.protobuf.ByteString
        getPipelineIdBytes() {
      java.lang.Object ref = pipelineId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        pipelineId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string pipeline_id = 2;</code>
     * @param value The pipelineId to set.
     * @return This builder for chaining.
     */
    public Builder setPipelineId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      pipelineId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string pipeline_id = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearPipelineId() {
      pipelineId_ = getDefaultInstance().getPipelineId();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string pipeline_id = 2;</code>
     * @param value The bytes for pipelineId to set.
     * @return This builder for chaining.
     */
    public Builder setPipelineIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      pipelineId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object version_ = "";
    /**
     * <code>string version = 3;</code>
     * @return The version.
     */
    public java.lang.String getVersion() {
      java.lang.Object ref = version_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        version_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string version = 3;</code>
     * @return The bytes for version.
     */
    public com.google.protobuf.ByteString
        getVersionBytes() {
      java.lang.Object ref = version_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        version_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string version = 3;</code>
     * @param value The version to set.
     * @return This builder for chaining.
     */
    public Builder setVersion(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      version_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string version = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearVersion() {
      version_ = getDefaultInstance().getVersion();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string version = 3;</code>
     * @param value The bytes for version to set.
     * @return This builder for chaining.
     */
    public Builder setVersionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      version_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.lang.Object objective_ = "";
    /**
     * <code>optional string objective = 4;</code>
     * @return Whether the objective field is set.
     */
    public boolean hasObjective() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional string objective = 4;</code>
     * @return The objective.
     */
    public java.lang.String getObjective() {
      java.lang.Object ref = objective_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        objective_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string objective = 4;</code>
     * @return The bytes for objective.
     */
    public com.google.protobuf.ByteString
        getObjectiveBytes() {
      java.lang.Object ref = objective_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        objective_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string objective = 4;</code>
     * @param value The objective to set.
     * @return This builder for chaining.
     */
    public Builder setObjective(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      objective_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>optional string objective = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearObjective() {
      objective_ = getDefaultInstance().getObjective();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>optional string objective = 4;</code>
     * @param value The bytes for objective to set.
     * @return This builder for chaining.
     */
    public Builder setObjectiveBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      objective_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private java.lang.Object projectKey_ = "";
    /**
     * <code>optional string project_key = 5;</code>
     * @return Whether the projectKey field is set.
     */
    public boolean hasProjectKey() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional string project_key = 5;</code>
     * @return The projectKey.
     */
    public java.lang.String getProjectKey() {
      java.lang.Object ref = projectKey_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        projectKey_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string project_key = 5;</code>
     * @return The bytes for projectKey.
     */
    public com.google.protobuf.ByteString
        getProjectKeyBytes() {
      java.lang.Object ref = projectKey_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        projectKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string project_key = 5;</code>
     * @param value The projectKey to set.
     * @return This builder for chaining.
     */
    public Builder setProjectKey(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      projectKey_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>optional string project_key = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearProjectKey() {
      projectKey_ = getDefaultInstance().getProjectKey();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <code>optional string project_key = 5;</code>
     * @param value The bytes for projectKey to set.
     * @return This builder for chaining.
     */
    public Builder setProjectKeyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      projectKey_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private boolean continueOnError_ ;
    /**
     * <code>bool continue_on_error = 6;</code>
     * @return The continueOnError.
     */
    @java.lang.Override
    public boolean getContinueOnError() {
      return continueOnError_;
    }
    /**
     * <code>bool continue_on_error = 6;</code>
     * @param value The continueOnError to set.
     * @return This builder for chaining.
     */
    public Builder setContinueOnError(boolean value) {

      continueOnError_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>bool continue_on_error = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearContinueOnError() {
      bitField0_ = (bitField0_ & ~0x00000020);
      continueOnError_ = false;
      onChanged();
      return this;
    }

    private ai.monarchic.agent_protocol.v1.CampaignPipelineGatePolicy gatePolicy_;
    private com.google.protobuf.SingleFieldBuilder<
        ai.monarchic.agent_protocol.v1.CampaignPipelineGatePolicy, ai.monarchic.agent_protocol.v1.CampaignPipelineGatePolicy.Builder, ai.monarchic.agent_protocol.v1.CampaignPipelineGatePolicyOrBuilder> gatePolicyBuilder_;
    /**
     * <code>optional .monarchic.agent_protocol.v1.CampaignPipelineGatePolicy gate_policy = 7;</code>
     * @return Whether the gatePolicy field is set.
     */
    public boolean hasGatePolicy() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <code>optional .monarchic.agent_protocol.v1.CampaignPipelineGatePolicy gate_policy = 7;</code>
     * @return The gatePolicy.
     */
    public ai.monarchic.agent_protocol.v1.CampaignPipelineGatePolicy getGatePolicy() {
      if (gatePolicyBuilder_ == null) {
        return gatePolicy_ == null ? ai.monarchic.agent_protocol.v1.CampaignPipelineGatePolicy.getDefaultInstance() : gatePolicy_;
      } else {
        return gatePolicyBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .monarchic.agent_protocol.v1.CampaignPipelineGatePolicy gate_policy = 7;</code>
     */
    public Builder setGatePolicy(ai.monarchic.agent_protocol.v1.CampaignPipelineGatePolicy value) {
      if (gatePolicyBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        gatePolicy_ = value;
      } else {
        gatePolicyBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>optional .monarchic.agent_protocol.v1.CampaignPipelineGatePolicy gate_policy = 7;</code>
     */
    public Builder setGatePolicy(
        ai.monarchic.agent_protocol.v1.CampaignPipelineGatePolicy.Builder builderForValue) {
      if (gatePolicyBuilder_ == null) {
        gatePolicy_ = builderForValue.build();
      } else {
        gatePolicyBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>optional .monarchic.agent_protocol.v1.CampaignPipelineGatePolicy gate_policy = 7;</code>
     */
    public Builder mergeGatePolicy(ai.monarchic.agent_protocol.v1.CampaignPipelineGatePolicy value) {
      if (gatePolicyBuilder_ == null) {
        if (((bitField0_ & 0x00000040) != 0) &&
          gatePolicy_ != null &&
          gatePolicy_ != ai.monarchic.agent_protocol.v1.CampaignPipelineGatePolicy.getDefaultInstance()) {
          getGatePolicyBuilder().mergeFrom(value);
        } else {
          gatePolicy_ = value;
        }
      } else {
        gatePolicyBuilder_.mergeFrom(value);
      }
      if (gatePolicy_ != null) {
        bitField0_ |= 0x00000040;
        onChanged();
      }
      return this;
    }
    /**
     * <code>optional .monarchic.agent_protocol.v1.CampaignPipelineGatePolicy gate_policy = 7;</code>
     */
    public Builder clearGatePolicy() {
      bitField0_ = (bitField0_ & ~0x00000040);
      gatePolicy_ = null;
      if (gatePolicyBuilder_ != null) {
        gatePolicyBuilder_.dispose();
        gatePolicyBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>optional .monarchic.agent_protocol.v1.CampaignPipelineGatePolicy gate_policy = 7;</code>
     */
    public ai.monarchic.agent_protocol.v1.CampaignPipelineGatePolicy.Builder getGatePolicyBuilder() {
      bitField0_ |= 0x00000040;
      onChanged();
      return internalGetGatePolicyFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .monarchic.agent_protocol.v1.CampaignPipelineGatePolicy gate_policy = 7;</code>
     */
    public ai.monarchic.agent_protocol.v1.CampaignPipelineGatePolicyOrBuilder getGatePolicyOrBuilder() {
      if (gatePolicyBuilder_ != null) {
        return gatePolicyBuilder_.getMessageOrBuilder();
      } else {
        return gatePolicy_ == null ?
            ai.monarchic.agent_protocol.v1.CampaignPipelineGatePolicy.getDefaultInstance() : gatePolicy_;
      }
    }
    /**
     * <code>optional .monarchic.agent_protocol.v1.CampaignPipelineGatePolicy gate_policy = 7;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        ai.monarchic.agent_protocol.v1.CampaignPipelineGatePolicy, ai.monarchic.agent_protocol.v1.CampaignPipelineGatePolicy.Builder, ai.monarchic.agent_protocol.v1.CampaignPipelineGatePolicyOrBuilder>
        internalGetGatePolicyFieldBuilder() {
      if (gatePolicyBuilder_ == null) {
        gatePolicyBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            ai.monarchic.agent_protocol.v1.CampaignPipelineGatePolicy, ai.monarchic.agent_protocol.v1.CampaignPipelineGatePolicy.Builder, ai.monarchic.agent_protocol.v1.CampaignPipelineGatePolicyOrBuilder>(
                getGatePolicy(),
                getParentForChildren(),
                isClean());
        gatePolicy_ = null;
      }
      return gatePolicyBuilder_;
    }

    private com.google.protobuf.Struct metadata_;
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Struct, com.google.protobuf.Struct.Builder, com.google.protobuf.StructOrBuilder> metadataBuilder_;
    /**
     * <code>.google.protobuf.Struct metadata = 8;</code>
     * @return Whether the metadata field is set.
     */
    public boolean hasMetadata() {
      return ((bitField0_ & 0x00000080) != 0);
    }
    /**
     * <code>.google.protobuf.Struct metadata = 8;</code>
     * @return The metadata.
     */
    public com.google.protobuf.Struct getMetadata() {
      if (metadataBuilder_ == null) {
        return metadata_ == null ? com.google.protobuf.Struct.getDefaultInstance() : metadata_;
      } else {
        return metadataBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Struct metadata = 8;</code>
     */
    public Builder setMetadata(com.google.protobuf.Struct value) {
      if (metadataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        metadata_ = value;
      } else {
        metadataBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Struct metadata = 8;</code>
     */
    public Builder setMetadata(
        com.google.protobuf.Struct.Builder builderForValue) {
      if (metadataBuilder_ == null) {
        metadata_ = builderForValue.build();
      } else {
        metadataBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Struct metadata = 8;</code>
     */
    public Builder mergeMetadata(com.google.protobuf.Struct value) {
      if (metadataBuilder_ == null) {
        if (((bitField0_ & 0x00000080) != 0) &&
          metadata_ != null &&
          metadata_ != com.google.protobuf.Struct.getDefaultInstance()) {
          getMetadataBuilder().mergeFrom(value);
        } else {
          metadata_ = value;
        }
      } else {
        metadataBuilder_.mergeFrom(value);
      }
      if (metadata_ != null) {
        bitField0_ |= 0x00000080;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.google.protobuf.Struct metadata = 8;</code>
     */
    public Builder clearMetadata() {
      bitField0_ = (bitField0_ & ~0x00000080);
      metadata_ = null;
      if (metadataBuilder_ != null) {
        metadataBuilder_.dispose();
        metadataBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Struct metadata = 8;</code>
     */
    public com.google.protobuf.Struct.Builder getMetadataBuilder() {
      bitField0_ |= 0x00000080;
      onChanged();
      return internalGetMetadataFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Struct metadata = 8;</code>
     */
    public com.google.protobuf.StructOrBuilder getMetadataOrBuilder() {
      if (metadataBuilder_ != null) {
        return metadataBuilder_.getMessageOrBuilder();
      } else {
        return metadata_ == null ?
            com.google.protobuf.Struct.getDefaultInstance() : metadata_;
      }
    }
    /**
     * <code>.google.protobuf.Struct metadata = 8;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Struct, com.google.protobuf.Struct.Builder, com.google.protobuf.StructOrBuilder>
        internalGetMetadataFieldBuilder() {
      if (metadataBuilder_ == null) {
        metadataBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.google.protobuf.Struct, com.google.protobuf.Struct.Builder, com.google.protobuf.StructOrBuilder>(
                getMetadata(),
                getParentForChildren(),
                isClean());
        metadata_ = null;
      }
      return metadataBuilder_;
    }

    private java.util.List<ai.monarchic.agent_protocol.v1.CampaignPipelineConnection> connections_ =
      java.util.Collections.emptyList();
    private void ensureConnectionsIsMutable() {
      if (!((bitField0_ & 0x00000100) != 0)) {
        connections_ = new java.util.ArrayList<ai.monarchic.agent_protocol.v1.CampaignPipelineConnection>(connections_);
        bitField0_ |= 0x00000100;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        ai.monarchic.agent_protocol.v1.CampaignPipelineConnection, ai.monarchic.agent_protocol.v1.CampaignPipelineConnection.Builder, ai.monarchic.agent_protocol.v1.CampaignPipelineConnectionOrBuilder> connectionsBuilder_;

    /**
     * <code>repeated .monarchic.agent_protocol.v1.CampaignPipelineConnection connections = 9;</code>
     */
    public java.util.List<ai.monarchic.agent_protocol.v1.CampaignPipelineConnection> getConnectionsList() {
      if (connectionsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(connections_);
      } else {
        return connectionsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .monarchic.agent_protocol.v1.CampaignPipelineConnection connections = 9;</code>
     */
    public int getConnectionsCount() {
      if (connectionsBuilder_ == null) {
        return connections_.size();
      } else {
        return connectionsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .monarchic.agent_protocol.v1.CampaignPipelineConnection connections = 9;</code>
     */
    public ai.monarchic.agent_protocol.v1.CampaignPipelineConnection getConnections(int index) {
      if (connectionsBuilder_ == null) {
        return connections_.get(index);
      } else {
        return connectionsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .monarchic.agent_protocol.v1.CampaignPipelineConnection connections = 9;</code>
     */
    public Builder setConnections(
        int index, ai.monarchic.agent_protocol.v1.CampaignPipelineConnection value) {
      if (connectionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureConnectionsIsMutable();
        connections_.set(index, value);
        onChanged();
      } else {
        connectionsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .monarchic.agent_protocol.v1.CampaignPipelineConnection connections = 9;</code>
     */
    public Builder setConnections(
        int index, ai.monarchic.agent_protocol.v1.CampaignPipelineConnection.Builder builderForValue) {
      if (connectionsBuilder_ == null) {
        ensureConnectionsIsMutable();
        connections_.set(index, builderForValue.build());
        onChanged();
      } else {
        connectionsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .monarchic.agent_protocol.v1.CampaignPipelineConnection connections = 9;</code>
     */
    public Builder addConnections(ai.monarchic.agent_protocol.v1.CampaignPipelineConnection value) {
      if (connectionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureConnectionsIsMutable();
        connections_.add(value);
        onChanged();
      } else {
        connectionsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .monarchic.agent_protocol.v1.CampaignPipelineConnection connections = 9;</code>
     */
    public Builder addConnections(
        int index, ai.monarchic.agent_protocol.v1.CampaignPipelineConnection value) {
      if (connectionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureConnectionsIsMutable();
        connections_.add(index, value);
        onChanged();
      } else {
        connectionsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .monarchic.agent_protocol.v1.CampaignPipelineConnection connections = 9;</code>
     */
    public Builder addConnections(
        ai.monarchic.agent_protocol.v1.CampaignPipelineConnection.Builder builderForValue) {
      if (connectionsBuilder_ == null) {
        ensureConnectionsIsMutable();
        connections_.add(builderForValue.build());
        onChanged();
      } else {
        connectionsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .monarchic.agent_protocol.v1.CampaignPipelineConnection connections = 9;</code>
     */
    public Builder addConnections(
        int index, ai.monarchic.agent_protocol.v1.CampaignPipelineConnection.Builder builderForValue) {
      if (connectionsBuilder_ == null) {
        ensureConnectionsIsMutable();
        connections_.add(index, builderForValue.build());
        onChanged();
      } else {
        connectionsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .monarchic.agent_protocol.v1.CampaignPipelineConnection connections = 9;</code>
     */
    public Builder addAllConnections(
        java.lang.Iterable<? extends ai.monarchic.agent_protocol.v1.CampaignPipelineConnection> values) {
      if (connectionsBuilder_ == null) {
        ensureConnectionsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, connections_);
        onChanged();
      } else {
        connectionsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .monarchic.agent_protocol.v1.CampaignPipelineConnection connections = 9;</code>
     */
    public Builder clearConnections() {
      if (connectionsBuilder_ == null) {
        connections_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000100);
        onChanged();
      } else {
        connectionsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .monarchic.agent_protocol.v1.CampaignPipelineConnection connections = 9;</code>
     */
    public Builder removeConnections(int index) {
      if (connectionsBuilder_ == null) {
        ensureConnectionsIsMutable();
        connections_.remove(index);
        onChanged();
      } else {
        connectionsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .monarchic.agent_protocol.v1.CampaignPipelineConnection connections = 9;</code>
     */
    public ai.monarchic.agent_protocol.v1.CampaignPipelineConnection.Builder getConnectionsBuilder(
        int index) {
      return internalGetConnectionsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .monarchic.agent_protocol.v1.CampaignPipelineConnection connections = 9;</code>
     */
    public ai.monarchic.agent_protocol.v1.CampaignPipelineConnectionOrBuilder getConnectionsOrBuilder(
        int index) {
      if (connectionsBuilder_ == null) {
        return connections_.get(index);  } else {
        return connectionsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .monarchic.agent_protocol.v1.CampaignPipelineConnection connections = 9;</code>
     */
    public java.util.List<? extends ai.monarchic.agent_protocol.v1.CampaignPipelineConnectionOrBuilder>
         getConnectionsOrBuilderList() {
      if (connectionsBuilder_ != null) {
        return connectionsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(connections_);
      }
    }
    /**
     * <code>repeated .monarchic.agent_protocol.v1.CampaignPipelineConnection connections = 9;</code>
     */
    public ai.monarchic.agent_protocol.v1.CampaignPipelineConnection.Builder addConnectionsBuilder() {
      return internalGetConnectionsFieldBuilder().addBuilder(
          ai.monarchic.agent_protocol.v1.CampaignPipelineConnection.getDefaultInstance());
    }
    /**
     * <code>repeated .monarchic.agent_protocol.v1.CampaignPipelineConnection connections = 9;</code>
     */
    public ai.monarchic.agent_protocol.v1.CampaignPipelineConnection.Builder addConnectionsBuilder(
        int index) {
      return internalGetConnectionsFieldBuilder().addBuilder(
          index, ai.monarchic.agent_protocol.v1.CampaignPipelineConnection.getDefaultInstance());
    }
    /**
     * <code>repeated .monarchic.agent_protocol.v1.CampaignPipelineConnection connections = 9;</code>
     */
    public java.util.List<ai.monarchic.agent_protocol.v1.CampaignPipelineConnection.Builder>
         getConnectionsBuilderList() {
      return internalGetConnectionsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        ai.monarchic.agent_protocol.v1.CampaignPipelineConnection, ai.monarchic.agent_protocol.v1.CampaignPipelineConnection.Builder, ai.monarchic.agent_protocol.v1.CampaignPipelineConnectionOrBuilder>
        internalGetConnectionsFieldBuilder() {
      if (connectionsBuilder_ == null) {
        connectionsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            ai.monarchic.agent_protocol.v1.CampaignPipelineConnection, ai.monarchic.agent_protocol.v1.CampaignPipelineConnection.Builder, ai.monarchic.agent_protocol.v1.CampaignPipelineConnectionOrBuilder>(
                connections_,
                ((bitField0_ & 0x00000100) != 0),
                getParentForChildren(),
                isClean());
        connections_ = null;
      }
      return connectionsBuilder_;
    }

    private java.util.List<ai.monarchic.agent_protocol.v1.CampaignPipelineTaskRef> tasks_ =
      java.util.Collections.emptyList();
    private void ensureTasksIsMutable() {
      if (!((bitField0_ & 0x00000200) != 0)) {
        tasks_ = new java.util.ArrayList<ai.monarchic.agent_protocol.v1.CampaignPipelineTaskRef>(tasks_);
        bitField0_ |= 0x00000200;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        ai.monarchic.agent_protocol.v1.CampaignPipelineTaskRef, ai.monarchic.agent_protocol.v1.CampaignPipelineTaskRef.Builder, ai.monarchic.agent_protocol.v1.CampaignPipelineTaskRefOrBuilder> tasksBuilder_;

    /**
     * <code>repeated .monarchic.agent_protocol.v1.CampaignPipelineTaskRef tasks = 10;</code>
     */
    public java.util.List<ai.monarchic.agent_protocol.v1.CampaignPipelineTaskRef> getTasksList() {
      if (tasksBuilder_ == null) {
        return java.util.Collections.unmodifiableList(tasks_);
      } else {
        return tasksBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .monarchic.agent_protocol.v1.CampaignPipelineTaskRef tasks = 10;</code>
     */
    public int getTasksCount() {
      if (tasksBuilder_ == null) {
        return tasks_.size();
      } else {
        return tasksBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .monarchic.agent_protocol.v1.CampaignPipelineTaskRef tasks = 10;</code>
     */
    public ai.monarchic.agent_protocol.v1.CampaignPipelineTaskRef getTasks(int index) {
      if (tasksBuilder_ == null) {
        return tasks_.get(index);
      } else {
        return tasksBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .monarchic.agent_protocol.v1.CampaignPipelineTaskRef tasks = 10;</code>
     */
    public Builder setTasks(
        int index, ai.monarchic.agent_protocol.v1.CampaignPipelineTaskRef value) {
      if (tasksBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTasksIsMutable();
        tasks_.set(index, value);
        onChanged();
      } else {
        tasksBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .monarchic.agent_protocol.v1.CampaignPipelineTaskRef tasks = 10;</code>
     */
    public Builder setTasks(
        int index, ai.monarchic.agent_protocol.v1.CampaignPipelineTaskRef.Builder builderForValue) {
      if (tasksBuilder_ == null) {
        ensureTasksIsMutable();
        tasks_.set(index, builderForValue.build());
        onChanged();
      } else {
        tasksBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .monarchic.agent_protocol.v1.CampaignPipelineTaskRef tasks = 10;</code>
     */
    public Builder addTasks(ai.monarchic.agent_protocol.v1.CampaignPipelineTaskRef value) {
      if (tasksBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTasksIsMutable();
        tasks_.add(value);
        onChanged();
      } else {
        tasksBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .monarchic.agent_protocol.v1.CampaignPipelineTaskRef tasks = 10;</code>
     */
    public Builder addTasks(
        int index, ai.monarchic.agent_protocol.v1.CampaignPipelineTaskRef value) {
      if (tasksBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTasksIsMutable();
        tasks_.add(index, value);
        onChanged();
      } else {
        tasksBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .monarchic.agent_protocol.v1.CampaignPipelineTaskRef tasks = 10;</code>
     */
    public Builder addTasks(
        ai.monarchic.agent_protocol.v1.CampaignPipelineTaskRef.Builder builderForValue) {
      if (tasksBuilder_ == null) {
        ensureTasksIsMutable();
        tasks_.add(builderForValue.build());
        onChanged();
      } else {
        tasksBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .monarchic.agent_protocol.v1.CampaignPipelineTaskRef tasks = 10;</code>
     */
    public Builder addTasks(
        int index, ai.monarchic.agent_protocol.v1.CampaignPipelineTaskRef.Builder builderForValue) {
      if (tasksBuilder_ == null) {
        ensureTasksIsMutable();
        tasks_.add(index, builderForValue.build());
        onChanged();
      } else {
        tasksBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .monarchic.agent_protocol.v1.CampaignPipelineTaskRef tasks = 10;</code>
     */
    public Builder addAllTasks(
        java.lang.Iterable<? extends ai.monarchic.agent_protocol.v1.CampaignPipelineTaskRef> values) {
      if (tasksBuilder_ == null) {
        ensureTasksIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, tasks_);
        onChanged();
      } else {
        tasksBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .monarchic.agent_protocol.v1.CampaignPipelineTaskRef tasks = 10;</code>
     */
    public Builder clearTasks() {
      if (tasksBuilder_ == null) {
        tasks_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000200);
        onChanged();
      } else {
        tasksBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .monarchic.agent_protocol.v1.CampaignPipelineTaskRef tasks = 10;</code>
     */
    public Builder removeTasks(int index) {
      if (tasksBuilder_ == null) {
        ensureTasksIsMutable();
        tasks_.remove(index);
        onChanged();
      } else {
        tasksBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .monarchic.agent_protocol.v1.CampaignPipelineTaskRef tasks = 10;</code>
     */
    public ai.monarchic.agent_protocol.v1.CampaignPipelineTaskRef.Builder getTasksBuilder(
        int index) {
      return internalGetTasksFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .monarchic.agent_protocol.v1.CampaignPipelineTaskRef tasks = 10;</code>
     */
    public ai.monarchic.agent_protocol.v1.CampaignPipelineTaskRefOrBuilder getTasksOrBuilder(
        int index) {
      if (tasksBuilder_ == null) {
        return tasks_.get(index);  } else {
        return tasksBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .monarchic.agent_protocol.v1.CampaignPipelineTaskRef tasks = 10;</code>
     */
    public java.util.List<? extends ai.monarchic.agent_protocol.v1.CampaignPipelineTaskRefOrBuilder>
         getTasksOrBuilderList() {
      if (tasksBuilder_ != null) {
        return tasksBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(tasks_);
      }
    }
    /**
     * <code>repeated .monarchic.agent_protocol.v1.CampaignPipelineTaskRef tasks = 10;</code>
     */
    public ai.monarchic.agent_protocol.v1.CampaignPipelineTaskRef.Builder addTasksBuilder() {
      return internalGetTasksFieldBuilder().addBuilder(
          ai.monarchic.agent_protocol.v1.CampaignPipelineTaskRef.getDefaultInstance());
    }
    /**
     * <code>repeated .monarchic.agent_protocol.v1.CampaignPipelineTaskRef tasks = 10;</code>
     */
    public ai.monarchic.agent_protocol.v1.CampaignPipelineTaskRef.Builder addTasksBuilder(
        int index) {
      return internalGetTasksFieldBuilder().addBuilder(
          index, ai.monarchic.agent_protocol.v1.CampaignPipelineTaskRef.getDefaultInstance());
    }
    /**
     * <code>repeated .monarchic.agent_protocol.v1.CampaignPipelineTaskRef tasks = 10;</code>
     */
    public java.util.List<ai.monarchic.agent_protocol.v1.CampaignPipelineTaskRef.Builder>
         getTasksBuilderList() {
      return internalGetTasksFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        ai.monarchic.agent_protocol.v1.CampaignPipelineTaskRef, ai.monarchic.agent_protocol.v1.CampaignPipelineTaskRef.Builder, ai.monarchic.agent_protocol.v1.CampaignPipelineTaskRefOrBuilder>
        internalGetTasksFieldBuilder() {
      if (tasksBuilder_ == null) {
        tasksBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            ai.monarchic.agent_protocol.v1.CampaignPipelineTaskRef, ai.monarchic.agent_protocol.v1.CampaignPipelineTaskRef.Builder, ai.monarchic.agent_protocol.v1.CampaignPipelineTaskRefOrBuilder>(
                tasks_,
                ((bitField0_ & 0x00000200) != 0),
                getParentForChildren(),
                isClean());
        tasks_ = null;
      }
      return tasksBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:monarchic.agent_protocol.v1.CampaignPipelineSpec)
  }

  // @@protoc_insertion_point(class_scope:monarchic.agent_protocol.v1.CampaignPipelineSpec)
  private static final ai.monarchic.agent_protocol.v1.CampaignPipelineSpec DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ai.monarchic.agent_protocol.v1.CampaignPipelineSpec();
  }

  public static ai.monarchic.agent_protocol.v1.CampaignPipelineSpec getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CampaignPipelineSpec>
      PARSER = new com.google.protobuf.AbstractParser<CampaignPipelineSpec>() {
    @java.lang.Override
    public CampaignPipelineSpec parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<CampaignPipelineSpec> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CampaignPipelineSpec> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ai.monarchic.agent_protocol.v1.CampaignPipelineSpec getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}
