// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: monarchic_agent_protocol.proto
// Protobuf Java Version: 4.32.1

package ai.monarchic.agent_protocol.v1;

/**
 * Protobuf type {@code monarchic.agent_protocol.v1.DigestManifest}
 */
@com.google.protobuf.Generated
public final class DigestManifest extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:monarchic.agent_protocol.v1.DigestManifest)
    DigestManifestOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 32,
      /* patch= */ 1,
      /* suffix= */ "",
      DigestManifest.class.getName());
  }
  // Use DigestManifest.newBuilder() to construct.
  private DigestManifest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private DigestManifest() {
    contractVersion_ = "";
    manifestId_ = "";
    runId_ = "";
    planId_ = "";
    combinedDigest_ = "";
    eventDigest_ = "";
    artifactDescriptors_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ai.monarchic.agent_protocol.v1.MonarchicAgentProtocolV1.internal_static_monarchic_agent_protocol_v1_DigestManifest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ai.monarchic.agent_protocol.v1.MonarchicAgentProtocolV1.internal_static_monarchic_agent_protocol_v1_DigestManifest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ai.monarchic.agent_protocol.v1.DigestManifest.class, ai.monarchic.agent_protocol.v1.DigestManifest.Builder.class);
  }

  public static final int CONTRACT_VERSION_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object contractVersion_ = "";
  /**
   * <code>string contract_version = 1;</code>
   * @return The contractVersion.
   */
  @java.lang.Override
  public java.lang.String getContractVersion() {
    java.lang.Object ref = contractVersion_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      contractVersion_ = s;
      return s;
    }
  }
  /**
   * <code>string contract_version = 1;</code>
   * @return The bytes for contractVersion.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getContractVersionBytes() {
    java.lang.Object ref = contractVersion_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      contractVersion_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MANIFEST_ID_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object manifestId_ = "";
  /**
   * <code>string manifest_id = 2;</code>
   * @return The manifestId.
   */
  @java.lang.Override
  public java.lang.String getManifestId() {
    java.lang.Object ref = manifestId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      manifestId_ = s;
      return s;
    }
  }
  /**
   * <code>string manifest_id = 2;</code>
   * @return The bytes for manifestId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getManifestIdBytes() {
    java.lang.Object ref = manifestId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      manifestId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RUN_ID_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object runId_ = "";
  /**
   * <code>string run_id = 3;</code>
   * @return The runId.
   */
  @java.lang.Override
  public java.lang.String getRunId() {
    java.lang.Object ref = runId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      runId_ = s;
      return s;
    }
  }
  /**
   * <code>string run_id = 3;</code>
   * @return The bytes for runId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRunIdBytes() {
    java.lang.Object ref = runId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      runId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PLAN_ID_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object planId_ = "";
  /**
   * <code>string plan_id = 4;</code>
   * @return The planId.
   */
  @java.lang.Override
  public java.lang.String getPlanId() {
    java.lang.Object ref = planId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      planId_ = s;
      return s;
    }
  }
  /**
   * <code>string plan_id = 4;</code>
   * @return The bytes for planId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPlanIdBytes() {
    java.lang.Object ref = planId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      planId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CREATED_AT_FIELD_NUMBER = 5;
  private long createdAt_ = 0L;
  /**
   * <code>uint64 created_at = 5;</code>
   * @return The createdAt.
   */
  @java.lang.Override
  public long getCreatedAt() {
    return createdAt_;
  }

  public static final int COMBINED_DIGEST_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private volatile java.lang.Object combinedDigest_ = "";
  /**
   * <code>string combined_digest = 6;</code>
   * @return The combinedDigest.
   */
  @java.lang.Override
  public java.lang.String getCombinedDigest() {
    java.lang.Object ref = combinedDigest_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      combinedDigest_ = s;
      return s;
    }
  }
  /**
   * <code>string combined_digest = 6;</code>
   * @return The bytes for combinedDigest.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCombinedDigestBytes() {
    java.lang.Object ref = combinedDigest_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      combinedDigest_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EVENT_DIGEST_FIELD_NUMBER = 7;
  @SuppressWarnings("serial")
  private volatile java.lang.Object eventDigest_ = "";
  /**
   * <code>string event_digest = 7;</code>
   * @return The eventDigest.
   */
  @java.lang.Override
  public java.lang.String getEventDigest() {
    java.lang.Object ref = eventDigest_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      eventDigest_ = s;
      return s;
    }
  }
  /**
   * <code>string event_digest = 7;</code>
   * @return The bytes for eventDigest.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getEventDigestBytes() {
    java.lang.Object ref = eventDigest_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      eventDigest_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ARTIFACT_DESCRIPTORS_FIELD_NUMBER = 8;
  @SuppressWarnings("serial")
  private java.util.List<ai.monarchic.agent_protocol.v1.ArtifactDescriptor> artifactDescriptors_;
  /**
   * <code>repeated .monarchic.agent_protocol.v1.ArtifactDescriptor artifact_descriptors = 8;</code>
   */
  @java.lang.Override
  public java.util.List<ai.monarchic.agent_protocol.v1.ArtifactDescriptor> getArtifactDescriptorsList() {
    return artifactDescriptors_;
  }
  /**
   * <code>repeated .monarchic.agent_protocol.v1.ArtifactDescriptor artifact_descriptors = 8;</code>
   */
  @java.lang.Override
  public java.util.List<? extends ai.monarchic.agent_protocol.v1.ArtifactDescriptorOrBuilder> 
      getArtifactDescriptorsOrBuilderList() {
    return artifactDescriptors_;
  }
  /**
   * <code>repeated .monarchic.agent_protocol.v1.ArtifactDescriptor artifact_descriptors = 8;</code>
   */
  @java.lang.Override
  public int getArtifactDescriptorsCount() {
    return artifactDescriptors_.size();
  }
  /**
   * <code>repeated .monarchic.agent_protocol.v1.ArtifactDescriptor artifact_descriptors = 8;</code>
   */
  @java.lang.Override
  public ai.monarchic.agent_protocol.v1.ArtifactDescriptor getArtifactDescriptors(int index) {
    return artifactDescriptors_.get(index);
  }
  /**
   * <code>repeated .monarchic.agent_protocol.v1.ArtifactDescriptor artifact_descriptors = 8;</code>
   */
  @java.lang.Override
  public ai.monarchic.agent_protocol.v1.ArtifactDescriptorOrBuilder getArtifactDescriptorsOrBuilder(
      int index) {
    return artifactDescriptors_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(contractVersion_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, contractVersion_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(manifestId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, manifestId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(runId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, runId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(planId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 4, planId_);
    }
    if (createdAt_ != 0L) {
      output.writeUInt64(5, createdAt_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(combinedDigest_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 6, combinedDigest_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(eventDigest_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 7, eventDigest_);
    }
    for (int i = 0; i < artifactDescriptors_.size(); i++) {
      output.writeMessage(8, artifactDescriptors_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(contractVersion_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, contractVersion_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(manifestId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, manifestId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(runId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, runId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(planId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(4, planId_);
    }
    if (createdAt_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(5, createdAt_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(combinedDigest_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(6, combinedDigest_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(eventDigest_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(7, eventDigest_);
    }
    for (int i = 0; i < artifactDescriptors_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(8, artifactDescriptors_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ai.monarchic.agent_protocol.v1.DigestManifest)) {
      return super.equals(obj);
    }
    ai.monarchic.agent_protocol.v1.DigestManifest other = (ai.monarchic.agent_protocol.v1.DigestManifest) obj;

    if (!getContractVersion()
        .equals(other.getContractVersion())) return false;
    if (!getManifestId()
        .equals(other.getManifestId())) return false;
    if (!getRunId()
        .equals(other.getRunId())) return false;
    if (!getPlanId()
        .equals(other.getPlanId())) return false;
    if (getCreatedAt()
        != other.getCreatedAt()) return false;
    if (!getCombinedDigest()
        .equals(other.getCombinedDigest())) return false;
    if (!getEventDigest()
        .equals(other.getEventDigest())) return false;
    if (!getArtifactDescriptorsList()
        .equals(other.getArtifactDescriptorsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CONTRACT_VERSION_FIELD_NUMBER;
    hash = (53 * hash) + getContractVersion().hashCode();
    hash = (37 * hash) + MANIFEST_ID_FIELD_NUMBER;
    hash = (53 * hash) + getManifestId().hashCode();
    hash = (37 * hash) + RUN_ID_FIELD_NUMBER;
    hash = (53 * hash) + getRunId().hashCode();
    hash = (37 * hash) + PLAN_ID_FIELD_NUMBER;
    hash = (53 * hash) + getPlanId().hashCode();
    hash = (37 * hash) + CREATED_AT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getCreatedAt());
    hash = (37 * hash) + COMBINED_DIGEST_FIELD_NUMBER;
    hash = (53 * hash) + getCombinedDigest().hashCode();
    hash = (37 * hash) + EVENT_DIGEST_FIELD_NUMBER;
    hash = (53 * hash) + getEventDigest().hashCode();
    if (getArtifactDescriptorsCount() > 0) {
      hash = (37 * hash) + ARTIFACT_DESCRIPTORS_FIELD_NUMBER;
      hash = (53 * hash) + getArtifactDescriptorsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ai.monarchic.agent_protocol.v1.DigestManifest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ai.monarchic.agent_protocol.v1.DigestManifest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ai.monarchic.agent_protocol.v1.DigestManifest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ai.monarchic.agent_protocol.v1.DigestManifest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ai.monarchic.agent_protocol.v1.DigestManifest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ai.monarchic.agent_protocol.v1.DigestManifest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ai.monarchic.agent_protocol.v1.DigestManifest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static ai.monarchic.agent_protocol.v1.DigestManifest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static ai.monarchic.agent_protocol.v1.DigestManifest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static ai.monarchic.agent_protocol.v1.DigestManifest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ai.monarchic.agent_protocol.v1.DigestManifest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static ai.monarchic.agent_protocol.v1.DigestManifest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ai.monarchic.agent_protocol.v1.DigestManifest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code monarchic.agent_protocol.v1.DigestManifest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:monarchic.agent_protocol.v1.DigestManifest)
      ai.monarchic.agent_protocol.v1.DigestManifestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ai.monarchic.agent_protocol.v1.MonarchicAgentProtocolV1.internal_static_monarchic_agent_protocol_v1_DigestManifest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ai.monarchic.agent_protocol.v1.MonarchicAgentProtocolV1.internal_static_monarchic_agent_protocol_v1_DigestManifest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ai.monarchic.agent_protocol.v1.DigestManifest.class, ai.monarchic.agent_protocol.v1.DigestManifest.Builder.class);
    }

    // Construct using ai.monarchic.agent_protocol.v1.DigestManifest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      contractVersion_ = "";
      manifestId_ = "";
      runId_ = "";
      planId_ = "";
      createdAt_ = 0L;
      combinedDigest_ = "";
      eventDigest_ = "";
      if (artifactDescriptorsBuilder_ == null) {
        artifactDescriptors_ = java.util.Collections.emptyList();
      } else {
        artifactDescriptors_ = null;
        artifactDescriptorsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000080);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ai.monarchic.agent_protocol.v1.MonarchicAgentProtocolV1.internal_static_monarchic_agent_protocol_v1_DigestManifest_descriptor;
    }

    @java.lang.Override
    public ai.monarchic.agent_protocol.v1.DigestManifest getDefaultInstanceForType() {
      return ai.monarchic.agent_protocol.v1.DigestManifest.getDefaultInstance();
    }

    @java.lang.Override
    public ai.monarchic.agent_protocol.v1.DigestManifest build() {
      ai.monarchic.agent_protocol.v1.DigestManifest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ai.monarchic.agent_protocol.v1.DigestManifest buildPartial() {
      ai.monarchic.agent_protocol.v1.DigestManifest result = new ai.monarchic.agent_protocol.v1.DigestManifest(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(ai.monarchic.agent_protocol.v1.DigestManifest result) {
      if (artifactDescriptorsBuilder_ == null) {
        if (((bitField0_ & 0x00000080) != 0)) {
          artifactDescriptors_ = java.util.Collections.unmodifiableList(artifactDescriptors_);
          bitField0_ = (bitField0_ & ~0x00000080);
        }
        result.artifactDescriptors_ = artifactDescriptors_;
      } else {
        result.artifactDescriptors_ = artifactDescriptorsBuilder_.build();
      }
    }

    private void buildPartial0(ai.monarchic.agent_protocol.v1.DigestManifest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.contractVersion_ = contractVersion_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.manifestId_ = manifestId_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.runId_ = runId_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.planId_ = planId_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.createdAt_ = createdAt_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.combinedDigest_ = combinedDigest_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.eventDigest_ = eventDigest_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ai.monarchic.agent_protocol.v1.DigestManifest) {
        return mergeFrom((ai.monarchic.agent_protocol.v1.DigestManifest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ai.monarchic.agent_protocol.v1.DigestManifest other) {
      if (other == ai.monarchic.agent_protocol.v1.DigestManifest.getDefaultInstance()) return this;
      if (!other.getContractVersion().isEmpty()) {
        contractVersion_ = other.contractVersion_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getManifestId().isEmpty()) {
        manifestId_ = other.manifestId_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getRunId().isEmpty()) {
        runId_ = other.runId_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.getPlanId().isEmpty()) {
        planId_ = other.planId_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (other.getCreatedAt() != 0L) {
        setCreatedAt(other.getCreatedAt());
      }
      if (!other.getCombinedDigest().isEmpty()) {
        combinedDigest_ = other.combinedDigest_;
        bitField0_ |= 0x00000020;
        onChanged();
      }
      if (!other.getEventDigest().isEmpty()) {
        eventDigest_ = other.eventDigest_;
        bitField0_ |= 0x00000040;
        onChanged();
      }
      if (artifactDescriptorsBuilder_ == null) {
        if (!other.artifactDescriptors_.isEmpty()) {
          if (artifactDescriptors_.isEmpty()) {
            artifactDescriptors_ = other.artifactDescriptors_;
            bitField0_ = (bitField0_ & ~0x00000080);
          } else {
            ensureArtifactDescriptorsIsMutable();
            artifactDescriptors_.addAll(other.artifactDescriptors_);
          }
          onChanged();
        }
      } else {
        if (!other.artifactDescriptors_.isEmpty()) {
          if (artifactDescriptorsBuilder_.isEmpty()) {
            artifactDescriptorsBuilder_.dispose();
            artifactDescriptorsBuilder_ = null;
            artifactDescriptors_ = other.artifactDescriptors_;
            bitField0_ = (bitField0_ & ~0x00000080);
            artifactDescriptorsBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 internalGetArtifactDescriptorsFieldBuilder() : null;
          } else {
            artifactDescriptorsBuilder_.addAllMessages(other.artifactDescriptors_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              contractVersion_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              manifestId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              runId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              planId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 40: {
              createdAt_ = input.readUInt64();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            case 50: {
              combinedDigest_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            case 58: {
              eventDigest_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000040;
              break;
            } // case 58
            case 66: {
              ai.monarchic.agent_protocol.v1.ArtifactDescriptor m =
                  input.readMessage(
                      ai.monarchic.agent_protocol.v1.ArtifactDescriptor.parser(),
                      extensionRegistry);
              if (artifactDescriptorsBuilder_ == null) {
                ensureArtifactDescriptorsIsMutable();
                artifactDescriptors_.add(m);
              } else {
                artifactDescriptorsBuilder_.addMessage(m);
              }
              break;
            } // case 66
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object contractVersion_ = "";
    /**
     * <code>string contract_version = 1;</code>
     * @return The contractVersion.
     */
    public java.lang.String getContractVersion() {
      java.lang.Object ref = contractVersion_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        contractVersion_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string contract_version = 1;</code>
     * @return The bytes for contractVersion.
     */
    public com.google.protobuf.ByteString
        getContractVersionBytes() {
      java.lang.Object ref = contractVersion_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        contractVersion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string contract_version = 1;</code>
     * @param value The contractVersion to set.
     * @return This builder for chaining.
     */
    public Builder setContractVersion(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      contractVersion_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string contract_version = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearContractVersion() {
      contractVersion_ = getDefaultInstance().getContractVersion();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string contract_version = 1;</code>
     * @param value The bytes for contractVersion to set.
     * @return This builder for chaining.
     */
    public Builder setContractVersionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      contractVersion_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object manifestId_ = "";
    /**
     * <code>string manifest_id = 2;</code>
     * @return The manifestId.
     */
    public java.lang.String getManifestId() {
      java.lang.Object ref = manifestId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        manifestId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string manifest_id = 2;</code>
     * @return The bytes for manifestId.
     */
    public com.google.protobuf.ByteString
        getManifestIdBytes() {
      java.lang.Object ref = manifestId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        manifestId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string manifest_id = 2;</code>
     * @param value The manifestId to set.
     * @return This builder for chaining.
     */
    public Builder setManifestId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      manifestId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string manifest_id = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearManifestId() {
      manifestId_ = getDefaultInstance().getManifestId();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string manifest_id = 2;</code>
     * @param value The bytes for manifestId to set.
     * @return This builder for chaining.
     */
    public Builder setManifestIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      manifestId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object runId_ = "";
    /**
     * <code>string run_id = 3;</code>
     * @return The runId.
     */
    public java.lang.String getRunId() {
      java.lang.Object ref = runId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        runId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string run_id = 3;</code>
     * @return The bytes for runId.
     */
    public com.google.protobuf.ByteString
        getRunIdBytes() {
      java.lang.Object ref = runId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        runId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string run_id = 3;</code>
     * @param value The runId to set.
     * @return This builder for chaining.
     */
    public Builder setRunId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      runId_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string run_id = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearRunId() {
      runId_ = getDefaultInstance().getRunId();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string run_id = 3;</code>
     * @param value The bytes for runId to set.
     * @return This builder for chaining.
     */
    public Builder setRunIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      runId_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.lang.Object planId_ = "";
    /**
     * <code>string plan_id = 4;</code>
     * @return The planId.
     */
    public java.lang.String getPlanId() {
      java.lang.Object ref = planId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        planId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string plan_id = 4;</code>
     * @return The bytes for planId.
     */
    public com.google.protobuf.ByteString
        getPlanIdBytes() {
      java.lang.Object ref = planId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        planId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string plan_id = 4;</code>
     * @param value The planId to set.
     * @return This builder for chaining.
     */
    public Builder setPlanId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      planId_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>string plan_id = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearPlanId() {
      planId_ = getDefaultInstance().getPlanId();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>string plan_id = 4;</code>
     * @param value The bytes for planId to set.
     * @return This builder for chaining.
     */
    public Builder setPlanIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      planId_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private long createdAt_ ;
    /**
     * <code>uint64 created_at = 5;</code>
     * @return The createdAt.
     */
    @java.lang.Override
    public long getCreatedAt() {
      return createdAt_;
    }
    /**
     * <code>uint64 created_at = 5;</code>
     * @param value The createdAt to set.
     * @return This builder for chaining.
     */
    public Builder setCreatedAt(long value) {

      createdAt_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 created_at = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearCreatedAt() {
      bitField0_ = (bitField0_ & ~0x00000010);
      createdAt_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object combinedDigest_ = "";
    /**
     * <code>string combined_digest = 6;</code>
     * @return The combinedDigest.
     */
    public java.lang.String getCombinedDigest() {
      java.lang.Object ref = combinedDigest_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        combinedDigest_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string combined_digest = 6;</code>
     * @return The bytes for combinedDigest.
     */
    public com.google.protobuf.ByteString
        getCombinedDigestBytes() {
      java.lang.Object ref = combinedDigest_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        combinedDigest_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string combined_digest = 6;</code>
     * @param value The combinedDigest to set.
     * @return This builder for chaining.
     */
    public Builder setCombinedDigest(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      combinedDigest_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>string combined_digest = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearCombinedDigest() {
      combinedDigest_ = getDefaultInstance().getCombinedDigest();
      bitField0_ = (bitField0_ & ~0x00000020);
      onChanged();
      return this;
    }
    /**
     * <code>string combined_digest = 6;</code>
     * @param value The bytes for combinedDigest to set.
     * @return This builder for chaining.
     */
    public Builder setCombinedDigestBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      combinedDigest_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }

    private java.lang.Object eventDigest_ = "";
    /**
     * <code>string event_digest = 7;</code>
     * @return The eventDigest.
     */
    public java.lang.String getEventDigest() {
      java.lang.Object ref = eventDigest_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        eventDigest_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string event_digest = 7;</code>
     * @return The bytes for eventDigest.
     */
    public com.google.protobuf.ByteString
        getEventDigestBytes() {
      java.lang.Object ref = eventDigest_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        eventDigest_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string event_digest = 7;</code>
     * @param value The eventDigest to set.
     * @return This builder for chaining.
     */
    public Builder setEventDigest(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      eventDigest_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>string event_digest = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearEventDigest() {
      eventDigest_ = getDefaultInstance().getEventDigest();
      bitField0_ = (bitField0_ & ~0x00000040);
      onChanged();
      return this;
    }
    /**
     * <code>string event_digest = 7;</code>
     * @param value The bytes for eventDigest to set.
     * @return This builder for chaining.
     */
    public Builder setEventDigestBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      eventDigest_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }

    private java.util.List<ai.monarchic.agent_protocol.v1.ArtifactDescriptor> artifactDescriptors_ =
      java.util.Collections.emptyList();
    private void ensureArtifactDescriptorsIsMutable() {
      if (!((bitField0_ & 0x00000080) != 0)) {
        artifactDescriptors_ = new java.util.ArrayList<ai.monarchic.agent_protocol.v1.ArtifactDescriptor>(artifactDescriptors_);
        bitField0_ |= 0x00000080;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        ai.monarchic.agent_protocol.v1.ArtifactDescriptor, ai.monarchic.agent_protocol.v1.ArtifactDescriptor.Builder, ai.monarchic.agent_protocol.v1.ArtifactDescriptorOrBuilder> artifactDescriptorsBuilder_;

    /**
     * <code>repeated .monarchic.agent_protocol.v1.ArtifactDescriptor artifact_descriptors = 8;</code>
     */
    public java.util.List<ai.monarchic.agent_protocol.v1.ArtifactDescriptor> getArtifactDescriptorsList() {
      if (artifactDescriptorsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(artifactDescriptors_);
      } else {
        return artifactDescriptorsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .monarchic.agent_protocol.v1.ArtifactDescriptor artifact_descriptors = 8;</code>
     */
    public int getArtifactDescriptorsCount() {
      if (artifactDescriptorsBuilder_ == null) {
        return artifactDescriptors_.size();
      } else {
        return artifactDescriptorsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .monarchic.agent_protocol.v1.ArtifactDescriptor artifact_descriptors = 8;</code>
     */
    public ai.monarchic.agent_protocol.v1.ArtifactDescriptor getArtifactDescriptors(int index) {
      if (artifactDescriptorsBuilder_ == null) {
        return artifactDescriptors_.get(index);
      } else {
        return artifactDescriptorsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .monarchic.agent_protocol.v1.ArtifactDescriptor artifact_descriptors = 8;</code>
     */
    public Builder setArtifactDescriptors(
        int index, ai.monarchic.agent_protocol.v1.ArtifactDescriptor value) {
      if (artifactDescriptorsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureArtifactDescriptorsIsMutable();
        artifactDescriptors_.set(index, value);
        onChanged();
      } else {
        artifactDescriptorsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .monarchic.agent_protocol.v1.ArtifactDescriptor artifact_descriptors = 8;</code>
     */
    public Builder setArtifactDescriptors(
        int index, ai.monarchic.agent_protocol.v1.ArtifactDescriptor.Builder builderForValue) {
      if (artifactDescriptorsBuilder_ == null) {
        ensureArtifactDescriptorsIsMutable();
        artifactDescriptors_.set(index, builderForValue.build());
        onChanged();
      } else {
        artifactDescriptorsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .monarchic.agent_protocol.v1.ArtifactDescriptor artifact_descriptors = 8;</code>
     */
    public Builder addArtifactDescriptors(ai.monarchic.agent_protocol.v1.ArtifactDescriptor value) {
      if (artifactDescriptorsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureArtifactDescriptorsIsMutable();
        artifactDescriptors_.add(value);
        onChanged();
      } else {
        artifactDescriptorsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .monarchic.agent_protocol.v1.ArtifactDescriptor artifact_descriptors = 8;</code>
     */
    public Builder addArtifactDescriptors(
        int index, ai.monarchic.agent_protocol.v1.ArtifactDescriptor value) {
      if (artifactDescriptorsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureArtifactDescriptorsIsMutable();
        artifactDescriptors_.add(index, value);
        onChanged();
      } else {
        artifactDescriptorsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .monarchic.agent_protocol.v1.ArtifactDescriptor artifact_descriptors = 8;</code>
     */
    public Builder addArtifactDescriptors(
        ai.monarchic.agent_protocol.v1.ArtifactDescriptor.Builder builderForValue) {
      if (artifactDescriptorsBuilder_ == null) {
        ensureArtifactDescriptorsIsMutable();
        artifactDescriptors_.add(builderForValue.build());
        onChanged();
      } else {
        artifactDescriptorsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .monarchic.agent_protocol.v1.ArtifactDescriptor artifact_descriptors = 8;</code>
     */
    public Builder addArtifactDescriptors(
        int index, ai.monarchic.agent_protocol.v1.ArtifactDescriptor.Builder builderForValue) {
      if (artifactDescriptorsBuilder_ == null) {
        ensureArtifactDescriptorsIsMutable();
        artifactDescriptors_.add(index, builderForValue.build());
        onChanged();
      } else {
        artifactDescriptorsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .monarchic.agent_protocol.v1.ArtifactDescriptor artifact_descriptors = 8;</code>
     */
    public Builder addAllArtifactDescriptors(
        java.lang.Iterable<? extends ai.monarchic.agent_protocol.v1.ArtifactDescriptor> values) {
      if (artifactDescriptorsBuilder_ == null) {
        ensureArtifactDescriptorsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, artifactDescriptors_);
        onChanged();
      } else {
        artifactDescriptorsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .monarchic.agent_protocol.v1.ArtifactDescriptor artifact_descriptors = 8;</code>
     */
    public Builder clearArtifactDescriptors() {
      if (artifactDescriptorsBuilder_ == null) {
        artifactDescriptors_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000080);
        onChanged();
      } else {
        artifactDescriptorsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .monarchic.agent_protocol.v1.ArtifactDescriptor artifact_descriptors = 8;</code>
     */
    public Builder removeArtifactDescriptors(int index) {
      if (artifactDescriptorsBuilder_ == null) {
        ensureArtifactDescriptorsIsMutable();
        artifactDescriptors_.remove(index);
        onChanged();
      } else {
        artifactDescriptorsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .monarchic.agent_protocol.v1.ArtifactDescriptor artifact_descriptors = 8;</code>
     */
    public ai.monarchic.agent_protocol.v1.ArtifactDescriptor.Builder getArtifactDescriptorsBuilder(
        int index) {
      return internalGetArtifactDescriptorsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .monarchic.agent_protocol.v1.ArtifactDescriptor artifact_descriptors = 8;</code>
     */
    public ai.monarchic.agent_protocol.v1.ArtifactDescriptorOrBuilder getArtifactDescriptorsOrBuilder(
        int index) {
      if (artifactDescriptorsBuilder_ == null) {
        return artifactDescriptors_.get(index);  } else {
        return artifactDescriptorsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .monarchic.agent_protocol.v1.ArtifactDescriptor artifact_descriptors = 8;</code>
     */
    public java.util.List<? extends ai.monarchic.agent_protocol.v1.ArtifactDescriptorOrBuilder> 
         getArtifactDescriptorsOrBuilderList() {
      if (artifactDescriptorsBuilder_ != null) {
        return artifactDescriptorsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(artifactDescriptors_);
      }
    }
    /**
     * <code>repeated .monarchic.agent_protocol.v1.ArtifactDescriptor artifact_descriptors = 8;</code>
     */
    public ai.monarchic.agent_protocol.v1.ArtifactDescriptor.Builder addArtifactDescriptorsBuilder() {
      return internalGetArtifactDescriptorsFieldBuilder().addBuilder(
          ai.monarchic.agent_protocol.v1.ArtifactDescriptor.getDefaultInstance());
    }
    /**
     * <code>repeated .monarchic.agent_protocol.v1.ArtifactDescriptor artifact_descriptors = 8;</code>
     */
    public ai.monarchic.agent_protocol.v1.ArtifactDescriptor.Builder addArtifactDescriptorsBuilder(
        int index) {
      return internalGetArtifactDescriptorsFieldBuilder().addBuilder(
          index, ai.monarchic.agent_protocol.v1.ArtifactDescriptor.getDefaultInstance());
    }
    /**
     * <code>repeated .monarchic.agent_protocol.v1.ArtifactDescriptor artifact_descriptors = 8;</code>
     */
    public java.util.List<ai.monarchic.agent_protocol.v1.ArtifactDescriptor.Builder> 
         getArtifactDescriptorsBuilderList() {
      return internalGetArtifactDescriptorsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        ai.monarchic.agent_protocol.v1.ArtifactDescriptor, ai.monarchic.agent_protocol.v1.ArtifactDescriptor.Builder, ai.monarchic.agent_protocol.v1.ArtifactDescriptorOrBuilder> 
        internalGetArtifactDescriptorsFieldBuilder() {
      if (artifactDescriptorsBuilder_ == null) {
        artifactDescriptorsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            ai.monarchic.agent_protocol.v1.ArtifactDescriptor, ai.monarchic.agent_protocol.v1.ArtifactDescriptor.Builder, ai.monarchic.agent_protocol.v1.ArtifactDescriptorOrBuilder>(
                artifactDescriptors_,
                ((bitField0_ & 0x00000080) != 0),
                getParentForChildren(),
                isClean());
        artifactDescriptors_ = null;
      }
      return artifactDescriptorsBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:monarchic.agent_protocol.v1.DigestManifest)
  }

  // @@protoc_insertion_point(class_scope:monarchic.agent_protocol.v1.DigestManifest)
  private static final ai.monarchic.agent_protocol.v1.DigestManifest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ai.monarchic.agent_protocol.v1.DigestManifest();
  }

  public static ai.monarchic.agent_protocol.v1.DigestManifest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DigestManifest>
      PARSER = new com.google.protobuf.AbstractParser<DigestManifest>() {
    @java.lang.Override
    public DigestManifest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<DigestManifest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<DigestManifest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ai.monarchic.agent_protocol.v1.DigestManifest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

