// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: monarchic_agent_protocol.proto
// Protobuf Java Version: 4.32.1

package ai.monarchic.agent_protocol.v1;

/**
 * Protobuf type {@code monarchic.agent_protocol.v1.GetControlPlaneRunActivityPageResponse}
 */
@com.google.protobuf.Generated
public final class GetControlPlaneRunActivityPageResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:monarchic.agent_protocol.v1.GetControlPlaneRunActivityPageResponse)
    GetControlPlaneRunActivityPageResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 32,
      /* patch= */ 1,
      /* suffix= */ "",
      GetControlPlaneRunActivityPageResponse.class.getName());
  }
  // Use GetControlPlaneRunActivityPageResponse.newBuilder() to construct.
  private GetControlPlaneRunActivityPageResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private GetControlPlaneRunActivityPageResponse() {
    contractVersion_ = "";
    records_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ai.monarchic.agent_protocol.v1.MonarchicAgentProtocolV1.internal_static_monarchic_agent_protocol_v1_GetControlPlaneRunActivityPageResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ai.monarchic.agent_protocol.v1.MonarchicAgentProtocolV1.internal_static_monarchic_agent_protocol_v1_GetControlPlaneRunActivityPageResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ai.monarchic.agent_protocol.v1.GetControlPlaneRunActivityPageResponse.class, ai.monarchic.agent_protocol.v1.GetControlPlaneRunActivityPageResponse.Builder.class);
  }

  private int bitField0_;
  public static final int CONTRACT_VERSION_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object contractVersion_ = "";
  /**
   * <code>string contract_version = 1;</code>
   * @return The contractVersion.
   */
  @java.lang.Override
  public java.lang.String getContractVersion() {
    java.lang.Object ref = contractVersion_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      contractVersion_ = s;
      return s;
    }
  }
  /**
   * <code>string contract_version = 1;</code>
   * @return The bytes for contractVersion.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getContractVersionBytes() {
    java.lang.Object ref = contractVersion_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      contractVersion_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RECORDS_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private java.util.List<ai.monarchic.agent_protocol.v1.RunEventRecord> records_;
  /**
   * <code>repeated .monarchic.agent_protocol.v1.RunEventRecord records = 2;</code>
   */
  @java.lang.Override
  public java.util.List<ai.monarchic.agent_protocol.v1.RunEventRecord> getRecordsList() {
    return records_;
  }
  /**
   * <code>repeated .monarchic.agent_protocol.v1.RunEventRecord records = 2;</code>
   */
  @java.lang.Override
  public java.util.List<? extends ai.monarchic.agent_protocol.v1.RunEventRecordOrBuilder>
      getRecordsOrBuilderList() {
    return records_;
  }
  /**
   * <code>repeated .monarchic.agent_protocol.v1.RunEventRecord records = 2;</code>
   */
  @java.lang.Override
  public int getRecordsCount() {
    return records_.size();
  }
  /**
   * <code>repeated .monarchic.agent_protocol.v1.RunEventRecord records = 2;</code>
   */
  @java.lang.Override
  public ai.monarchic.agent_protocol.v1.RunEventRecord getRecords(int index) {
    return records_.get(index);
  }
  /**
   * <code>repeated .monarchic.agent_protocol.v1.RunEventRecord records = 2;</code>
   */
  @java.lang.Override
  public ai.monarchic.agent_protocol.v1.RunEventRecordOrBuilder getRecordsOrBuilder(
      int index) {
    return records_.get(index);
  }

  public static final int NEXT_CURSOR_FIELD_NUMBER = 3;
  private ai.monarchic.agent_protocol.v1.ControlPlaneRunActivityCursor nextCursor_;
  /**
   * <code>.monarchic.agent_protocol.v1.ControlPlaneRunActivityCursor next_cursor = 3;</code>
   * @return Whether the nextCursor field is set.
   */
  @java.lang.Override
  public boolean hasNextCursor() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.monarchic.agent_protocol.v1.ControlPlaneRunActivityCursor next_cursor = 3;</code>
   * @return The nextCursor.
   */
  @java.lang.Override
  public ai.monarchic.agent_protocol.v1.ControlPlaneRunActivityCursor getNextCursor() {
    return nextCursor_ == null ? ai.monarchic.agent_protocol.v1.ControlPlaneRunActivityCursor.getDefaultInstance() : nextCursor_;
  }
  /**
   * <code>.monarchic.agent_protocol.v1.ControlPlaneRunActivityCursor next_cursor = 3;</code>
   */
  @java.lang.Override
  public ai.monarchic.agent_protocol.v1.ControlPlaneRunActivityCursorOrBuilder getNextCursorOrBuilder() {
    return nextCursor_ == null ? ai.monarchic.agent_protocol.v1.ControlPlaneRunActivityCursor.getDefaultInstance() : nextCursor_;
  }

  public static final int EXTENSIONS_FIELD_NUMBER = 4;
  private com.google.protobuf.Struct extensions_;
  /**
   * <code>.google.protobuf.Struct extensions = 4;</code>
   * @return Whether the extensions field is set.
   */
  @java.lang.Override
  public boolean hasExtensions() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>.google.protobuf.Struct extensions = 4;</code>
   * @return The extensions.
   */
  @java.lang.Override
  public com.google.protobuf.Struct getExtensions() {
    return extensions_ == null ? com.google.protobuf.Struct.getDefaultInstance() : extensions_;
  }
  /**
   * <code>.google.protobuf.Struct extensions = 4;</code>
   */
  @java.lang.Override
  public com.google.protobuf.StructOrBuilder getExtensionsOrBuilder() {
    return extensions_ == null ? com.google.protobuf.Struct.getDefaultInstance() : extensions_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(contractVersion_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, contractVersion_);
    }
    for (int i = 0; i < records_.size(); i++) {
      output.writeMessage(2, records_.get(i));
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(3, getNextCursor());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(4, getExtensions());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(contractVersion_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, contractVersion_);
    }
    for (int i = 0; i < records_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, records_.get(i));
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getNextCursor());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getExtensions());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ai.monarchic.agent_protocol.v1.GetControlPlaneRunActivityPageResponse)) {
      return super.equals(obj);
    }
    ai.monarchic.agent_protocol.v1.GetControlPlaneRunActivityPageResponse other = (ai.monarchic.agent_protocol.v1.GetControlPlaneRunActivityPageResponse) obj;

    if (!getContractVersion()
        .equals(other.getContractVersion())) return false;
    if (!getRecordsList()
        .equals(other.getRecordsList())) return false;
    if (hasNextCursor() != other.hasNextCursor()) return false;
    if (hasNextCursor()) {
      if (!getNextCursor()
          .equals(other.getNextCursor())) return false;
    }
    if (hasExtensions() != other.hasExtensions()) return false;
    if (hasExtensions()) {
      if (!getExtensions()
          .equals(other.getExtensions())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CONTRACT_VERSION_FIELD_NUMBER;
    hash = (53 * hash) + getContractVersion().hashCode();
    if (getRecordsCount() > 0) {
      hash = (37 * hash) + RECORDS_FIELD_NUMBER;
      hash = (53 * hash) + getRecordsList().hashCode();
    }
    if (hasNextCursor()) {
      hash = (37 * hash) + NEXT_CURSOR_FIELD_NUMBER;
      hash = (53 * hash) + getNextCursor().hashCode();
    }
    if (hasExtensions()) {
      hash = (37 * hash) + EXTENSIONS_FIELD_NUMBER;
      hash = (53 * hash) + getExtensions().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ai.monarchic.agent_protocol.v1.GetControlPlaneRunActivityPageResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ai.monarchic.agent_protocol.v1.GetControlPlaneRunActivityPageResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ai.monarchic.agent_protocol.v1.GetControlPlaneRunActivityPageResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ai.monarchic.agent_protocol.v1.GetControlPlaneRunActivityPageResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ai.monarchic.agent_protocol.v1.GetControlPlaneRunActivityPageResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ai.monarchic.agent_protocol.v1.GetControlPlaneRunActivityPageResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ai.monarchic.agent_protocol.v1.GetControlPlaneRunActivityPageResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static ai.monarchic.agent_protocol.v1.GetControlPlaneRunActivityPageResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static ai.monarchic.agent_protocol.v1.GetControlPlaneRunActivityPageResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static ai.monarchic.agent_protocol.v1.GetControlPlaneRunActivityPageResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ai.monarchic.agent_protocol.v1.GetControlPlaneRunActivityPageResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static ai.monarchic.agent_protocol.v1.GetControlPlaneRunActivityPageResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ai.monarchic.agent_protocol.v1.GetControlPlaneRunActivityPageResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code monarchic.agent_protocol.v1.GetControlPlaneRunActivityPageResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:monarchic.agent_protocol.v1.GetControlPlaneRunActivityPageResponse)
      ai.monarchic.agent_protocol.v1.GetControlPlaneRunActivityPageResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ai.monarchic.agent_protocol.v1.MonarchicAgentProtocolV1.internal_static_monarchic_agent_protocol_v1_GetControlPlaneRunActivityPageResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ai.monarchic.agent_protocol.v1.MonarchicAgentProtocolV1.internal_static_monarchic_agent_protocol_v1_GetControlPlaneRunActivityPageResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ai.monarchic.agent_protocol.v1.GetControlPlaneRunActivityPageResponse.class, ai.monarchic.agent_protocol.v1.GetControlPlaneRunActivityPageResponse.Builder.class);
    }

    // Construct using ai.monarchic.agent_protocol.v1.GetControlPlaneRunActivityPageResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetRecordsFieldBuilder();
        internalGetNextCursorFieldBuilder();
        internalGetExtensionsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      contractVersion_ = "";
      if (recordsBuilder_ == null) {
        records_ = java.util.Collections.emptyList();
      } else {
        records_ = null;
        recordsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      nextCursor_ = null;
      if (nextCursorBuilder_ != null) {
        nextCursorBuilder_.dispose();
        nextCursorBuilder_ = null;
      }
      extensions_ = null;
      if (extensionsBuilder_ != null) {
        extensionsBuilder_.dispose();
        extensionsBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ai.monarchic.agent_protocol.v1.MonarchicAgentProtocolV1.internal_static_monarchic_agent_protocol_v1_GetControlPlaneRunActivityPageResponse_descriptor;
    }

    @java.lang.Override
    public ai.monarchic.agent_protocol.v1.GetControlPlaneRunActivityPageResponse getDefaultInstanceForType() {
      return ai.monarchic.agent_protocol.v1.GetControlPlaneRunActivityPageResponse.getDefaultInstance();
    }

    @java.lang.Override
    public ai.monarchic.agent_protocol.v1.GetControlPlaneRunActivityPageResponse build() {
      ai.monarchic.agent_protocol.v1.GetControlPlaneRunActivityPageResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ai.monarchic.agent_protocol.v1.GetControlPlaneRunActivityPageResponse buildPartial() {
      ai.monarchic.agent_protocol.v1.GetControlPlaneRunActivityPageResponse result = new ai.monarchic.agent_protocol.v1.GetControlPlaneRunActivityPageResponse(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(ai.monarchic.agent_protocol.v1.GetControlPlaneRunActivityPageResponse result) {
      if (recordsBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          records_ = java.util.Collections.unmodifiableList(records_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.records_ = records_;
      } else {
        result.records_ = recordsBuilder_.build();
      }
    }

    private void buildPartial0(ai.monarchic.agent_protocol.v1.GetControlPlaneRunActivityPageResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.contractVersion_ = contractVersion_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.nextCursor_ = nextCursorBuilder_ == null
            ? nextCursor_
            : nextCursorBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.extensions_ = extensionsBuilder_ == null
            ? extensions_
            : extensionsBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ai.monarchic.agent_protocol.v1.GetControlPlaneRunActivityPageResponse) {
        return mergeFrom((ai.monarchic.agent_protocol.v1.GetControlPlaneRunActivityPageResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ai.monarchic.agent_protocol.v1.GetControlPlaneRunActivityPageResponse other) {
      if (other == ai.monarchic.agent_protocol.v1.GetControlPlaneRunActivityPageResponse.getDefaultInstance()) return this;
      if (!other.getContractVersion().isEmpty()) {
        contractVersion_ = other.contractVersion_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (recordsBuilder_ == null) {
        if (!other.records_.isEmpty()) {
          if (records_.isEmpty()) {
            records_ = other.records_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureRecordsIsMutable();
            records_.addAll(other.records_);
          }
          onChanged();
        }
      } else {
        if (!other.records_.isEmpty()) {
          if (recordsBuilder_.isEmpty()) {
            recordsBuilder_.dispose();
            recordsBuilder_ = null;
            records_ = other.records_;
            bitField0_ = (bitField0_ & ~0x00000002);
            recordsBuilder_ =
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 internalGetRecordsFieldBuilder() : null;
          } else {
            recordsBuilder_.addAllMessages(other.records_);
          }
        }
      }
      if (other.hasNextCursor()) {
        mergeNextCursor(other.getNextCursor());
      }
      if (other.hasExtensions()) {
        mergeExtensions(other.getExtensions());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              contractVersion_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              ai.monarchic.agent_protocol.v1.RunEventRecord m =
                  input.readMessage(
                      ai.monarchic.agent_protocol.v1.RunEventRecord.parser(),
                      extensionRegistry);
              if (recordsBuilder_ == null) {
                ensureRecordsIsMutable();
                records_.add(m);
              } else {
                recordsBuilder_.addMessage(m);
              }
              break;
            } // case 18
            case 26: {
              input.readMessage(
                  internalGetNextCursorFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              input.readMessage(
                  internalGetExtensionsFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object contractVersion_ = "";
    /**
     * <code>string contract_version = 1;</code>
     * @return The contractVersion.
     */
    public java.lang.String getContractVersion() {
      java.lang.Object ref = contractVersion_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        contractVersion_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string contract_version = 1;</code>
     * @return The bytes for contractVersion.
     */
    public com.google.protobuf.ByteString
        getContractVersionBytes() {
      java.lang.Object ref = contractVersion_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        contractVersion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string contract_version = 1;</code>
     * @param value The contractVersion to set.
     * @return This builder for chaining.
     */
    public Builder setContractVersion(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      contractVersion_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string contract_version = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearContractVersion() {
      contractVersion_ = getDefaultInstance().getContractVersion();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string contract_version = 1;</code>
     * @param value The bytes for contractVersion to set.
     * @return This builder for chaining.
     */
    public Builder setContractVersionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      contractVersion_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.util.List<ai.monarchic.agent_protocol.v1.RunEventRecord> records_ =
      java.util.Collections.emptyList();
    private void ensureRecordsIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        records_ = new java.util.ArrayList<ai.monarchic.agent_protocol.v1.RunEventRecord>(records_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        ai.monarchic.agent_protocol.v1.RunEventRecord, ai.monarchic.agent_protocol.v1.RunEventRecord.Builder, ai.monarchic.agent_protocol.v1.RunEventRecordOrBuilder> recordsBuilder_;

    /**
     * <code>repeated .monarchic.agent_protocol.v1.RunEventRecord records = 2;</code>
     */
    public java.util.List<ai.monarchic.agent_protocol.v1.RunEventRecord> getRecordsList() {
      if (recordsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(records_);
      } else {
        return recordsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .monarchic.agent_protocol.v1.RunEventRecord records = 2;</code>
     */
    public int getRecordsCount() {
      if (recordsBuilder_ == null) {
        return records_.size();
      } else {
        return recordsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .monarchic.agent_protocol.v1.RunEventRecord records = 2;</code>
     */
    public ai.monarchic.agent_protocol.v1.RunEventRecord getRecords(int index) {
      if (recordsBuilder_ == null) {
        return records_.get(index);
      } else {
        return recordsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .monarchic.agent_protocol.v1.RunEventRecord records = 2;</code>
     */
    public Builder setRecords(
        int index, ai.monarchic.agent_protocol.v1.RunEventRecord value) {
      if (recordsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRecordsIsMutable();
        records_.set(index, value);
        onChanged();
      } else {
        recordsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .monarchic.agent_protocol.v1.RunEventRecord records = 2;</code>
     */
    public Builder setRecords(
        int index, ai.monarchic.agent_protocol.v1.RunEventRecord.Builder builderForValue) {
      if (recordsBuilder_ == null) {
        ensureRecordsIsMutable();
        records_.set(index, builderForValue.build());
        onChanged();
      } else {
        recordsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .monarchic.agent_protocol.v1.RunEventRecord records = 2;</code>
     */
    public Builder addRecords(ai.monarchic.agent_protocol.v1.RunEventRecord value) {
      if (recordsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRecordsIsMutable();
        records_.add(value);
        onChanged();
      } else {
        recordsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .monarchic.agent_protocol.v1.RunEventRecord records = 2;</code>
     */
    public Builder addRecords(
        int index, ai.monarchic.agent_protocol.v1.RunEventRecord value) {
      if (recordsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRecordsIsMutable();
        records_.add(index, value);
        onChanged();
      } else {
        recordsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .monarchic.agent_protocol.v1.RunEventRecord records = 2;</code>
     */
    public Builder addRecords(
        ai.monarchic.agent_protocol.v1.RunEventRecord.Builder builderForValue) {
      if (recordsBuilder_ == null) {
        ensureRecordsIsMutable();
        records_.add(builderForValue.build());
        onChanged();
      } else {
        recordsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .monarchic.agent_protocol.v1.RunEventRecord records = 2;</code>
     */
    public Builder addRecords(
        int index, ai.monarchic.agent_protocol.v1.RunEventRecord.Builder builderForValue) {
      if (recordsBuilder_ == null) {
        ensureRecordsIsMutable();
        records_.add(index, builderForValue.build());
        onChanged();
      } else {
        recordsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .monarchic.agent_protocol.v1.RunEventRecord records = 2;</code>
     */
    public Builder addAllRecords(
        java.lang.Iterable<? extends ai.monarchic.agent_protocol.v1.RunEventRecord> values) {
      if (recordsBuilder_ == null) {
        ensureRecordsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, records_);
        onChanged();
      } else {
        recordsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .monarchic.agent_protocol.v1.RunEventRecord records = 2;</code>
     */
    public Builder clearRecords() {
      if (recordsBuilder_ == null) {
        records_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        recordsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .monarchic.agent_protocol.v1.RunEventRecord records = 2;</code>
     */
    public Builder removeRecords(int index) {
      if (recordsBuilder_ == null) {
        ensureRecordsIsMutable();
        records_.remove(index);
        onChanged();
      } else {
        recordsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .monarchic.agent_protocol.v1.RunEventRecord records = 2;</code>
     */
    public ai.monarchic.agent_protocol.v1.RunEventRecord.Builder getRecordsBuilder(
        int index) {
      return internalGetRecordsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .monarchic.agent_protocol.v1.RunEventRecord records = 2;</code>
     */
    public ai.monarchic.agent_protocol.v1.RunEventRecordOrBuilder getRecordsOrBuilder(
        int index) {
      if (recordsBuilder_ == null) {
        return records_.get(index);  } else {
        return recordsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .monarchic.agent_protocol.v1.RunEventRecord records = 2;</code>
     */
    public java.util.List<? extends ai.monarchic.agent_protocol.v1.RunEventRecordOrBuilder>
         getRecordsOrBuilderList() {
      if (recordsBuilder_ != null) {
        return recordsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(records_);
      }
    }
    /**
     * <code>repeated .monarchic.agent_protocol.v1.RunEventRecord records = 2;</code>
     */
    public ai.monarchic.agent_protocol.v1.RunEventRecord.Builder addRecordsBuilder() {
      return internalGetRecordsFieldBuilder().addBuilder(
          ai.monarchic.agent_protocol.v1.RunEventRecord.getDefaultInstance());
    }
    /**
     * <code>repeated .monarchic.agent_protocol.v1.RunEventRecord records = 2;</code>
     */
    public ai.monarchic.agent_protocol.v1.RunEventRecord.Builder addRecordsBuilder(
        int index) {
      return internalGetRecordsFieldBuilder().addBuilder(
          index, ai.monarchic.agent_protocol.v1.RunEventRecord.getDefaultInstance());
    }
    /**
     * <code>repeated .monarchic.agent_protocol.v1.RunEventRecord records = 2;</code>
     */
    public java.util.List<ai.monarchic.agent_protocol.v1.RunEventRecord.Builder>
         getRecordsBuilderList() {
      return internalGetRecordsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        ai.monarchic.agent_protocol.v1.RunEventRecord, ai.monarchic.agent_protocol.v1.RunEventRecord.Builder, ai.monarchic.agent_protocol.v1.RunEventRecordOrBuilder>
        internalGetRecordsFieldBuilder() {
      if (recordsBuilder_ == null) {
        recordsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            ai.monarchic.agent_protocol.v1.RunEventRecord, ai.monarchic.agent_protocol.v1.RunEventRecord.Builder, ai.monarchic.agent_protocol.v1.RunEventRecordOrBuilder>(
                records_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        records_ = null;
      }
      return recordsBuilder_;
    }

    private ai.monarchic.agent_protocol.v1.ControlPlaneRunActivityCursor nextCursor_;
    private com.google.protobuf.SingleFieldBuilder<
        ai.monarchic.agent_protocol.v1.ControlPlaneRunActivityCursor, ai.monarchic.agent_protocol.v1.ControlPlaneRunActivityCursor.Builder, ai.monarchic.agent_protocol.v1.ControlPlaneRunActivityCursorOrBuilder> nextCursorBuilder_;
    /**
     * <code>.monarchic.agent_protocol.v1.ControlPlaneRunActivityCursor next_cursor = 3;</code>
     * @return Whether the nextCursor field is set.
     */
    public boolean hasNextCursor() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>.monarchic.agent_protocol.v1.ControlPlaneRunActivityCursor next_cursor = 3;</code>
     * @return The nextCursor.
     */
    public ai.monarchic.agent_protocol.v1.ControlPlaneRunActivityCursor getNextCursor() {
      if (nextCursorBuilder_ == null) {
        return nextCursor_ == null ? ai.monarchic.agent_protocol.v1.ControlPlaneRunActivityCursor.getDefaultInstance() : nextCursor_;
      } else {
        return nextCursorBuilder_.getMessage();
      }
    }
    /**
     * <code>.monarchic.agent_protocol.v1.ControlPlaneRunActivityCursor next_cursor = 3;</code>
     */
    public Builder setNextCursor(ai.monarchic.agent_protocol.v1.ControlPlaneRunActivityCursor value) {
      if (nextCursorBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        nextCursor_ = value;
      } else {
        nextCursorBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.monarchic.agent_protocol.v1.ControlPlaneRunActivityCursor next_cursor = 3;</code>
     */
    public Builder setNextCursor(
        ai.monarchic.agent_protocol.v1.ControlPlaneRunActivityCursor.Builder builderForValue) {
      if (nextCursorBuilder_ == null) {
        nextCursor_ = builderForValue.build();
      } else {
        nextCursorBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.monarchic.agent_protocol.v1.ControlPlaneRunActivityCursor next_cursor = 3;</code>
     */
    public Builder mergeNextCursor(ai.monarchic.agent_protocol.v1.ControlPlaneRunActivityCursor value) {
      if (nextCursorBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
          nextCursor_ != null &&
          nextCursor_ != ai.monarchic.agent_protocol.v1.ControlPlaneRunActivityCursor.getDefaultInstance()) {
          getNextCursorBuilder().mergeFrom(value);
        } else {
          nextCursor_ = value;
        }
      } else {
        nextCursorBuilder_.mergeFrom(value);
      }
      if (nextCursor_ != null) {
        bitField0_ |= 0x00000004;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.monarchic.agent_protocol.v1.ControlPlaneRunActivityCursor next_cursor = 3;</code>
     */
    public Builder clearNextCursor() {
      bitField0_ = (bitField0_ & ~0x00000004);
      nextCursor_ = null;
      if (nextCursorBuilder_ != null) {
        nextCursorBuilder_.dispose();
        nextCursorBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.monarchic.agent_protocol.v1.ControlPlaneRunActivityCursor next_cursor = 3;</code>
     */
    public ai.monarchic.agent_protocol.v1.ControlPlaneRunActivityCursor.Builder getNextCursorBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return internalGetNextCursorFieldBuilder().getBuilder();
    }
    /**
     * <code>.monarchic.agent_protocol.v1.ControlPlaneRunActivityCursor next_cursor = 3;</code>
     */
    public ai.monarchic.agent_protocol.v1.ControlPlaneRunActivityCursorOrBuilder getNextCursorOrBuilder() {
      if (nextCursorBuilder_ != null) {
        return nextCursorBuilder_.getMessageOrBuilder();
      } else {
        return nextCursor_ == null ?
            ai.monarchic.agent_protocol.v1.ControlPlaneRunActivityCursor.getDefaultInstance() : nextCursor_;
      }
    }
    /**
     * <code>.monarchic.agent_protocol.v1.ControlPlaneRunActivityCursor next_cursor = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        ai.monarchic.agent_protocol.v1.ControlPlaneRunActivityCursor, ai.monarchic.agent_protocol.v1.ControlPlaneRunActivityCursor.Builder, ai.monarchic.agent_protocol.v1.ControlPlaneRunActivityCursorOrBuilder>
        internalGetNextCursorFieldBuilder() {
      if (nextCursorBuilder_ == null) {
        nextCursorBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            ai.monarchic.agent_protocol.v1.ControlPlaneRunActivityCursor, ai.monarchic.agent_protocol.v1.ControlPlaneRunActivityCursor.Builder, ai.monarchic.agent_protocol.v1.ControlPlaneRunActivityCursorOrBuilder>(
                getNextCursor(),
                getParentForChildren(),
                isClean());
        nextCursor_ = null;
      }
      return nextCursorBuilder_;
    }

    private com.google.protobuf.Struct extensions_;
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Struct, com.google.protobuf.Struct.Builder, com.google.protobuf.StructOrBuilder> extensionsBuilder_;
    /**
     * <code>.google.protobuf.Struct extensions = 4;</code>
     * @return Whether the extensions field is set.
     */
    public boolean hasExtensions() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>.google.protobuf.Struct extensions = 4;</code>
     * @return The extensions.
     */
    public com.google.protobuf.Struct getExtensions() {
      if (extensionsBuilder_ == null) {
        return extensions_ == null ? com.google.protobuf.Struct.getDefaultInstance() : extensions_;
      } else {
        return extensionsBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Struct extensions = 4;</code>
     */
    public Builder setExtensions(com.google.protobuf.Struct value) {
      if (extensionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        extensions_ = value;
      } else {
        extensionsBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Struct extensions = 4;</code>
     */
    public Builder setExtensions(
        com.google.protobuf.Struct.Builder builderForValue) {
      if (extensionsBuilder_ == null) {
        extensions_ = builderForValue.build();
      } else {
        extensionsBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Struct extensions = 4;</code>
     */
    public Builder mergeExtensions(com.google.protobuf.Struct value) {
      if (extensionsBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0) &&
          extensions_ != null &&
          extensions_ != com.google.protobuf.Struct.getDefaultInstance()) {
          getExtensionsBuilder().mergeFrom(value);
        } else {
          extensions_ = value;
        }
      } else {
        extensionsBuilder_.mergeFrom(value);
      }
      if (extensions_ != null) {
        bitField0_ |= 0x00000008;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.google.protobuf.Struct extensions = 4;</code>
     */
    public Builder clearExtensions() {
      bitField0_ = (bitField0_ & ~0x00000008);
      extensions_ = null;
      if (extensionsBuilder_ != null) {
        extensionsBuilder_.dispose();
        extensionsBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Struct extensions = 4;</code>
     */
    public com.google.protobuf.Struct.Builder getExtensionsBuilder() {
      bitField0_ |= 0x00000008;
      onChanged();
      return internalGetExtensionsFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Struct extensions = 4;</code>
     */
    public com.google.protobuf.StructOrBuilder getExtensionsOrBuilder() {
      if (extensionsBuilder_ != null) {
        return extensionsBuilder_.getMessageOrBuilder();
      } else {
        return extensions_ == null ?
            com.google.protobuf.Struct.getDefaultInstance() : extensions_;
      }
    }
    /**
     * <code>.google.protobuf.Struct extensions = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Struct, com.google.protobuf.Struct.Builder, com.google.protobuf.StructOrBuilder>
        internalGetExtensionsFieldBuilder() {
      if (extensionsBuilder_ == null) {
        extensionsBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.google.protobuf.Struct, com.google.protobuf.Struct.Builder, com.google.protobuf.StructOrBuilder>(
                getExtensions(),
                getParentForChildren(),
                isClean());
        extensions_ = null;
      }
      return extensionsBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:monarchic.agent_protocol.v1.GetControlPlaneRunActivityPageResponse)
  }

  // @@protoc_insertion_point(class_scope:monarchic.agent_protocol.v1.GetControlPlaneRunActivityPageResponse)
  private static final ai.monarchic.agent_protocol.v1.GetControlPlaneRunActivityPageResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ai.monarchic.agent_protocol.v1.GetControlPlaneRunActivityPageResponse();
  }

  public static ai.monarchic.agent_protocol.v1.GetControlPlaneRunActivityPageResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetControlPlaneRunActivityPageResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetControlPlaneRunActivityPageResponse>() {
    @java.lang.Override
    public GetControlPlaneRunActivityPageResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<GetControlPlaneRunActivityPageResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetControlPlaneRunActivityPageResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ai.monarchic.agent_protocol.v1.GetControlPlaneRunActivityPageResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}
