// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: monarchic_agent_protocol.proto
// Protobuf Java Version: 4.32.1

package ai.monarchic.agent_protocol.v1;

@com.google.protobuf.Generated
public interface HeartbeatResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:monarchic.agent_protocol.v1.HeartbeatResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string contract_version = 1;</code>
   * @return The contractVersion.
   */
  java.lang.String getContractVersion();
  /**
   * <code>string contract_version = 1;</code>
   * @return The bytes for contractVersion.
   */
  com.google.protobuf.ByteString
      getContractVersionBytes();

  /**
   * <code>string orchestrator_id = 2;</code>
   * @return The orchestratorId.
   */
  java.lang.String getOrchestratorId();
  /**
   * <code>string orchestrator_id = 2;</code>
   * @return The bytes for orchestratorId.
   */
  com.google.protobuf.ByteString
      getOrchestratorIdBytes();

  /**
   * <code>uint64 next_heartbeat_ms = 3;</code>
   * @return The nextHeartbeatMs.
   */
  long getNextHeartbeatMs();

  /**
   * <code>repeated .monarchic.agent_protocol.v1.CancellationIntent cancellations = 4;</code>
   */
  java.util.List<ai.monarchic.agent_protocol.v1.CancellationIntent>
      getCancellationsList();
  /**
   * <code>repeated .monarchic.agent_protocol.v1.CancellationIntent cancellations = 4;</code>
   */
  ai.monarchic.agent_protocol.v1.CancellationIntent getCancellations(int index);
  /**
   * <code>repeated .monarchic.agent_protocol.v1.CancellationIntent cancellations = 4;</code>
   */
  int getCancellationsCount();
  /**
   * <code>repeated .monarchic.agent_protocol.v1.CancellationIntent cancellations = 4;</code>
   */
  java.util.List<? extends ai.monarchic.agent_protocol.v1.CancellationIntentOrBuilder>
      getCancellationsOrBuilderList();
  /**
   * <code>repeated .monarchic.agent_protocol.v1.CancellationIntent cancellations = 4;</code>
   */
  ai.monarchic.agent_protocol.v1.CancellationIntentOrBuilder getCancellationsOrBuilder(
      int index);

  /**
   * <code>.google.protobuf.Struct extensions = 5;</code>
   * @return Whether the extensions field is set.
   */
  boolean hasExtensions();
  /**
   * <code>.google.protobuf.Struct extensions = 5;</code>
   * @return The extensions.
   */
  com.google.protobuf.Struct getExtensions();
  /**
   * <code>.google.protobuf.Struct extensions = 5;</code>
   */
  com.google.protobuf.StructOrBuilder getExtensionsOrBuilder();
}
