// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: monarchic_agent_protocol.proto
// Protobuf Java Version: 4.32.1

package ai.monarchic.agent_protocol.v1;

@com.google.protobuf.Generated
public final class MonarchicAgentProtocolV1 extends com.google.protobuf.GeneratedFile {
  private MonarchicAgentProtocolV1() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 32,
      /* patch= */ 1,
      /* suffix= */ "",
      MonarchicAgentProtocolV1.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_monarchic_agent_protocol_v1_DatasetRef_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_monarchic_agent_protocol_v1_DatasetRef_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_monarchic_agent_protocol_v1_AcceptanceCriteria_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_monarchic_agent_protocol_v1_AcceptanceCriteria_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_monarchic_agent_protocol_v1_ExperimentSpec_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_monarchic_agent_protocol_v1_ExperimentSpec_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_monarchic_agent_protocol_v1_ObjectiveSpec_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_monarchic_agent_protocol_v1_ObjectiveSpec_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_monarchic_agent_protocol_v1_EvalResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_monarchic_agent_protocol_v1_EvalResult_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_monarchic_agent_protocol_v1_FailureClass_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_monarchic_agent_protocol_v1_FailureClass_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_monarchic_agent_protocol_v1_Provenance_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_monarchic_agent_protocol_v1_Provenance_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_monarchic_agent_protocol_v1_RoleProvenance_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_monarchic_agent_protocol_v1_RoleProvenance_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_monarchic_agent_protocol_v1_PlanProvenance_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_monarchic_agent_protocol_v1_PlanProvenance_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_monarchic_agent_protocol_v1_FailureDetail_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_monarchic_agent_protocol_v1_FailureDetail_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_monarchic_agent_protocol_v1_PlanStep_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_monarchic_agent_protocol_v1_PlanStep_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_monarchic_agent_protocol_v1_Plan_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_monarchic_agent_protocol_v1_Plan_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_monarchic_agent_protocol_v1_ExecutionReceipt_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_monarchic_agent_protocol_v1_ExecutionReceipt_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_monarchic_agent_protocol_v1_Task_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_monarchic_agent_protocol_v1_Task_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_monarchic_agent_protocol_v1_Artifact_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_monarchic_agent_protocol_v1_Artifact_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_monarchic_agent_protocol_v1_Event_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_monarchic_agent_protocol_v1_Event_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_monarchic_agent_protocol_v1_GateResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_monarchic_agent_protocol_v1_GateResult_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_monarchic_agent_protocol_v1_RunOutcome_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_monarchic_agent_protocol_v1_RunOutcome_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_monarchic_agent_protocol_v1_RunContext_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_monarchic_agent_protocol_v1_RunContext_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_monarchic_agent_protocol_v1_RunnerCapabilities_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_monarchic_agent_protocol_v1_RunnerCapabilities_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_monarchic_agent_protocol_v1_LeaseRef_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_monarchic_agent_protocol_v1_LeaseRef_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_monarchic_agent_protocol_v1_FencingToken_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_monarchic_agent_protocol_v1_FencingToken_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_monarchic_agent_protocol_v1_Lease_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_monarchic_agent_protocol_v1_Lease_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_monarchic_agent_protocol_v1_RecoveryEvent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_monarchic_agent_protocol_v1_RecoveryEvent_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_monarchic_agent_protocol_v1_LeaseStatus_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_monarchic_agent_protocol_v1_LeaseStatus_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_monarchic_agent_protocol_v1_CancellationIntent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_monarchic_agent_protocol_v1_CancellationIntent_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_monarchic_agent_protocol_v1_LeaseAssignment_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_monarchic_agent_protocol_v1_LeaseAssignment_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_monarchic_agent_protocol_v1_RegisterRunnerRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_monarchic_agent_protocol_v1_RegisterRunnerRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_monarchic_agent_protocol_v1_RegisterRunnerResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_monarchic_agent_protocol_v1_RegisterRunnerResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_monarchic_agent_protocol_v1_HeartbeatRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_monarchic_agent_protocol_v1_HeartbeatRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_monarchic_agent_protocol_v1_HeartbeatResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_monarchic_agent_protocol_v1_HeartbeatResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_monarchic_agent_protocol_v1_AcquireLeaseRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_monarchic_agent_protocol_v1_AcquireLeaseRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_monarchic_agent_protocol_v1_AcquireLeaseResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_monarchic_agent_protocol_v1_AcquireLeaseResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_monarchic_agent_protocol_v1_RenewLeaseRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_monarchic_agent_protocol_v1_RenewLeaseRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_monarchic_agent_protocol_v1_RenewLeaseResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_monarchic_agent_protocol_v1_RenewLeaseResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_monarchic_agent_protocol_v1_ResumeLeaseRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_monarchic_agent_protocol_v1_ResumeLeaseRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_monarchic_agent_protocol_v1_ResumeLeaseResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_monarchic_agent_protocol_v1_ResumeLeaseResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_monarchic_agent_protocol_v1_ReportStepStartedRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_monarchic_agent_protocol_v1_ReportStepStartedRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_monarchic_agent_protocol_v1_ReportStepStartedResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_monarchic_agent_protocol_v1_ReportStepStartedResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_monarchic_agent_protocol_v1_ReportStepProgressRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_monarchic_agent_protocol_v1_ReportStepProgressRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_monarchic_agent_protocol_v1_ReportStepProgressResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_monarchic_agent_protocol_v1_ReportStepProgressResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_monarchic_agent_protocol_v1_ReportStepOutcomeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_monarchic_agent_protocol_v1_ReportStepOutcomeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_monarchic_agent_protocol_v1_ReportStepOutcomeResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_monarchic_agent_protocol_v1_ReportStepOutcomeResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_monarchic_agent_protocol_v1_AckCancellationRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_monarchic_agent_protocol_v1_AckCancellationRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_monarchic_agent_protocol_v1_AckCancellationResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_monarchic_agent_protocol_v1_AckCancellationResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\036monarchic_agent_protocol.proto\022\033monarc" +
      "hic.agent_protocol.v1\032\034google/protobuf/s" +
      "truct.proto\"\367\001\n\nDatasetRef\022\022\n\ndataset_id" +
      "\030\001 \001(\t\022\020\n\003uri\030\002 \001(\tH\000\210\001\001\022\016\n\006sha256\030\003 \001(\t" +
      "\022\016\n\006format\030\004 \001(\t\022\022\n\005split\030\005 \001(\tH\001\210\001\001\022\027\n\n" +
      "size_bytes\030\006 \001(\004H\002\210\001\001\022\030\n\013description\030\007 \001" +
      "(\tH\003\210\001\001\022+\n\nextensions\030\010 \001(\0132\027.google.pro" +
      "tobuf.StructB\006\n\004_uriB\010\n\006_splitB\r\n\013_size_" +
      "bytesB\016\n\014_description\"\211\002\n\022AcceptanceCrit" +
      "eria\022\016\n\006metric\030\001 \001(\t\022\021\n\tdirection\030\002 \001(\t\022" +
      "\021\n\tthreshold\030\003 \001(\001\022\034\n\017min_effect_size\030\004 " +
      "\001(\001H\000\210\001\001\022\031\n\014max_variance\030\005 \001(\001H\001\210\001\001\022\035\n\020c" +
      "onfidence_level\030\006 \001(\001H\002\210\001\001\022+\n\nextensions" +
      "\030\007 \001(\0132\027.google.protobuf.StructB\022\n\020_min_" +
      "effect_sizeB\017\n\r_max_varianceB\023\n\021_confide" +
      "nce_level\"\374\002\n\016ExperimentSpec\022\025\n\rexperime" +
      "nt_id\030\001 \001(\t\022\021\n\tobjective\030\002 \001(\t\022\027\n\nhypoth" +
      "esis\030\003 \001(\tH\000\210\001\001\022\031\n\014model_family\030\004 \001(\tH\001\210" +
      "\001\001\022\r\n\005seeds\030\005 \003(\003\022=\n\014dataset_refs\030\006 \003(\0132" +
      "\'.monarchic.agent_protocol.v1.DatasetRef" +
      "\022C\n\nacceptance\030\007 \001(\0132/.monarchic.agent_p" +
      "rotocol.v1.AcceptanceCriteria\022,\n\013constra" +
      "ints\030\010 \001(\0132\027.google.protobuf.Struct\022+\n\ne" +
      "xtensions\030\t \001(\0132\027.google.protobuf.Struct" +
      "B\r\n\013_hypothesisB\017\n\r_model_family\"\363\002\n\rObj" +
      "ectiveSpec\022\022\n\nmetric_key\030\001 \001(\t\022\021\n\tdirect" +
      "ion\030\002 \001(\t\022\023\n\006target\030\003 \001(\001H\000\210\001\001\022\026\n\tmin_de" +
      "lta\030\004 \001(\001H\001\210\001\001\022\026\n\ttolerance\030\005 \001(\001H\002\210\001\001\022\030" +
      "\n\013report_file\030\006 \001(\tH\003\210\001\001\022\033\n\016report_task_" +
      "id\030\007 \001(\tH\004\210\001\001\022\023\n\006weight\030\010 \001(\001H\005\210\001\001\022\030\n\013de" +
      "scription\030\t \001(\tH\006\210\001\001\022+\n\nextensions\030\n \001(\013" +
      "2\027.google.protobuf.StructB\t\n\007_targetB\014\n\n" +
      "_min_deltaB\014\n\n_toleranceB\016\n\014_report_file" +
      "B\021\n\017_report_task_idB\t\n\007_weightB\016\n\014_descr" +
      "iption\"\216\002\n\nEvalResult\022\016\n\006metric\030\001 \001(\t\022\r\n" +
      "\005value\030\002 \001(\001\022\025\n\010lower_ci\030\003 \001(\001H\000\210\001\001\022\025\n\010u" +
      "pper_ci\030\004 \001(\001H\001\210\001\001\022\025\n\010variance\030\005 \001(\001H\002\210\001" +
      "\001\022\021\n\004seed\030\006 \001(\003H\003\210\001\001\022\016\n\006passed\030\007 \001(\010\022\022\n\005" +
      "notes\030\010 \001(\tH\004\210\001\001\022+\n\nextensions\030\t \001(\0132\027.g" +
      "oogle.protobuf.StructB\013\n\t_lower_ciB\013\n\t_u" +
      "pper_ciB\013\n\t_varianceB\007\n\005_seedB\010\n\006_notes\"" +
      "\366\001\n\014FailureClass\022\020\n\010category\030\001 \001(\t\022\014\n\004co" +
      "de\030\002 \001(\t\022\021\n\tretryable\030\003 \001(\010\022\023\n\006detail\030\004 " +
      "\001(\tH\000\210\001\001\022\022\n\005scope\030\005 \001(\tH\001\210\001\001\022\023\n\006source\030\006" +
      " \001(\tH\002\210\001\001\022\030\n\013next_action\030\007 \001(\tH\003\210\001\001\022+\n\ne" +
      "xtensions\030\010 \001(\0132\027.google.protobuf.Struct" +
      "B\t\n\007_detailB\010\n\006_scopeB\t\n\007_sourceB\016\n\014_nex" +
      "t_action\"\353\003\n\nProvenance\022\025\n\rprompt_sha256" +
      "\030\001 \001(\t\022\023\n\013code_sha256\030\002 \001(\t\022\026\n\016dataset_s" +
      "ha256\030\003 \003(\t\022\017\n\007runtime\030\004 \001(\t\022\022\n\005model\030\005 " +
      "\001(\tH\000\210\001\001\022\016\n\006runner\030\006 \001(\t\022\024\n\014orchestrator" +
      "\030\007 \001(\t\022\035\n\020task_spec_sha256\030\010 \001(\tH\001\210\001\001\022\034\n" +
      "\017pipeline_sha256\030\t \001(\tH\002\210\001\001\022\033\n\016command_s" +
      "ha256\030\n \001(\tH\003\210\001\001\022\022\n\ncreated_at\030\013 \001(\t\022\033\n\016" +
      "source_task_id\030\014 \001(\tH\004\210\001\001\022=\n\014dataset_ref" +
      "s\030\r \003(\0132\'.monarchic.agent_protocol.v1.Da" +
      "tasetRef\022+\n\nextensions\030\016 \001(\0132\027.google.pr" +
      "otobuf.StructB\010\n\006_modelB\023\n\021_task_spec_sh" +
      "a256B\022\n\020_pipeline_sha256B\021\n\017_command_sha" +
      "256B\021\n\017_source_task_id\"O\n\016RoleProvenance" +
      "\022\021\n\trole_name\030\001 \001(\t\022\025\n\rtemplate_hash\030\002 \001" +
      "(\t\022\023\n\013render_hash\030\003 \001(\t\"\270\001\n\016PlanProvenan" +
      "ce\022\024\n\014generated_by\030\001 \001(\t\022\033\n\016policy_profi" +
      "le\030\002 \001(\tH\000\210\001\001\022\027\n\017generated_at_ms\030\003 \001(\004\022>" +
      "\n\004role\030\004 \001(\0132+.monarchic.agent_protocol." +
      "v1.RoleProvenanceH\001\210\001\001B\021\n\017_policy_profil" +
      "eB\007\n\005_role\"g\n\rFailureDetail\022\r\n\005class\030\001 \001" +
      "(\t\022\014\n\004code\030\002 \001(\t\022\017\n\007message\030\003 \001(\t\022(\n\007det" +
      "ails\030\004 \001(\0132\027.google.protobuf.Struct\"\302\001\n\010" +
      "PlanStep\022\017\n\007step_id\030\001 \001(\t\022\023\n\013description" +
      "\030\002 \001(\t\022\022\n\ndepends_on\030\003 \003(\t\022.\n\rtask_templ" +
      "ate\030\004 \001(\0132\027.google.protobuf.Struct\022@\n\007fa" +
      "ilure\030\005 \001(\0132*.monarchic.agent_protocol.v" +
      "1.FailureDetailH\000\210\001\001B\n\n\010_failure\"\302\002\n\004Pla" +
      "n\022\030\n\020contract_version\030\001 \001(\t\022\017\n\007plan_id\030\002" +
      " \001(\t\022\023\n\006run_id\030\003 \001(\tH\000\210\001\001\022\021\n\tobjective\030\004" +
      " \001(\t\0227\n\006status\030\005 \001(\0162\'.monarchic.agent_p" +
      "rotocol.v1.PlanStatus\022\025\n\rcreated_at_ms\030\006" +
      " \001(\004\022\025\n\rupdated_at_ms\030\007 \001(\004\022?\n\nprovenanc" +
      "e\030\010 \001(\0132+.monarchic.agent_protocol.v1.Pl" +
      "anProvenance\0224\n\005steps\030\t \003(\0132%.monarchic." +
      "agent_protocol.v1.PlanStepB\t\n\007_run_id\"\304\002" +
      "\n\020ExecutionReceipt\022\030\n\020contract_version\030\001" +
      " \001(\t\022\016\n\006run_id\030\002 \001(\t\022\017\n\007plan_id\030\003 \001(\t\022\021\n" +
      "\tplan_hash\030\004 \001(\t\022\023\n\013task_hashes\030\005 \003(\t\022\027\n" +
      "\017artifact_hashes\030\006 \003(\t\022\024\n\014outcome_hash\030\007" +
      " \001(\t\0227\n\006status\030\010 \001(\0162\'.monarchic.agent_p" +
      "rotocol.v1.PlanStatus\022@\n\007failure\030\t \001(\0132*" +
      ".monarchic.agent_protocol.v1.FailureDeta" +
      "ilH\000\210\001\001\022\027\n\017generated_at_ms\030\n \001(\004B\n\n\010_fai" +
      "lure\"\320\003\n\004Task\022\017\n\007version\030\001 \001(\t\022\017\n\007task_i" +
      "d\030\002 \001(\t\0224\n\004role\030\003 \001(\0162&.monarchic.agent_" +
      "protocol.v1.AgentRole\022\014\n\004goal\030\004 \001(\t\022\'\n\006i" +
      "nputs\030\005 \001(\0132\027.google.protobuf.Struct\022,\n\013" +
      "constraints\030\006 \001(\0132\027.google.protobuf.Stru" +
      "ct\022\026\n\016gates_required\030\007 \003(\t\022<\n\013run_contex" +
      "t\030\010 \001(\0132\'.monarchic.agent_protocol.v1.Ru" +
      "nContext\022+\n\nextensions\030\t \001(\0132\027.google.pr" +
      "otobuf.Struct\022D\n\017experiment_spec\030\n \001(\0132+" +
      ".monarchic.agent_protocol.v1.ExperimentS" +
      "pec\022B\n\016objective_spec\030\013 \001(\0132*.monarchic." +
      "agent_protocol.v1.ObjectiveSpec\"\234\003\n\010Arti" +
      "fact\022\017\n\007version\030\001 \001(\t\022\023\n\013artifact_id\030\002 \001" +
      "(\t\022\014\n\004type\030\003 \001(\t\022\017\n\007summary\030\004 \001(\t\022\014\n\004pat" +
      "h\030\005 \001(\t\022\017\n\007task_id\030\006 \001(\t\022+\n\nextensions\030\007" +
      " \001(\0132\027.google.protobuf.Struct\022;\n\nprovena" +
      "nce\030\010 \001(\0132\'.monarchic.agent_protocol.v1." +
      "Provenance\022=\n\014dataset_refs\030\t \003(\0132\'.monar" +
      "chic.agent_protocol.v1.DatasetRef\022=\n\014eva" +
      "l_results\030\n \003(\0132\'.monarchic.agent_protoc" +
      "ol.v1.EvalResult\022D\n\017experiment_spec\030\013 \001(" +
      "\0132+.monarchic.agent_protocol.v1.Experime" +
      "ntSpec\"\355\002\n\005Event\022\017\n\007version\030\001 \001(\t\022\022\n\neve" +
      "nt_type\030\002 \001(\t\022\021\n\ttimestamp\030\003 \001(\t\022\017\n\007task" +
      "_id\030\004 \001(\t\022\016\n\006status\030\005 \001(\t\022\024\n\007message\030\006 \001" +
      "(\tH\000\210\001\001\022+\n\nextensions\030\007 \001(\0132\027.google.pro" +
      "tobuf.Struct\022;\n\nprovenance\030\010 \001(\0132\'.monar" +
      "chic.agent_protocol.v1.Provenance\022=\n\014eva" +
      "l_results\030\t \003(\0132\'.monarchic.agent_protoc" +
      "ol.v1.EvalResult\022@\n\rfailure_class\030\n \001(\0132" +
      ").monarchic.agent_protocol.v1.FailureCla" +
      "ssB\n\n\010_message\"\365\001\n\nGateResult\022\017\n\007version" +
      "\030\001 \001(\t\022\014\n\004gate\030\002 \001(\t\022\016\n\006status\030\003 \001(\t\022\023\n\006" +
      "reason\030\004 \001(\tH\000\210\001\001\022)\n\010evidence\030\005 \001(\0132\027.go" +
      "ogle.protobuf.Struct\022+\n\nextensions\030\006 \001(\013" +
      "2\027.google.protobuf.Struct\022@\n\rfailure_cla" +
      "ss\030\007 \001(\0132).monarchic.agent_protocol.v1.F" +
      "ailureClassB\t\n\007_reason\"\210\006\n\nRunOutcome\022\017\n" +
      "\007version\030\001 \001(\t\022\017\n\007task_id\030\002 \001(\t\022\023\n\006run_i" +
      "d\030\003 \001(\tH\000\210\001\001\022\035\n\020objective_metric\030\004 \001(\tH\001" +
      "\210\001\001\022\034\n\017objective_score\030\005 \001(\001H\002\210\001\001\022H\n\022obj" +
      "ective_decision\030\006 \001(\0162,.monarchic.agent_" +
      "protocol.v1.OutcomeDecision\022\037\n\022estimated" +
      "_cost_usd\030\007 \001(\001H\003\210\001\001\022\035\n\020budget_limit_usd" +
      "\030\010 \001(\001H\004\210\001\001\022C\n\rcost_decision\030\t \001(\0162,.mon" +
      "archic.agent_protocol.v1.OutcomeDecision" +
      "\022\027\n\nrisk_level\030\n \001(\tH\005\210\001\001\022\031\n\014risk_summar" +
      "y\030\013 \001(\tH\006\210\001\001\022C\n\rrisk_decision\030\014 \001(\0162,.mo" +
      "narchic.agent_protocol.v1.OutcomeDecisio" +
      "n\022D\n\016final_decision\030\r \001(\0162,.monarchic.ag" +
      "ent_protocol.v1.OutcomeDecision\022\024\n\007summa" +
      "ry\030\016 \001(\tH\007\210\001\001\022)\n\010evidence\030\017 \001(\0132\027.google" +
      ".protobuf.Struct\022+\n\nextensions\030\020 \001(\0132\027.g" +
      "oogle.protobuf.StructB\t\n\007_run_idB\023\n\021_obj" +
      "ective_metricB\022\n\020_objective_scoreB\025\n\023_es" +
      "timated_cost_usdB\023\n\021_budget_limit_usdB\r\n" +
      "\013_risk_levelB\017\n\r_risk_summaryB\n\n\010_summar" +
      "y\"\231\001\n\nRunContext\022\017\n\007version\030\001 \001(\t\022\014\n\004rep" +
      "o\030\002 \001(\t\022\020\n\010worktree\030\003 \001(\t\022\r\n\005image\030\004 \001(\t" +
      "\022\016\n\006runner\030\005 \001(\t\022\016\n\006labels\030\006 \003(\t\022+\n\nexte" +
      "nsions\030\007 \001(\0132\027.google.protobuf.Struct\"\221\002" +
      "\n\022RunnerCapabilities\022\020\n\010platform\030\001 \001(\t\022\017" +
      "\n\007runtime\030\002 \001(\t\022?\n\017supported_roles\030\003 \003(\016" +
      "2&.monarchic.agent_protocol.v1.AgentRole" +
      "\022\037\n\027supported_task_versions\030\004 \003(\t\022\016\n\006lab" +
      "els\030\005 \003(\t\022 \n\030supports_interactive_pty\030\006 " +
      "\001(\010\022\027\n\017supports_resume\030\007 \001(\010\022+\n\nextensio" +
      "ns\030\010 \001(\0132\027.google.protobuf.Struct\"v\n\010Lea" +
      "seRef\022\020\n\010lease_id\030\001 \001(\t\022\025\n\rfencing_token" +
      "\030\002 \001(\t\022\016\n\006run_id\030\003 \001(\t\022\017\n\007plan_id\030\004 \001(\t\022" +
      "\017\n\007step_id\030\005 \001(\t\022\017\n\007task_id\030\006 \001(\t\"\177\n\014Fen" +
      "cingToken\022\r\n\005token\030\001 \001(\t\022\024\n\014issued_at_ms" +
      "\030\002 \001(\004\022\016\n\006issuer\030\003 \001(\t\022\r\n\005scope\030\004 \001(\t\022+\n" +
      "\nextensions\030\005 \001(\0132\027.google.protobuf.Stru" +
      "ct\"\341\002\n\005Lease\022\020\n\010lease_id\030\001 \001(\t\022\016\n\006run_id" +
      "\030\002 \001(\t\022\017\n\007plan_id\030\003 \001(\t\022\017\n\007step_id\030\004 \001(\t" +
      "\022\017\n\007task_id\030\005 \001(\t\022\021\n\trunner_id\030\006 \001(\t\022\022\n\n" +
      "session_id\030\007 \001(\t\022@\n\rfencing_token\030\010 \001(\0132" +
      ").monarchic.agent_protocol.v1.FencingTok" +
      "en\022\024\n\014issued_at_ms\030\t \001(\004\022\025\n\rexpires_at_m" +
      "s\030\n \001(\004\022@\n\006status\030\013 \001(\01620.monarchic.agen" +
      "t_protocol.v1.LeaseLifecycleState\022+\n\next" +
      "ensions\030\014 \001(\0132\027.google.protobuf.Struct\"\257" +
      "\004\n\rRecoveryEvent\022\020\n\010event_id\030\001 \001(\t\022\016\n\006ru" +
      "n_id\030\002 \001(\t\022\017\n\007plan_id\030\003 \001(\t\022\024\n\007step_id\030\004" +
      " \001(\tH\000\210\001\001\022<\n\004kind\030\005 \001(\0162..monarchic.agen" +
      "t_protocol.v1.RecoveryEventKind\022\026\n\016occur" +
      "red_at_ms\030\006 \001(\004\022\r\n\005actor\030\007 \001(\t\022(\n\007detail" +
      "s\030\010 \001(\0132\027.google.protobuf.Struct\022\030\n\020cont" +
      "ract_version\030\t \001(\t\022F\n\trun_state\030\n \001(\0162.." +
      "monarchic.agent_protocol.v1.RunLifecycle" +
      "StateH\001\210\001\001\022H\n\nstep_state\030\013 \001(\0162/.monarch" +
      "ic.agent_protocol.v1.StepLifecycleStateH" +
      "\002\210\001\001\022V\n\026lease_rejection_reason\030\014 \001(\01621.m" +
      "onarchic.agent_protocol.v1.LeaseRejectio" +
      "nReasonH\003\210\001\001B\n\n\010_step_idB\014\n\n_run_stateB\r" +
      "\n\013_step_stateB\031\n\027_lease_rejection_reason" +
      "\"\344\001\n\013LeaseStatus\0224\n\005lease\030\001 \001(\0132%.monarc" +
      "hic.agent_protocol.v1.LeaseRef\022\r\n\005state\030" +
      "\002 \001(\t\022\025\n\rupdated_at_ms\030\003 \001(\004\022@\n\007failure\030" +
      "\004 \001(\0132*.monarchic.agent_protocol.v1.Fail" +
      "ureDetailH\000\210\001\001\022+\n\nextensions\030\005 \001(\0132\027.goo" +
      "gle.protobuf.StructB\n\n\010_failure\"\257\001\n\022Canc" +
      "ellationIntent\0224\n\005lease\030\001 \001(\0132%.monarchi" +
      "c.agent_protocol.v1.LeaseRef\022\016\n\006reason\030\002" +
      " \001(\t\022\027\n\017requested_at_ms\030\003 \001(\004\022\r\n\005force\030\004" +
      " \001(\010\022+\n\nextensions\030\005 \001(\0132\027.google.protob" +
      "uf.Struct\"\321\001\n\017LeaseAssignment\0224\n\005lease\030\001" +
      " \001(\0132%.monarchic.agent_protocol.v1.Lease" +
      "Ref\022/\n\004task\030\002 \001(\0132!.monarchic.agent_prot" +
      "ocol.v1.Task\022\024\n\014issued_at_ms\030\003 \001(\004\022\024\n\014le" +
      "ase_ttl_ms\030\004 \001(\004\022+\n\nextensions\030\005 \001(\0132\027.g" +
      "oogle.protobuf.Struct\"\325\001\n\025RegisterRunner" +
      "Request\022\030\n\020contract_version\030\001 \001(\t\022\021\n\trun" +
      "ner_id\030\002 \001(\t\022E\n\014capabilities\030\003 \001(\0132/.mon" +
      "archic.agent_protocol.v1.RunnerCapabilit" +
      "ies\022\033\n\023max_parallel_leases\030\004 \001(\r\022+\n\nexte" +
      "nsions\030\005 \001(\0132\027.google.protobuf.Struct\"\313\001" +
      "\n\026RegisterRunnerResponse\022\030\n\020contract_ver" +
      "sion\030\001 \001(\t\022\027\n\017orchestrator_id\030\002 \001(\t\022\022\n\ns" +
      "ession_id\030\003 \001(\t\022\035\n\025heartbeat_interval_ms" +
      "\030\004 \001(\004\022\036\n\026lease_poll_interval_ms\030\005 \001(\004\022+" +
      "\n\nextensions\030\006 \001(\0132\027.google.protobuf.Str" +
      "uct\"\301\001\n\020HeartbeatRequest\022\030\n\020contract_ver" +
      "sion\030\001 \001(\t\022\021\n\trunner_id\030\002 \001(\t\022\022\n\nsession" +
      "_id\030\003 \001(\t\022?\n\ractive_leases\030\004 \003(\0132(.monar" +
      "chic.agent_protocol.v1.LeaseStatus\022+\n\nex" +
      "tensions\030\005 \001(\0132\027.google.protobuf.Struct\"" +
      "\326\001\n\021HeartbeatResponse\022\030\n\020contract_versio" +
      "n\030\001 \001(\t\022\027\n\017orchestrator_id\030\002 \001(\t\022\031\n\021next" +
      "_heartbeat_ms\030\003 \001(\004\022F\n\rcancellations\030\004 \003" +
      "(\0132/.monarchic.agent_protocol.v1.Cancell" +
      "ationIntent\022+\n\nextensions\030\005 \001(\0132\027.google" +
      ".protobuf.Struct\"\266\001\n\023AcquireLeaseRequest" +
      "\022\030\n\020contract_version\030\001 \001(\t\022\021\n\trunner_id\030" +
      "\002 \001(\t\022\022\n\nsession_id\030\003 \001(\t\022\027\n\017available_s" +
      "lots\030\004 \001(\r\022\030\n\020active_lease_ids\030\005 \003(\t\022+\n\n" +
      "extensions\030\006 \001(\0132\027.google.protobuf.Struc" +
      "t\"\230\002\n\024AcquireLeaseResponse\022\030\n\020contract_v" +
      "ersion\030\001 \001(\t\022\027\n\017orchestrator_id\030\002 \001(\t\022@\n" +
      "\nassignment\030\003 \001(\0132,.monarchic.agent_prot" +
      "ocol.v1.LeaseAssignment\022\026\n\016retry_after_m" +
      "s\030\004 \001(\004\022F\n\rcancellations\030\005 \003(\0132/.monarch" +
      "ic.agent_protocol.v1.CancellationIntent\022" +
      "+\n\nextensions\030\006 \001(\0132\027.google.protobuf.St" +
      "ruct\"\267\001\n\021RenewLeaseRequest\022\030\n\020contract_v" +
      "ersion\030\001 \001(\t\022\021\n\trunner_id\030\002 \001(\t\022\022\n\nsessi" +
      "on_id\030\003 \001(\t\0224\n\005lease\030\004 \001(\0132%.monarchic.a" +
      "gent_protocol.v1.LeaseRef\022+\n\nextensions\030" +
      "\005 \001(\0132\027.google.protobuf.Struct\"\262\002\n\022Renew" +
      "LeaseResponse\022\030\n\020contract_version\030\001 \001(\t\022" +
      "\027\n\017orchestrator_id\030\002 \001(\t\022\020\n\010accepted\030\003 \001" +
      "(\010\022\024\n\014lease_ttl_ms\030\004 \001(\004\022F\n\rcancellation" +
      "s\030\005 \003(\0132/.monarchic.agent_protocol.v1.Ca" +
      "ncellationIntent\022@\n\007failure\030\006 \001(\0132*.mona" +
      "rchic.agent_protocol.v1.FailureDetailH\000\210" +
      "\001\001\022+\n\nextensions\030\007 \001(\0132\027.google.protobuf" +
      ".StructB\n\n\010_failure\"\270\001\n\022ResumeLeaseReque" +
      "st\022\030\n\020contract_version\030\001 \001(\t\022\021\n\trunner_i" +
      "d\030\002 \001(\t\022\022\n\nsession_id\030\003 \001(\t\0224\n\005lease\030\004 \001" +
      "(\0132%.monarchic.agent_protocol.v1.LeaseRe" +
      "f\022+\n\nextensions\030\005 \001(\0132\027.google.protobuf." +
      "Struct\"\304\002\n\023ResumeLeaseResponse\022\030\n\020contra" +
      "ct_version\030\001 \001(\t\022\027\n\017orchestrator_id\030\002 \001(" +
      "\t\022\020\n\010accepted\030\003 \001(\010\0221\n\005lease\030\004 \001(\0132\".mon" +
      "archic.agent_protocol.v1.Lease\022\025\n\rexpire" +
      "s_at_ms\030\005 \001(\004\022\035\n\025current_fencing_token\030\006" +
      " \001(\t\022A\n\006reason\030\007 \001(\01621.monarchic.agent_p" +
      "rotocol.v1.LeaseRejectionReason\022\017\n\007messa" +
      "ge\030\010 \001(\t\022+\n\nextensions\030\t \001(\0132\027.google.pr" +
      "otobuf.Struct\"\322\001\n\030ReportStepStartedReque" +
      "st\022\030\n\020contract_version\030\001 \001(\t\022\021\n\trunner_i" +
      "d\030\002 \001(\t\022\022\n\nsession_id\030\003 \001(\t\0224\n\005lease\030\004 \001" +
      "(\0132%.monarchic.agent_protocol.v1.LeaseRe" +
      "f\022\022\n\nstarted_at\030\005 \001(\t\022+\n\nextensions\030\006 \001(" +
      "\0132\027.google.protobuf.Struct\"\333\001\n\031ReportSte" +
      "pStartedResponse\022\030\n\020contract_version\030\001 \001" +
      "(\t\022\027\n\017orchestrator_id\030\002 \001(\t\022\020\n\010accepted\030" +
      "\003 \001(\010\022@\n\007failure\030\004 \001(\0132*.monarchic.agent" +
      "_protocol.v1.FailureDetailH\000\210\001\001\022+\n\nexten" +
      "sions\030\005 \001(\0132\027.google.protobuf.StructB\n\n\010" +
      "_failure\"\255\002\n\031ReportStepProgressRequest\022\030" +
      "\n\020contract_version\030\001 \001(\t\022\021\n\trunner_id\030\002 " +
      "\001(\t\022\022\n\nsession_id\030\003 \001(\t\0224\n\005lease\030\004 \001(\0132%" +
      ".monarchic.agent_protocol.v1.LeaseRef\0222\n" +
      "\006events\030\005 \003(\0132\".monarchic.agent_protocol" +
      ".v1.Event\0228\n\tartifacts\030\006 \003(\0132%.monarchic" +
      ".agent_protocol.v1.Artifact\022+\n\nextension" +
      "s\030\007 \001(\0132\027.google.protobuf.Struct\"\244\002\n\032Rep" +
      "ortStepProgressResponse\022\030\n\020contract_vers" +
      "ion\030\001 \001(\t\022\027\n\017orchestrator_id\030\002 \001(\t\022\020\n\010ac" +
      "cepted\030\003 \001(\010\022F\n\rcancellations\030\004 \003(\0132/.mo" +
      "narchic.agent_protocol.v1.CancellationIn" +
      "tent\022@\n\007failure\030\005 \001(\0132*.monarchic.agent_" +
      "protocol.v1.FailureDetailH\000\210\001\001\022+\n\nextens" +
      "ions\030\006 \001(\0132\027.google.protobuf.StructB\n\n\010_" +
      "failure\"\233\004\n\030ReportStepOutcomeRequest\022\030\n\020" +
      "contract_version\030\001 \001(\t\022\021\n\trunner_id\030\002 \001(" +
      "\t\022\022\n\nsession_id\030\003 \001(\t\0224\n\005lease\030\004 \001(\0132%.m" +
      "onarchic.agent_protocol.v1.LeaseRef\0227\n\006s" +
      "tatus\030\005 \001(\0162\'.monarchic.agent_protocol.v" +
      "1.PlanStatus\0222\n\006events\030\006 \003(\0132\".monarchic" +
      ".agent_protocol.v1.Event\0228\n\tartifacts\030\007 " +
      "\003(\0132%.monarchic.agent_protocol.v1.Artifa" +
      "ct\022A\n\013run_outcome\030\010 \001(\0132\'.monarchic.agen" +
      "t_protocol.v1.RunOutcomeH\000\210\001\001\022@\n\007failure" +
      "\030\t \001(\0132*.monarchic.agent_protocol.v1.Fai" +
      "lureDetailH\001\210\001\001\022\023\n\013finished_at\030\n \001(\t\022+\n\n" +
      "extensions\030\013 \001(\0132\027.google.protobuf.Struc" +
      "tB\016\n\014_run_outcomeB\n\n\010_failure\"\333\001\n\031Report" +
      "StepOutcomeResponse\022\030\n\020contract_version\030" +
      "\001 \001(\t\022\027\n\017orchestrator_id\030\002 \001(\t\022\020\n\010accept" +
      "ed\030\003 \001(\010\022@\n\007failure\030\004 \001(\0132*.monarchic.ag" +
      "ent_protocol.v1.FailureDetailH\000\210\001\001\022+\n\nex" +
      "tensions\030\005 \001(\0132\027.google.protobuf.StructB" +
      "\n\n\010_failure\"\356\001\n\026AckCancellationRequest\022\030" +
      "\n\020contract_version\030\001 \001(\t\022\021\n\trunner_id\030\002 " +
      "\001(\t\022\022\n\nsession_id\030\003 \001(\t\0224\n\005lease\030\004 \001(\0132%" +
      ".monarchic.agent_protocol.v1.LeaseRef\022\016\n" +
      "\006status\030\005 \001(\t\022\024\n\007message\030\006 \001(\tH\000\210\001\001\022+\n\ne" +
      "xtensions\030\007 \001(\0132\027.google.protobuf.Struct" +
      "B\n\n\010_message\"\331\001\n\027AckCancellationResponse" +
      "\022\030\n\020contract_version\030\001 \001(\t\022\027\n\017orchestrat" +
      "or_id\030\002 \001(\t\022\020\n\010accepted\030\003 \001(\010\022@\n\007failure" +
      "\030\004 \001(\0132*.monarchic.agent_protocol.v1.Fai" +
      "lureDetailH\000\210\001\001\022+\n\nextensions\030\005 \001(\0132\027.go" +
      "ogle.protobuf.StructB\n\n\010_failure*\224\001\n\tAge" +
      "ntRole\022\032\n\026AGENT_ROLE_UNSPECIFIED\020\000\022\021\n\rPR" +
      "ODUCT_OWNER\020\001\022\023\n\017PROJECT_MANAGER\020\002\022\007\n\003DE" +
      "V\020\003\022\006\n\002QA\020\004\022\014\n\010REVIEWER\020\005\022\014\n\010SECURITY\020\006\022" +
      "\007\n\003OPS\020\007\022\r\n\tPUBLISHER\020\010*f\n\017OutcomeDecisi" +
      "on\022 \n\034OUTCOME_DECISION_UNSPECIFIED\020\000\022\n\n\006" +
      "ACCEPT\020\001\022\013\n\007ITERATE\020\002\022\n\n\006REJECT\020\003\022\014\n\010ESC" +
      "ALATE\020\004*\223\001\n\nPlanStatus\022\033\n\027PLAN_STATUS_UN" +
      "SPECIFIED\020\000\022\t\n\005DRAFT\020\001\022\013\n\007PLANNED\020\002\022\r\n\tE" +
      "XECUTING\020\003\022\014\n\010COMPLETE\020\004\022\013\n\007BOUNDED\020\005\022\n\n" +
      "\006FAILED\020\006\022\r\n\tCANCELLED\020\007\022\013\n\007UNKNOWN\020\010*\260\001" +
      "\n\023LeaseLifecycleState\022%\n!LEASE_LIFECYCLE" +
      "_STATE_UNSPECIFIED\020\000\022\020\n\014LEASE_ISSUED\020\001\022\020" +
      "\n\014LEASE_ACTIVE\020\002\022\022\n\016LEASE_RELEASED\020\003\022\021\n\r" +
      "LEASE_EXPIRED\020\004\022\023\n\017LEASE_CANCELLED\020\005\022\022\n\016" +
      "LEASE_REJECTED\020\006*\306\001\n\021RunLifecycleState\022#" +
      "\n\037RUN_LIFECYCLE_STATE_UNSPECIFIED\020\000\022\017\n\013R" +
      "UN_PENDING\020\001\022\021\n\rRUN_EXECUTING\020\002\022\016\n\nRUN_P" +
      "AUSED\020\003\022\022\n\016RUN_CANCELLING\020\004\022\021\n\rRUN_CANCE" +
      "LLED\020\005\022\016\n\nRUN_FAILED\020\006\022\020\n\014RUN_COMPLETE\020\007" +
      "\022\017\n\013RUN_BLOCKED\020\010*\311\001\n\022StepLifecycleState" +
      "\022$\n STEP_LIFECYCLE_STATE_UNSPECIFIED\020\000\022\020" +
      "\n\014STEP_PENDING\020\001\022\016\n\nSTEP_READY\020\002\022\017\n\013STEP" +
      "_LEASED\020\003\022\020\n\014STEP_RUNNING\020\004\022\021\n\rSTEP_COMP" +
      "LETE\020\005\022\017\n\013STEP_FAILED\020\006\022\022\n\016STEP_CANCELLE" +
      "D\020\007\022\020\n\014STEP_BLOCKED\020\010*\356\002\n\024LeaseRejection" +
      "Reason\022&\n\"LEASE_REJECTION_REASON_UNSPECI" +
      "FIED\020\000\022\'\n#LEASE_REJECTION_STALE_FENCING_" +
      "TOKEN\020\001\022\033\n\027LEASE_REJECTION_EXPIRED\020\002\022$\n " +
      "LEASE_REJECTION_SESSION_MISMATCH\020\003\022!\n\035LE" +
      "ASE_REJECTION_UNKNOWN_LEASE\020\004\022)\n%LEASE_R" +
      "EJECTION_STEP_ALREADY_TERMINAL\020\005\022&\n\"LEAS" +
      "E_REJECTION_RUN_NOT_EXECUTABLE\020\006\022&\n\"LEAS" +
      "E_REJECTION_DEPENDENCY_BLOCKED\020\007\022$\n LEAS" +
      "E_REJECTION_LEASE_SUPERSEDED\020\010*\257\002\n\021Recov" +
      "eryEventKind\022#\n\037RECOVERY_EVENT_KIND_UNSP" +
      "ECIFIED\020\000\022\'\n#RECOVERY_EVENT_ORCHESTRATOR" +
      "_STARTED\020\001\022!\n\035RECOVERY_EVENT_STATE_RELOA" +
      "DED\020\002\022!\n\035RECOVERY_EVENT_LEASE_RESTORED\020\003" +
      "\022!\n\035RECOVERY_EVENT_LEASE_REJECTED\020\004\022 \n\034R" +
      "ECOVERY_EVENT_STEP_REQUEUED\020\005\022\037\n\033RECOVER" +
      "Y_EVENT_STEP_BLOCKED\020\006\022 \n\034RECOVERY_EVENT" +
      "_RUN_RECOVERED\020\0072\343\010\n\024RunnerControlServic" +
      "e\022y\n\016RegisterRunner\0222.monarchic.agent_pr" +
      "otocol.v1.RegisterRunnerRequest\0323.monarc" +
      "hic.agent_protocol.v1.RegisterRunnerResp" +
      "onse\022j\n\tHeartbeat\022-.monarchic.agent_prot" +
      "ocol.v1.HeartbeatRequest\032..monarchic.age" +
      "nt_protocol.v1.HeartbeatResponse\022s\n\014Acqu" +
      "ireLease\0220.monarchic.agent_protocol.v1.A" +
      "cquireLeaseRequest\0321.monarchic.agent_pro" +
      "tocol.v1.AcquireLeaseResponse\022m\n\nRenewLe" +
      "ase\022..monarchic.agent_protocol.v1.RenewL" +
      "easeRequest\032/.monarchic.agent_protocol.v" +
      "1.RenewLeaseResponse\022p\n\013ResumeLease\022/.mo" +
      "narchic.agent_protocol.v1.ResumeLeaseReq" +
      "uest\0320.monarchic.agent_protocol.v1.Resum" +
      "eLeaseResponse\022\202\001\n\021ReportStepStarted\0225.m" +
      "onarchic.agent_protocol.v1.ReportStepSta" +
      "rtedRequest\0326.monarchic.agent_protocol.v" +
      "1.ReportStepStartedResponse\022\205\001\n\022ReportSt" +
      "epProgress\0226.monarchic.agent_protocol.v1" +
      ".ReportStepProgressRequest\0327.monarchic.a" +
      "gent_protocol.v1.ReportStepProgressRespo" +
      "nse\022\202\001\n\021ReportStepOutcome\0225.monarchic.ag" +
      "ent_protocol.v1.ReportStepOutcomeRequest" +
      "\0326.monarchic.agent_protocol.v1.ReportSte" +
      "pOutcomeResponse\022|\n\017AckCancellation\0223.mo" +
      "narchic.agent_protocol.v1.AckCancellatio" +
      "nRequest\0324.monarchic.agent_protocol.v1.A" +
      "ckCancellationResponseB\210\002\n\036ai.monarchic." +
      "agent_protocol.v1B\030MonarchicAgentProtoco" +
      "lV1P\001Zdgithub.com/monarchic-ai/monarchic" +
      "-agent-protocol/src/go/monarchic/agent_p" +
      "rotocol/v1;agent_protocolv1\242\002\003MAP\252\002\032Mona" +
      "rchic.AgentProtocol.V1\312\002\032Monarchic\\Agent" +
      "Protocol\\V1\342\002#Monarchic\\AgentProtocol\\V1" +
      "\\Metadatab\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.StructProto.getDescriptor(),
        });
    internal_static_monarchic_agent_protocol_v1_DatasetRef_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_monarchic_agent_protocol_v1_DatasetRef_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_monarchic_agent_protocol_v1_DatasetRef_descriptor,
        new java.lang.String[] { "DatasetId", "Uri", "Sha256", "Format", "Split", "SizeBytes", "Description", "Extensions", });
    internal_static_monarchic_agent_protocol_v1_AcceptanceCriteria_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_monarchic_agent_protocol_v1_AcceptanceCriteria_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_monarchic_agent_protocol_v1_AcceptanceCriteria_descriptor,
        new java.lang.String[] { "Metric", "Direction", "Threshold", "MinEffectSize", "MaxVariance", "ConfidenceLevel", "Extensions", });
    internal_static_monarchic_agent_protocol_v1_ExperimentSpec_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_monarchic_agent_protocol_v1_ExperimentSpec_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_monarchic_agent_protocol_v1_ExperimentSpec_descriptor,
        new java.lang.String[] { "ExperimentId", "Objective", "Hypothesis", "ModelFamily", "Seeds", "DatasetRefs", "Acceptance", "Constraints", "Extensions", });
    internal_static_monarchic_agent_protocol_v1_ObjectiveSpec_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_monarchic_agent_protocol_v1_ObjectiveSpec_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_monarchic_agent_protocol_v1_ObjectiveSpec_descriptor,
        new java.lang.String[] { "MetricKey", "Direction", "Target", "MinDelta", "Tolerance", "ReportFile", "ReportTaskId", "Weight", "Description", "Extensions", });
    internal_static_monarchic_agent_protocol_v1_EvalResult_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_monarchic_agent_protocol_v1_EvalResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_monarchic_agent_protocol_v1_EvalResult_descriptor,
        new java.lang.String[] { "Metric", "Value", "LowerCi", "UpperCi", "Variance", "Seed", "Passed", "Notes", "Extensions", });
    internal_static_monarchic_agent_protocol_v1_FailureClass_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_monarchic_agent_protocol_v1_FailureClass_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_monarchic_agent_protocol_v1_FailureClass_descriptor,
        new java.lang.String[] { "Category", "Code", "Retryable", "Detail", "Scope", "Source", "NextAction", "Extensions", });
    internal_static_monarchic_agent_protocol_v1_Provenance_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_monarchic_agent_protocol_v1_Provenance_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_monarchic_agent_protocol_v1_Provenance_descriptor,
        new java.lang.String[] { "PromptSha256", "CodeSha256", "DatasetSha256", "Runtime", "Model", "Runner", "Orchestrator", "TaskSpecSha256", "PipelineSha256", "CommandSha256", "CreatedAt", "SourceTaskId", "DatasetRefs", "Extensions", });
    internal_static_monarchic_agent_protocol_v1_RoleProvenance_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_monarchic_agent_protocol_v1_RoleProvenance_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_monarchic_agent_protocol_v1_RoleProvenance_descriptor,
        new java.lang.String[] { "RoleName", "TemplateHash", "RenderHash", });
    internal_static_monarchic_agent_protocol_v1_PlanProvenance_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_monarchic_agent_protocol_v1_PlanProvenance_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_monarchic_agent_protocol_v1_PlanProvenance_descriptor,
        new java.lang.String[] { "GeneratedBy", "PolicyProfile", "GeneratedAtMs", "Role", });
    internal_static_monarchic_agent_protocol_v1_FailureDetail_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_monarchic_agent_protocol_v1_FailureDetail_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_monarchic_agent_protocol_v1_FailureDetail_descriptor,
        new java.lang.String[] { "Class_", "Code", "Message", "Details", });
    internal_static_monarchic_agent_protocol_v1_PlanStep_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_monarchic_agent_protocol_v1_PlanStep_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_monarchic_agent_protocol_v1_PlanStep_descriptor,
        new java.lang.String[] { "StepId", "Description", "DependsOn", "TaskTemplate", "Failure", });
    internal_static_monarchic_agent_protocol_v1_Plan_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_monarchic_agent_protocol_v1_Plan_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_monarchic_agent_protocol_v1_Plan_descriptor,
        new java.lang.String[] { "ContractVersion", "PlanId", "RunId", "Objective", "Status", "CreatedAtMs", "UpdatedAtMs", "Provenance", "Steps", });
    internal_static_monarchic_agent_protocol_v1_ExecutionReceipt_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_monarchic_agent_protocol_v1_ExecutionReceipt_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_monarchic_agent_protocol_v1_ExecutionReceipt_descriptor,
        new java.lang.String[] { "ContractVersion", "RunId", "PlanId", "PlanHash", "TaskHashes", "ArtifactHashes", "OutcomeHash", "Status", "Failure", "GeneratedAtMs", });
    internal_static_monarchic_agent_protocol_v1_Task_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_monarchic_agent_protocol_v1_Task_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_monarchic_agent_protocol_v1_Task_descriptor,
        new java.lang.String[] { "Version", "TaskId", "Role", "Goal", "Inputs", "Constraints", "GatesRequired", "RunContext", "Extensions", "ExperimentSpec", "ObjectiveSpec", });
    internal_static_monarchic_agent_protocol_v1_Artifact_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_monarchic_agent_protocol_v1_Artifact_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_monarchic_agent_protocol_v1_Artifact_descriptor,
        new java.lang.String[] { "Version", "ArtifactId", "Type", "Summary", "Path", "TaskId", "Extensions", "Provenance", "DatasetRefs", "EvalResults", "ExperimentSpec", });
    internal_static_monarchic_agent_protocol_v1_Event_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_monarchic_agent_protocol_v1_Event_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_monarchic_agent_protocol_v1_Event_descriptor,
        new java.lang.String[] { "Version", "EventType", "Timestamp", "TaskId", "Status", "Message", "Extensions", "Provenance", "EvalResults", "FailureClass", });
    internal_static_monarchic_agent_protocol_v1_GateResult_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_monarchic_agent_protocol_v1_GateResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_monarchic_agent_protocol_v1_GateResult_descriptor,
        new java.lang.String[] { "Version", "Gate", "Status", "Reason", "Evidence", "Extensions", "FailureClass", });
    internal_static_monarchic_agent_protocol_v1_RunOutcome_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_monarchic_agent_protocol_v1_RunOutcome_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_monarchic_agent_protocol_v1_RunOutcome_descriptor,
        new java.lang.String[] { "Version", "TaskId", "RunId", "ObjectiveMetric", "ObjectiveScore", "ObjectiveDecision", "EstimatedCostUsd", "BudgetLimitUsd", "CostDecision", "RiskLevel", "RiskSummary", "RiskDecision", "FinalDecision", "Summary", "Evidence", "Extensions", });
    internal_static_monarchic_agent_protocol_v1_RunContext_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_monarchic_agent_protocol_v1_RunContext_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_monarchic_agent_protocol_v1_RunContext_descriptor,
        new java.lang.String[] { "Version", "Repo", "Worktree", "Image", "Runner", "Labels", "Extensions", });
    internal_static_monarchic_agent_protocol_v1_RunnerCapabilities_descriptor =
      getDescriptor().getMessageTypes().get(19);
    internal_static_monarchic_agent_protocol_v1_RunnerCapabilities_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_monarchic_agent_protocol_v1_RunnerCapabilities_descriptor,
        new java.lang.String[] { "Platform", "Runtime", "SupportedRoles", "SupportedTaskVersions", "Labels", "SupportsInteractivePty", "SupportsResume", "Extensions", });
    internal_static_monarchic_agent_protocol_v1_LeaseRef_descriptor =
      getDescriptor().getMessageTypes().get(20);
    internal_static_monarchic_agent_protocol_v1_LeaseRef_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_monarchic_agent_protocol_v1_LeaseRef_descriptor,
        new java.lang.String[] { "LeaseId", "FencingToken", "RunId", "PlanId", "StepId", "TaskId", });
    internal_static_monarchic_agent_protocol_v1_FencingToken_descriptor =
      getDescriptor().getMessageTypes().get(21);
    internal_static_monarchic_agent_protocol_v1_FencingToken_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_monarchic_agent_protocol_v1_FencingToken_descriptor,
        new java.lang.String[] { "Token", "IssuedAtMs", "Issuer", "Scope", "Extensions", });
    internal_static_monarchic_agent_protocol_v1_Lease_descriptor =
      getDescriptor().getMessageTypes().get(22);
    internal_static_monarchic_agent_protocol_v1_Lease_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_monarchic_agent_protocol_v1_Lease_descriptor,
        new java.lang.String[] { "LeaseId", "RunId", "PlanId", "StepId", "TaskId", "RunnerId", "SessionId", "FencingToken", "IssuedAtMs", "ExpiresAtMs", "Status", "Extensions", });
    internal_static_monarchic_agent_protocol_v1_RecoveryEvent_descriptor =
      getDescriptor().getMessageTypes().get(23);
    internal_static_monarchic_agent_protocol_v1_RecoveryEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_monarchic_agent_protocol_v1_RecoveryEvent_descriptor,
        new java.lang.String[] { "EventId", "RunId", "PlanId", "StepId", "Kind", "OccurredAtMs", "Actor", "Details", "ContractVersion", "RunState", "StepState", "LeaseRejectionReason", });
    internal_static_monarchic_agent_protocol_v1_LeaseStatus_descriptor =
      getDescriptor().getMessageTypes().get(24);
    internal_static_monarchic_agent_protocol_v1_LeaseStatus_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_monarchic_agent_protocol_v1_LeaseStatus_descriptor,
        new java.lang.String[] { "Lease", "State", "UpdatedAtMs", "Failure", "Extensions", });
    internal_static_monarchic_agent_protocol_v1_CancellationIntent_descriptor =
      getDescriptor().getMessageTypes().get(25);
    internal_static_monarchic_agent_protocol_v1_CancellationIntent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_monarchic_agent_protocol_v1_CancellationIntent_descriptor,
        new java.lang.String[] { "Lease", "Reason", "RequestedAtMs", "Force", "Extensions", });
    internal_static_monarchic_agent_protocol_v1_LeaseAssignment_descriptor =
      getDescriptor().getMessageTypes().get(26);
    internal_static_monarchic_agent_protocol_v1_LeaseAssignment_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_monarchic_agent_protocol_v1_LeaseAssignment_descriptor,
        new java.lang.String[] { "Lease", "Task", "IssuedAtMs", "LeaseTtlMs", "Extensions", });
    internal_static_monarchic_agent_protocol_v1_RegisterRunnerRequest_descriptor =
      getDescriptor().getMessageTypes().get(27);
    internal_static_monarchic_agent_protocol_v1_RegisterRunnerRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_monarchic_agent_protocol_v1_RegisterRunnerRequest_descriptor,
        new java.lang.String[] { "ContractVersion", "RunnerId", "Capabilities", "MaxParallelLeases", "Extensions", });
    internal_static_monarchic_agent_protocol_v1_RegisterRunnerResponse_descriptor =
      getDescriptor().getMessageTypes().get(28);
    internal_static_monarchic_agent_protocol_v1_RegisterRunnerResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_monarchic_agent_protocol_v1_RegisterRunnerResponse_descriptor,
        new java.lang.String[] { "ContractVersion", "OrchestratorId", "SessionId", "HeartbeatIntervalMs", "LeasePollIntervalMs", "Extensions", });
    internal_static_monarchic_agent_protocol_v1_HeartbeatRequest_descriptor =
      getDescriptor().getMessageTypes().get(29);
    internal_static_monarchic_agent_protocol_v1_HeartbeatRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_monarchic_agent_protocol_v1_HeartbeatRequest_descriptor,
        new java.lang.String[] { "ContractVersion", "RunnerId", "SessionId", "ActiveLeases", "Extensions", });
    internal_static_monarchic_agent_protocol_v1_HeartbeatResponse_descriptor =
      getDescriptor().getMessageTypes().get(30);
    internal_static_monarchic_agent_protocol_v1_HeartbeatResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_monarchic_agent_protocol_v1_HeartbeatResponse_descriptor,
        new java.lang.String[] { "ContractVersion", "OrchestratorId", "NextHeartbeatMs", "Cancellations", "Extensions", });
    internal_static_monarchic_agent_protocol_v1_AcquireLeaseRequest_descriptor =
      getDescriptor().getMessageTypes().get(31);
    internal_static_monarchic_agent_protocol_v1_AcquireLeaseRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_monarchic_agent_protocol_v1_AcquireLeaseRequest_descriptor,
        new java.lang.String[] { "ContractVersion", "RunnerId", "SessionId", "AvailableSlots", "ActiveLeaseIds", "Extensions", });
    internal_static_monarchic_agent_protocol_v1_AcquireLeaseResponse_descriptor =
      getDescriptor().getMessageTypes().get(32);
    internal_static_monarchic_agent_protocol_v1_AcquireLeaseResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_monarchic_agent_protocol_v1_AcquireLeaseResponse_descriptor,
        new java.lang.String[] { "ContractVersion", "OrchestratorId", "Assignment", "RetryAfterMs", "Cancellations", "Extensions", });
    internal_static_monarchic_agent_protocol_v1_RenewLeaseRequest_descriptor =
      getDescriptor().getMessageTypes().get(33);
    internal_static_monarchic_agent_protocol_v1_RenewLeaseRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_monarchic_agent_protocol_v1_RenewLeaseRequest_descriptor,
        new java.lang.String[] { "ContractVersion", "RunnerId", "SessionId", "Lease", "Extensions", });
    internal_static_monarchic_agent_protocol_v1_RenewLeaseResponse_descriptor =
      getDescriptor().getMessageTypes().get(34);
    internal_static_monarchic_agent_protocol_v1_RenewLeaseResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_monarchic_agent_protocol_v1_RenewLeaseResponse_descriptor,
        new java.lang.String[] { "ContractVersion", "OrchestratorId", "Accepted", "LeaseTtlMs", "Cancellations", "Failure", "Extensions", });
    internal_static_monarchic_agent_protocol_v1_ResumeLeaseRequest_descriptor =
      getDescriptor().getMessageTypes().get(35);
    internal_static_monarchic_agent_protocol_v1_ResumeLeaseRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_monarchic_agent_protocol_v1_ResumeLeaseRequest_descriptor,
        new java.lang.String[] { "ContractVersion", "RunnerId", "SessionId", "Lease", "Extensions", });
    internal_static_monarchic_agent_protocol_v1_ResumeLeaseResponse_descriptor =
      getDescriptor().getMessageTypes().get(36);
    internal_static_monarchic_agent_protocol_v1_ResumeLeaseResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_monarchic_agent_protocol_v1_ResumeLeaseResponse_descriptor,
        new java.lang.String[] { "ContractVersion", "OrchestratorId", "Accepted", "Lease", "ExpiresAtMs", "CurrentFencingToken", "Reason", "Message", "Extensions", });
    internal_static_monarchic_agent_protocol_v1_ReportStepStartedRequest_descriptor =
      getDescriptor().getMessageTypes().get(37);
    internal_static_monarchic_agent_protocol_v1_ReportStepStartedRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_monarchic_agent_protocol_v1_ReportStepStartedRequest_descriptor,
        new java.lang.String[] { "ContractVersion", "RunnerId", "SessionId", "Lease", "StartedAt", "Extensions", });
    internal_static_monarchic_agent_protocol_v1_ReportStepStartedResponse_descriptor =
      getDescriptor().getMessageTypes().get(38);
    internal_static_monarchic_agent_protocol_v1_ReportStepStartedResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_monarchic_agent_protocol_v1_ReportStepStartedResponse_descriptor,
        new java.lang.String[] { "ContractVersion", "OrchestratorId", "Accepted", "Failure", "Extensions", });
    internal_static_monarchic_agent_protocol_v1_ReportStepProgressRequest_descriptor =
      getDescriptor().getMessageTypes().get(39);
    internal_static_monarchic_agent_protocol_v1_ReportStepProgressRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_monarchic_agent_protocol_v1_ReportStepProgressRequest_descriptor,
        new java.lang.String[] { "ContractVersion", "RunnerId", "SessionId", "Lease", "Events", "Artifacts", "Extensions", });
    internal_static_monarchic_agent_protocol_v1_ReportStepProgressResponse_descriptor =
      getDescriptor().getMessageTypes().get(40);
    internal_static_monarchic_agent_protocol_v1_ReportStepProgressResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_monarchic_agent_protocol_v1_ReportStepProgressResponse_descriptor,
        new java.lang.String[] { "ContractVersion", "OrchestratorId", "Accepted", "Cancellations", "Failure", "Extensions", });
    internal_static_monarchic_agent_protocol_v1_ReportStepOutcomeRequest_descriptor =
      getDescriptor().getMessageTypes().get(41);
    internal_static_monarchic_agent_protocol_v1_ReportStepOutcomeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_monarchic_agent_protocol_v1_ReportStepOutcomeRequest_descriptor,
        new java.lang.String[] { "ContractVersion", "RunnerId", "SessionId", "Lease", "Status", "Events", "Artifacts", "RunOutcome", "Failure", "FinishedAt", "Extensions", });
    internal_static_monarchic_agent_protocol_v1_ReportStepOutcomeResponse_descriptor =
      getDescriptor().getMessageTypes().get(42);
    internal_static_monarchic_agent_protocol_v1_ReportStepOutcomeResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_monarchic_agent_protocol_v1_ReportStepOutcomeResponse_descriptor,
        new java.lang.String[] { "ContractVersion", "OrchestratorId", "Accepted", "Failure", "Extensions", });
    internal_static_monarchic_agent_protocol_v1_AckCancellationRequest_descriptor =
      getDescriptor().getMessageTypes().get(43);
    internal_static_monarchic_agent_protocol_v1_AckCancellationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_monarchic_agent_protocol_v1_AckCancellationRequest_descriptor,
        new java.lang.String[] { "ContractVersion", "RunnerId", "SessionId", "Lease", "Status", "Message", "Extensions", });
    internal_static_monarchic_agent_protocol_v1_AckCancellationResponse_descriptor =
      getDescriptor().getMessageTypes().get(44);
    internal_static_monarchic_agent_protocol_v1_AckCancellationResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_monarchic_agent_protocol_v1_AckCancellationResponse_descriptor,
        new java.lang.String[] { "ContractVersion", "OrchestratorId", "Accepted", "Failure", "Extensions", });
    descriptor.resolveAllFeaturesImmutable();
    com.google.protobuf.StructProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
