// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: monarchic_agent_protocol.proto

package ai.monarchic.agent_protocol.v1;

/**
 * Protobuf type {@code monarchic.agent_protocol.v1.RegisterRunnerResponse}
 */
public final class RegisterRunnerResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:monarchic.agent_protocol.v1.RegisterRunnerResponse)
    RegisterRunnerResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use RegisterRunnerResponse.newBuilder() to construct.
  private RegisterRunnerResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RegisterRunnerResponse() {
    contractVersion_ = "";
    orchestratorId_ = "";
    sessionId_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new RegisterRunnerResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ai.monarchic.agent_protocol.v1.MonarchicAgentProtocolV1.internal_static_monarchic_agent_protocol_v1_RegisterRunnerResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ai.monarchic.agent_protocol.v1.MonarchicAgentProtocolV1.internal_static_monarchic_agent_protocol_v1_RegisterRunnerResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ai.monarchic.agent_protocol.v1.RegisterRunnerResponse.class, ai.monarchic.agent_protocol.v1.RegisterRunnerResponse.Builder.class);
  }

  public static final int CONTRACT_VERSION_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object contractVersion_ = "";
  /**
   * <code>string contract_version = 1;</code>
   * @return The contractVersion.
   */
  @java.lang.Override
  public java.lang.String getContractVersion() {
    java.lang.Object ref = contractVersion_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      contractVersion_ = s;
      return s;
    }
  }
  /**
   * <code>string contract_version = 1;</code>
   * @return The bytes for contractVersion.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getContractVersionBytes() {
    java.lang.Object ref = contractVersion_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      contractVersion_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ORCHESTRATOR_ID_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object orchestratorId_ = "";
  /**
   * <code>string orchestrator_id = 2;</code>
   * @return The orchestratorId.
   */
  @java.lang.Override
  public java.lang.String getOrchestratorId() {
    java.lang.Object ref = orchestratorId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      orchestratorId_ = s;
      return s;
    }
  }
  /**
   * <code>string orchestrator_id = 2;</code>
   * @return The bytes for orchestratorId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getOrchestratorIdBytes() {
    java.lang.Object ref = orchestratorId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      orchestratorId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SESSION_ID_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object sessionId_ = "";
  /**
   * <code>string session_id = 3;</code>
   * @return The sessionId.
   */
  @java.lang.Override
  public java.lang.String getSessionId() {
    java.lang.Object ref = sessionId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      sessionId_ = s;
      return s;
    }
  }
  /**
   * <code>string session_id = 3;</code>
   * @return The bytes for sessionId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSessionIdBytes() {
    java.lang.Object ref = sessionId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sessionId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int HEARTBEAT_INTERVAL_MS_FIELD_NUMBER = 4;
  private long heartbeatIntervalMs_ = 0L;
  /**
   * <code>uint64 heartbeat_interval_ms = 4;</code>
   * @return The heartbeatIntervalMs.
   */
  @java.lang.Override
  public long getHeartbeatIntervalMs() {
    return heartbeatIntervalMs_;
  }

  public static final int LEASE_POLL_INTERVAL_MS_FIELD_NUMBER = 5;
  private long leasePollIntervalMs_ = 0L;
  /**
   * <code>uint64 lease_poll_interval_ms = 5;</code>
   * @return The leasePollIntervalMs.
   */
  @java.lang.Override
  public long getLeasePollIntervalMs() {
    return leasePollIntervalMs_;
  }

  public static final int EXTENSIONS_FIELD_NUMBER = 6;
  private com.google.protobuf.Struct extensions_;
  /**
   * <code>.google.protobuf.Struct extensions = 6;</code>
   * @return Whether the extensions field is set.
   */
  @java.lang.Override
  public boolean hasExtensions() {
    return extensions_ != null;
  }
  /**
   * <code>.google.protobuf.Struct extensions = 6;</code>
   * @return The extensions.
   */
  @java.lang.Override
  public com.google.protobuf.Struct getExtensions() {
    return extensions_ == null ? com.google.protobuf.Struct.getDefaultInstance() : extensions_;
  }
  /**
   * <code>.google.protobuf.Struct extensions = 6;</code>
   */
  @java.lang.Override
  public com.google.protobuf.StructOrBuilder getExtensionsOrBuilder() {
    return extensions_ == null ? com.google.protobuf.Struct.getDefaultInstance() : extensions_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(contractVersion_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, contractVersion_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(orchestratorId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, orchestratorId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(sessionId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, sessionId_);
    }
    if (heartbeatIntervalMs_ != 0L) {
      output.writeUInt64(4, heartbeatIntervalMs_);
    }
    if (leasePollIntervalMs_ != 0L) {
      output.writeUInt64(5, leasePollIntervalMs_);
    }
    if (extensions_ != null) {
      output.writeMessage(6, getExtensions());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(contractVersion_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, contractVersion_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(orchestratorId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, orchestratorId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(sessionId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, sessionId_);
    }
    if (heartbeatIntervalMs_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(4, heartbeatIntervalMs_);
    }
    if (leasePollIntervalMs_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(5, leasePollIntervalMs_);
    }
    if (extensions_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getExtensions());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ai.monarchic.agent_protocol.v1.RegisterRunnerResponse)) {
      return super.equals(obj);
    }
    ai.monarchic.agent_protocol.v1.RegisterRunnerResponse other = (ai.monarchic.agent_protocol.v1.RegisterRunnerResponse) obj;

    if (!getContractVersion()
        .equals(other.getContractVersion())) return false;
    if (!getOrchestratorId()
        .equals(other.getOrchestratorId())) return false;
    if (!getSessionId()
        .equals(other.getSessionId())) return false;
    if (getHeartbeatIntervalMs()
        != other.getHeartbeatIntervalMs()) return false;
    if (getLeasePollIntervalMs()
        != other.getLeasePollIntervalMs()) return false;
    if (hasExtensions() != other.hasExtensions()) return false;
    if (hasExtensions()) {
      if (!getExtensions()
          .equals(other.getExtensions())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CONTRACT_VERSION_FIELD_NUMBER;
    hash = (53 * hash) + getContractVersion().hashCode();
    hash = (37 * hash) + ORCHESTRATOR_ID_FIELD_NUMBER;
    hash = (53 * hash) + getOrchestratorId().hashCode();
    hash = (37 * hash) + SESSION_ID_FIELD_NUMBER;
    hash = (53 * hash) + getSessionId().hashCode();
    hash = (37 * hash) + HEARTBEAT_INTERVAL_MS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getHeartbeatIntervalMs());
    hash = (37 * hash) + LEASE_POLL_INTERVAL_MS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getLeasePollIntervalMs());
    if (hasExtensions()) {
      hash = (37 * hash) + EXTENSIONS_FIELD_NUMBER;
      hash = (53 * hash) + getExtensions().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ai.monarchic.agent_protocol.v1.RegisterRunnerResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ai.monarchic.agent_protocol.v1.RegisterRunnerResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ai.monarchic.agent_protocol.v1.RegisterRunnerResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ai.monarchic.agent_protocol.v1.RegisterRunnerResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ai.monarchic.agent_protocol.v1.RegisterRunnerResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ai.monarchic.agent_protocol.v1.RegisterRunnerResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ai.monarchic.agent_protocol.v1.RegisterRunnerResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ai.monarchic.agent_protocol.v1.RegisterRunnerResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ai.monarchic.agent_protocol.v1.RegisterRunnerResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ai.monarchic.agent_protocol.v1.RegisterRunnerResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ai.monarchic.agent_protocol.v1.RegisterRunnerResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ai.monarchic.agent_protocol.v1.RegisterRunnerResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ai.monarchic.agent_protocol.v1.RegisterRunnerResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code monarchic.agent_protocol.v1.RegisterRunnerResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:monarchic.agent_protocol.v1.RegisterRunnerResponse)
      ai.monarchic.agent_protocol.v1.RegisterRunnerResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ai.monarchic.agent_protocol.v1.MonarchicAgentProtocolV1.internal_static_monarchic_agent_protocol_v1_RegisterRunnerResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ai.monarchic.agent_protocol.v1.MonarchicAgentProtocolV1.internal_static_monarchic_agent_protocol_v1_RegisterRunnerResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ai.monarchic.agent_protocol.v1.RegisterRunnerResponse.class, ai.monarchic.agent_protocol.v1.RegisterRunnerResponse.Builder.class);
    }

    // Construct using ai.monarchic.agent_protocol.v1.RegisterRunnerResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      contractVersion_ = "";
      orchestratorId_ = "";
      sessionId_ = "";
      heartbeatIntervalMs_ = 0L;
      leasePollIntervalMs_ = 0L;
      extensions_ = null;
      if (extensionsBuilder_ != null) {
        extensionsBuilder_.dispose();
        extensionsBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ai.monarchic.agent_protocol.v1.MonarchicAgentProtocolV1.internal_static_monarchic_agent_protocol_v1_RegisterRunnerResponse_descriptor;
    }

    @java.lang.Override
    public ai.monarchic.agent_protocol.v1.RegisterRunnerResponse getDefaultInstanceForType() {
      return ai.monarchic.agent_protocol.v1.RegisterRunnerResponse.getDefaultInstance();
    }

    @java.lang.Override
    public ai.monarchic.agent_protocol.v1.RegisterRunnerResponse build() {
      ai.monarchic.agent_protocol.v1.RegisterRunnerResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ai.monarchic.agent_protocol.v1.RegisterRunnerResponse buildPartial() {
      ai.monarchic.agent_protocol.v1.RegisterRunnerResponse result = new ai.monarchic.agent_protocol.v1.RegisterRunnerResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(ai.monarchic.agent_protocol.v1.RegisterRunnerResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.contractVersion_ = contractVersion_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.orchestratorId_ = orchestratorId_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.sessionId_ = sessionId_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.heartbeatIntervalMs_ = heartbeatIntervalMs_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.leasePollIntervalMs_ = leasePollIntervalMs_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.extensions_ = extensionsBuilder_ == null
            ? extensions_
            : extensionsBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ai.monarchic.agent_protocol.v1.RegisterRunnerResponse) {
        return mergeFrom((ai.monarchic.agent_protocol.v1.RegisterRunnerResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ai.monarchic.agent_protocol.v1.RegisterRunnerResponse other) {
      if (other == ai.monarchic.agent_protocol.v1.RegisterRunnerResponse.getDefaultInstance()) return this;
      if (!other.getContractVersion().isEmpty()) {
        contractVersion_ = other.contractVersion_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getOrchestratorId().isEmpty()) {
        orchestratorId_ = other.orchestratorId_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getSessionId().isEmpty()) {
        sessionId_ = other.sessionId_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (other.getHeartbeatIntervalMs() != 0L) {
        setHeartbeatIntervalMs(other.getHeartbeatIntervalMs());
      }
      if (other.getLeasePollIntervalMs() != 0L) {
        setLeasePollIntervalMs(other.getLeasePollIntervalMs());
      }
      if (other.hasExtensions()) {
        mergeExtensions(other.getExtensions());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              contractVersion_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              orchestratorId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              sessionId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 32: {
              heartbeatIntervalMs_ = input.readUInt64();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 40: {
              leasePollIntervalMs_ = input.readUInt64();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            case 50: {
              input.readMessage(
                  getExtensionsFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object contractVersion_ = "";
    /**
     * <code>string contract_version = 1;</code>
     * @return The contractVersion.
     */
    public java.lang.String getContractVersion() {
      java.lang.Object ref = contractVersion_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        contractVersion_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string contract_version = 1;</code>
     * @return The bytes for contractVersion.
     */
    public com.google.protobuf.ByteString
        getContractVersionBytes() {
      java.lang.Object ref = contractVersion_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        contractVersion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string contract_version = 1;</code>
     * @param value The contractVersion to set.
     * @return This builder for chaining.
     */
    public Builder setContractVersion(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      contractVersion_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string contract_version = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearContractVersion() {
      contractVersion_ = getDefaultInstance().getContractVersion();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string contract_version = 1;</code>
     * @param value The bytes for contractVersion to set.
     * @return This builder for chaining.
     */
    public Builder setContractVersionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      contractVersion_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object orchestratorId_ = "";
    /**
     * <code>string orchestrator_id = 2;</code>
     * @return The orchestratorId.
     */
    public java.lang.String getOrchestratorId() {
      java.lang.Object ref = orchestratorId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        orchestratorId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string orchestrator_id = 2;</code>
     * @return The bytes for orchestratorId.
     */
    public com.google.protobuf.ByteString
        getOrchestratorIdBytes() {
      java.lang.Object ref = orchestratorId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        orchestratorId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string orchestrator_id = 2;</code>
     * @param value The orchestratorId to set.
     * @return This builder for chaining.
     */
    public Builder setOrchestratorId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      orchestratorId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string orchestrator_id = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearOrchestratorId() {
      orchestratorId_ = getDefaultInstance().getOrchestratorId();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string orchestrator_id = 2;</code>
     * @param value The bytes for orchestratorId to set.
     * @return This builder for chaining.
     */
    public Builder setOrchestratorIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      orchestratorId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object sessionId_ = "";
    /**
     * <code>string session_id = 3;</code>
     * @return The sessionId.
     */
    public java.lang.String getSessionId() {
      java.lang.Object ref = sessionId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sessionId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string session_id = 3;</code>
     * @return The bytes for sessionId.
     */
    public com.google.protobuf.ByteString
        getSessionIdBytes() {
      java.lang.Object ref = sessionId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sessionId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string session_id = 3;</code>
     * @param value The sessionId to set.
     * @return This builder for chaining.
     */
    public Builder setSessionId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      sessionId_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string session_id = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearSessionId() {
      sessionId_ = getDefaultInstance().getSessionId();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string session_id = 3;</code>
     * @param value The bytes for sessionId to set.
     * @return This builder for chaining.
     */
    public Builder setSessionIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      sessionId_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private long heartbeatIntervalMs_ ;
    /**
     * <code>uint64 heartbeat_interval_ms = 4;</code>
     * @return The heartbeatIntervalMs.
     */
    @java.lang.Override
    public long getHeartbeatIntervalMs() {
      return heartbeatIntervalMs_;
    }
    /**
     * <code>uint64 heartbeat_interval_ms = 4;</code>
     * @param value The heartbeatIntervalMs to set.
     * @return This builder for chaining.
     */
    public Builder setHeartbeatIntervalMs(long value) {
      
      heartbeatIntervalMs_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 heartbeat_interval_ms = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearHeartbeatIntervalMs() {
      bitField0_ = (bitField0_ & ~0x00000008);
      heartbeatIntervalMs_ = 0L;
      onChanged();
      return this;
    }

    private long leasePollIntervalMs_ ;
    /**
     * <code>uint64 lease_poll_interval_ms = 5;</code>
     * @return The leasePollIntervalMs.
     */
    @java.lang.Override
    public long getLeasePollIntervalMs() {
      return leasePollIntervalMs_;
    }
    /**
     * <code>uint64 lease_poll_interval_ms = 5;</code>
     * @param value The leasePollIntervalMs to set.
     * @return This builder for chaining.
     */
    public Builder setLeasePollIntervalMs(long value) {
      
      leasePollIntervalMs_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 lease_poll_interval_ms = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearLeasePollIntervalMs() {
      bitField0_ = (bitField0_ & ~0x00000010);
      leasePollIntervalMs_ = 0L;
      onChanged();
      return this;
    }

    private com.google.protobuf.Struct extensions_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Struct, com.google.protobuf.Struct.Builder, com.google.protobuf.StructOrBuilder> extensionsBuilder_;
    /**
     * <code>.google.protobuf.Struct extensions = 6;</code>
     * @return Whether the extensions field is set.
     */
    public boolean hasExtensions() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>.google.protobuf.Struct extensions = 6;</code>
     * @return The extensions.
     */
    public com.google.protobuf.Struct getExtensions() {
      if (extensionsBuilder_ == null) {
        return extensions_ == null ? com.google.protobuf.Struct.getDefaultInstance() : extensions_;
      } else {
        return extensionsBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Struct extensions = 6;</code>
     */
    public Builder setExtensions(com.google.protobuf.Struct value) {
      if (extensionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        extensions_ = value;
      } else {
        extensionsBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Struct extensions = 6;</code>
     */
    public Builder setExtensions(
        com.google.protobuf.Struct.Builder builderForValue) {
      if (extensionsBuilder_ == null) {
        extensions_ = builderForValue.build();
      } else {
        extensionsBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Struct extensions = 6;</code>
     */
    public Builder mergeExtensions(com.google.protobuf.Struct value) {
      if (extensionsBuilder_ == null) {
        if (((bitField0_ & 0x00000020) != 0) &&
          extensions_ != null &&
          extensions_ != com.google.protobuf.Struct.getDefaultInstance()) {
          getExtensionsBuilder().mergeFrom(value);
        } else {
          extensions_ = value;
        }
      } else {
        extensionsBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Struct extensions = 6;</code>
     */
    public Builder clearExtensions() {
      bitField0_ = (bitField0_ & ~0x00000020);
      extensions_ = null;
      if (extensionsBuilder_ != null) {
        extensionsBuilder_.dispose();
        extensionsBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Struct extensions = 6;</code>
     */
    public com.google.protobuf.Struct.Builder getExtensionsBuilder() {
      bitField0_ |= 0x00000020;
      onChanged();
      return getExtensionsFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Struct extensions = 6;</code>
     */
    public com.google.protobuf.StructOrBuilder getExtensionsOrBuilder() {
      if (extensionsBuilder_ != null) {
        return extensionsBuilder_.getMessageOrBuilder();
      } else {
        return extensions_ == null ?
            com.google.protobuf.Struct.getDefaultInstance() : extensions_;
      }
    }
    /**
     * <code>.google.protobuf.Struct extensions = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Struct, com.google.protobuf.Struct.Builder, com.google.protobuf.StructOrBuilder> 
        getExtensionsFieldBuilder() {
      if (extensionsBuilder_ == null) {
        extensionsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Struct, com.google.protobuf.Struct.Builder, com.google.protobuf.StructOrBuilder>(
                getExtensions(),
                getParentForChildren(),
                isClean());
        extensions_ = null;
      }
      return extensionsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:monarchic.agent_protocol.v1.RegisterRunnerResponse)
  }

  // @@protoc_insertion_point(class_scope:monarchic.agent_protocol.v1.RegisterRunnerResponse)
  private static final ai.monarchic.agent_protocol.v1.RegisterRunnerResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ai.monarchic.agent_protocol.v1.RegisterRunnerResponse();
  }

  public static ai.monarchic.agent_protocol.v1.RegisterRunnerResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RegisterRunnerResponse>
      PARSER = new com.google.protobuf.AbstractParser<RegisterRunnerResponse>() {
    @java.lang.Override
    public RegisterRunnerResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<RegisterRunnerResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RegisterRunnerResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ai.monarchic.agent_protocol.v1.RegisterRunnerResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

