// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: monarchic_agent_protocol.proto
// Protobuf Java Version: 4.32.1

package ai.monarchic.agent_protocol.v1;

@com.google.protobuf.Generated
public interface ReportStepOutcomeResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:monarchic.agent_protocol.v1.ReportStepOutcomeResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string contract_version = 1;</code>
   * @return The contractVersion.
   */
  java.lang.String getContractVersion();
  /**
   * <code>string contract_version = 1;</code>
   * @return The bytes for contractVersion.
   */
  com.google.protobuf.ByteString
      getContractVersionBytes();

  /**
   * <code>string orchestrator_id = 2;</code>
   * @return The orchestratorId.
   */
  java.lang.String getOrchestratorId();
  /**
   * <code>string orchestrator_id = 2;</code>
   * @return The bytes for orchestratorId.
   */
  com.google.protobuf.ByteString
      getOrchestratorIdBytes();

  /**
   * <code>bool accepted = 3;</code>
   * @return The accepted.
   */
  boolean getAccepted();

  /**
   * <code>optional .monarchic.agent_protocol.v1.FailureDetail failure = 4;</code>
   * @return Whether the failure field is set.
   */
  boolean hasFailure();
  /**
   * <code>optional .monarchic.agent_protocol.v1.FailureDetail failure = 4;</code>
   * @return The failure.
   */
  ai.monarchic.agent_protocol.v1.FailureDetail getFailure();
  /**
   * <code>optional .monarchic.agent_protocol.v1.FailureDetail failure = 4;</code>
   */
  ai.monarchic.agent_protocol.v1.FailureDetailOrBuilder getFailureOrBuilder();

  /**
   * <code>.google.protobuf.Struct extensions = 5;</code>
   * @return Whether the extensions field is set.
   */
  boolean hasExtensions();
  /**
   * <code>.google.protobuf.Struct extensions = 5;</code>
   * @return The extensions.
   */
  com.google.protobuf.Struct getExtensions();
  /**
   * <code>.google.protobuf.Struct extensions = 5;</code>
   */
  com.google.protobuf.StructOrBuilder getExtensionsOrBuilder();
}
