// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: monarchic_agent_protocol.proto
// Protobuf Java Version: 4.32.1

package ai.monarchic.agent_protocol.v1;

@com.google.protobuf.Generated
public interface ResumeLeaseRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:monarchic.agent_protocol.v1.ResumeLeaseRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string contract_version = 1;</code>
   * @return The contractVersion.
   */
  java.lang.String getContractVersion();
  /**
   * <code>string contract_version = 1;</code>
   * @return The bytes for contractVersion.
   */
  com.google.protobuf.ByteString
      getContractVersionBytes();

  /**
   * <code>string runner_id = 2;</code>
   * @return The runnerId.
   */
  java.lang.String getRunnerId();
  /**
   * <code>string runner_id = 2;</code>
   * @return The bytes for runnerId.
   */
  com.google.protobuf.ByteString
      getRunnerIdBytes();

  /**
   * <code>string session_id = 3;</code>
   * @return The sessionId.
   */
  java.lang.String getSessionId();
  /**
   * <code>string session_id = 3;</code>
   * @return The bytes for sessionId.
   */
  com.google.protobuf.ByteString
      getSessionIdBytes();

  /**
   * <code>.monarchic.agent_protocol.v1.LeaseRef lease = 4;</code>
   * @return Whether the lease field is set.
   */
  boolean hasLease();
  /**
   * <code>.monarchic.agent_protocol.v1.LeaseRef lease = 4;</code>
   * @return The lease.
   */
  ai.monarchic.agent_protocol.v1.LeaseRef getLease();
  /**
   * <code>.monarchic.agent_protocol.v1.LeaseRef lease = 4;</code>
   */
  ai.monarchic.agent_protocol.v1.LeaseRefOrBuilder getLeaseOrBuilder();

  /**
   * <code>.google.protobuf.Struct extensions = 5;</code>
   * @return Whether the extensions field is set.
   */
  boolean hasExtensions();
  /**
   * <code>.google.protobuf.Struct extensions = 5;</code>
   * @return The extensions.
   */
  com.google.protobuf.Struct getExtensions();
  /**
   * <code>.google.protobuf.Struct extensions = 5;</code>
   */
  com.google.protobuf.StructOrBuilder getExtensionsOrBuilder();

  /**
   * <code>optional .monarchic.agent_protocol.v1.AuthContext auth_context = 6;</code>
   * @return Whether the authContext field is set.
   */
  boolean hasAuthContext();
  /**
   * <code>optional .monarchic.agent_protocol.v1.AuthContext auth_context = 6;</code>
   * @return The authContext.
   */
  ai.monarchic.agent_protocol.v1.AuthContext getAuthContext();
  /**
   * <code>optional .monarchic.agent_protocol.v1.AuthContext auth_context = 6;</code>
   */
  ai.monarchic.agent_protocol.v1.AuthContextOrBuilder getAuthContextOrBuilder();
}
