// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: monarchic_agent_protocol.proto
// Protobuf Java Version: 4.32.1

package ai.monarchic.agent_protocol.v1;

@com.google.protobuf.Generated
public interface RoleProvenanceOrBuilder extends
    // @@protoc_insertion_point(interface_extends:monarchic.agent_protocol.v1.RoleProvenance)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string role_name = 1;</code>
   * @return The roleName.
   */
  java.lang.String getRoleName();
  /**
   * <code>string role_name = 1;</code>
   * @return The bytes for roleName.
   */
  com.google.protobuf.ByteString
      getRoleNameBytes();

  /**
   * <code>string template_hash = 2;</code>
   * @return The templateHash.
   */
  java.lang.String getTemplateHash();
  /**
   * <code>string template_hash = 2;</code>
   * @return The bytes for templateHash.
   */
  com.google.protobuf.ByteString
      getTemplateHashBytes();

  /**
   * <code>string render_hash = 3;</code>
   * @return The renderHash.
   */
  java.lang.String getRenderHash();
  /**
   * <code>string render_hash = 3;</code>
   * @return The bytes for renderHash.
   */
  com.google.protobuf.ByteString
      getRenderHashBytes();
}
