<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: monarchic_agent_protocol.proto

namespace Monarchic\AgentProtocol\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>monarchic.agent_protocol.v1.ArtifactDescriptor</code>
 */
class ArtifactDescriptor extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string artifact_id = 1;</code>
     */
    protected $artifact_id = '';
    /**
     * Generated from protobuf field <code>.monarchic.agent_protocol.v1.ArtifactKind kind = 2;</code>
     */
    protected $kind = 0;
    /**
     * Generated from protobuf field <code>string digest = 3;</code>
     */
    protected $digest = '';
    /**
     * Generated from protobuf field <code>string media_type = 4;</code>
     */
    protected $media_type = '';
    /**
     * Generated from protobuf field <code>string logical_name = 5;</code>
     */
    protected $logical_name = '';
    /**
     * Generated from protobuf field <code>string producer = 6;</code>
     */
    protected $producer = '';
    /**
     * Generated from protobuf field <code>string contract_version = 7;</code>
     */
    protected $contract_version = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $artifact_id
     *     @type int $kind
     *     @type string $digest
     *     @type string $media_type
     *     @type string $logical_name
     *     @type string $producer
     *     @type string $contract_version
     * }
     */
    public function __construct($data = NULL) {
        \Monarchic\AgentProtocol\V1\Metadata\MonarchicAgentProtocol::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string artifact_id = 1;</code>
     * @return string
     */
    public function getArtifactId()
    {
        return $this->artifact_id;
    }

    /**
     * Generated from protobuf field <code>string artifact_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setArtifactId($var)
    {
        GPBUtil::checkString($var, True);
        $this->artifact_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.monarchic.agent_protocol.v1.ArtifactKind kind = 2;</code>
     * @return int
     */
    public function getKind()
    {
        return $this->kind;
    }

    /**
     * Generated from protobuf field <code>.monarchic.agent_protocol.v1.ArtifactKind kind = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setKind($var)
    {
        GPBUtil::checkEnum($var, \Monarchic\AgentProtocol\V1\ArtifactKind::class);
        $this->kind = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string digest = 3;</code>
     * @return string
     */
    public function getDigest()
    {
        return $this->digest;
    }

    /**
     * Generated from protobuf field <code>string digest = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setDigest($var)
    {
        GPBUtil::checkString($var, True);
        $this->digest = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string media_type = 4;</code>
     * @return string
     */
    public function getMediaType()
    {
        return $this->media_type;
    }

    /**
     * Generated from protobuf field <code>string media_type = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setMediaType($var)
    {
        GPBUtil::checkString($var, True);
        $this->media_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string logical_name = 5;</code>
     * @return string
     */
    public function getLogicalName()
    {
        return $this->logical_name;
    }

    /**
     * Generated from protobuf field <code>string logical_name = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setLogicalName($var)
    {
        GPBUtil::checkString($var, True);
        $this->logical_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string producer = 6;</code>
     * @return string
     */
    public function getProducer()
    {
        return $this->producer;
    }

    /**
     * Generated from protobuf field <code>string producer = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setProducer($var)
    {
        GPBUtil::checkString($var, True);
        $this->producer = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string contract_version = 7;</code>
     * @return string
     */
    public function getContractVersion()
    {
        return $this->contract_version;
    }

    /**
     * Generated from protobuf field <code>string contract_version = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setContractVersion($var)
    {
        GPBUtil::checkString($var, True);
        $this->contract_version = $var;

        return $this;
    }

}
