<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: monarchic_agent_protocol.proto

namespace Monarchic\AgentProtocol\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>monarchic.agent_protocol.v1.BootstrapPlanningContext</code>
 */
class BootstrapPlanningContext extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string contract_version = 1;</code>
     */
    protected $contract_version = '';
    /**
     * Generated from protobuf field <code>string project_key = 2;</code>
     */
    protected $project_key = '';
    /**
     * Generated from protobuf field <code>string target_repo = 3;</code>
     */
    protected $target_repo = '';
    /**
     * Generated from protobuf field <code>repeated string target_repos = 4;</code>
     */
    private $target_repos;
    /**
     * Generated from protobuf field <code>string campaign_goal = 5;</code>
     */
    protected $campaign_goal = '';
    /**
     * Generated from protobuf field <code>optional string notes = 6;</code>
     */
    protected $notes = null;
    /**
     * Generated from protobuf field <code>string priority_profile = 7;</code>
     */
    protected $priority_profile = '';
    /**
     * Generated from protobuf field <code>repeated string codex_cmd = 8 [deprecated = true];</code>
     * @deprecated
     */
    private $codex_cmd;
    /**
     * Generated from protobuf field <code>repeated string available_skill_ids = 9;</code>
     */
    private $available_skill_ids;
    /**
     * Generated from protobuf field <code>optional .monarchic.agent_protocol.v1.BootstrapTemplateContext selected_template = 10;</code>
     */
    protected $selected_template = null;
    /**
     * Generated from protobuf field <code>.monarchic.agent_protocol.v1.BootstrapPlanningMode planning_mode = 11;</code>
     */
    protected $planning_mode = 0;
    /**
     * Generated from protobuf field <code>repeated string enabled_role_ids = 12;</code>
     */
    private $enabled_role_ids;
    /**
     * Generated from protobuf field <code>repeated .monarchic.agent_protocol.v1.AgentCommand agent_cmds = 13;</code>
     */
    private $agent_cmds;
    /**
     * Generated from protobuf field <code>repeated string default_agent_cmd = 14;</code>
     */
    private $default_agent_cmd;
    /**
     * Generated from protobuf field <code>repeated .monarchic.agent_protocol.v1.AgentProfile agent_profiles = 15;</code>
     */
    private $agent_profiles;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $contract_version
     *     @type string $project_key
     *     @type string $target_repo
     *     @type string[] $target_repos
     *     @type string $campaign_goal
     *     @type string $notes
     *     @type string $priority_profile
     *     @type string[] $codex_cmd
     *     @type string[] $available_skill_ids
     *     @type \Monarchic\AgentProtocol\V1\BootstrapTemplateContext $selected_template
     *     @type int $planning_mode
     *     @type string[] $enabled_role_ids
     *     @type \Monarchic\AgentProtocol\V1\AgentCommand[] $agent_cmds
     *     @type string[] $default_agent_cmd
     *     @type \Monarchic\AgentProtocol\V1\AgentProfile[] $agent_profiles
     * }
     */
    public function __construct($data = NULL) {
        \Monarchic\AgentProtocol\V1\Metadata\MonarchicAgentProtocol::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string contract_version = 1;</code>
     * @return string
     */
    public function getContractVersion()
    {
        return $this->contract_version;
    }

    /**
     * Generated from protobuf field <code>string contract_version = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setContractVersion($var)
    {
        GPBUtil::checkString($var, True);
        $this->contract_version = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string project_key = 2;</code>
     * @return string
     */
    public function getProjectKey()
    {
        return $this->project_key;
    }

    /**
     * Generated from protobuf field <code>string project_key = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setProjectKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->project_key = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string target_repo = 3;</code>
     * @return string
     */
    public function getTargetRepo()
    {
        return $this->target_repo;
    }

    /**
     * Generated from protobuf field <code>string target_repo = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setTargetRepo($var)
    {
        GPBUtil::checkString($var, True);
        $this->target_repo = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string target_repos = 4;</code>
     * @return RepeatedField<string>
     */
    public function getTargetRepos()
    {
        return $this->target_repos;
    }

    /**
     * Generated from protobuf field <code>repeated string target_repos = 4;</code>
     * @param string[] $var
     * @return $this
     */
    public function setTargetRepos($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->target_repos = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string campaign_goal = 5;</code>
     * @return string
     */
    public function getCampaignGoal()
    {
        return $this->campaign_goal;
    }

    /**
     * Generated from protobuf field <code>string campaign_goal = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setCampaignGoal($var)
    {
        GPBUtil::checkString($var, True);
        $this->campaign_goal = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string notes = 6;</code>
     * @return string
     */
    public function getNotes()
    {
        return isset($this->notes) ? $this->notes : '';
    }

    public function hasNotes()
    {
        return isset($this->notes);
    }

    public function clearNotes()
    {
        unset($this->notes);
    }

    /**
     * Generated from protobuf field <code>optional string notes = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setNotes($var)
    {
        GPBUtil::checkString($var, True);
        $this->notes = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string priority_profile = 7;</code>
     * @return string
     */
    public function getPriorityProfile()
    {
        return $this->priority_profile;
    }

    /**
     * Generated from protobuf field <code>string priority_profile = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setPriorityProfile($var)
    {
        GPBUtil::checkString($var, True);
        $this->priority_profile = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string codex_cmd = 8 [deprecated = true];</code>
     * @return RepeatedField<string>
     * @deprecated
     */
    public function getCodexCmd()
    {
        if (count($this->codex_cmd) !== 0) {
            @trigger_error('codex_cmd is deprecated.', E_USER_DEPRECATED);
        }
        return $this->codex_cmd;
    }

    /**
     * Generated from protobuf field <code>repeated string codex_cmd = 8 [deprecated = true];</code>
     * @param string[] $var
     * @return $this
     * @deprecated
     */
    public function setCodexCmd($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        if (count($arr) !== 0) {
            @trigger_error('codex_cmd is deprecated.', E_USER_DEPRECATED);
        }
        $this->codex_cmd = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string available_skill_ids = 9;</code>
     * @return RepeatedField<string>
     */
    public function getAvailableSkillIds()
    {
        return $this->available_skill_ids;
    }

    /**
     * Generated from protobuf field <code>repeated string available_skill_ids = 9;</code>
     * @param string[] $var
     * @return $this
     */
    public function setAvailableSkillIds($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->available_skill_ids = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .monarchic.agent_protocol.v1.BootstrapTemplateContext selected_template = 10;</code>
     * @return \Monarchic\AgentProtocol\V1\BootstrapTemplateContext|null
     */
    public function getSelectedTemplate()
    {
        return $this->selected_template;
    }

    public function hasSelectedTemplate()
    {
        return isset($this->selected_template);
    }

    public function clearSelectedTemplate()
    {
        unset($this->selected_template);
    }

    /**
     * Generated from protobuf field <code>optional .monarchic.agent_protocol.v1.BootstrapTemplateContext selected_template = 10;</code>
     * @param \Monarchic\AgentProtocol\V1\BootstrapTemplateContext $var
     * @return $this
     */
    public function setSelectedTemplate($var)
    {
        GPBUtil::checkMessage($var, \Monarchic\AgentProtocol\V1\BootstrapTemplateContext::class);
        $this->selected_template = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.monarchic.agent_protocol.v1.BootstrapPlanningMode planning_mode = 11;</code>
     * @return int
     */
    public function getPlanningMode()
    {
        return $this->planning_mode;
    }

    /**
     * Generated from protobuf field <code>.monarchic.agent_protocol.v1.BootstrapPlanningMode planning_mode = 11;</code>
     * @param int $var
     * @return $this
     */
    public function setPlanningMode($var)
    {
        GPBUtil::checkEnum($var, \Monarchic\AgentProtocol\V1\BootstrapPlanningMode::class);
        $this->planning_mode = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string enabled_role_ids = 12;</code>
     * @return RepeatedField<string>
     */
    public function getEnabledRoleIds()
    {
        return $this->enabled_role_ids;
    }

    /**
     * Generated from protobuf field <code>repeated string enabled_role_ids = 12;</code>
     * @param string[] $var
     * @return $this
     */
    public function setEnabledRoleIds($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->enabled_role_ids = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .monarchic.agent_protocol.v1.AgentCommand agent_cmds = 13;</code>
     * @return RepeatedField<\Monarchic\AgentProtocol\V1\AgentCommand>
     */
    public function getAgentCmds()
    {
        return $this->agent_cmds;
    }

    /**
     * Generated from protobuf field <code>repeated .monarchic.agent_protocol.v1.AgentCommand agent_cmds = 13;</code>
     * @param \Monarchic\AgentProtocol\V1\AgentCommand[] $var
     * @return $this
     */
    public function setAgentCmds($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Monarchic\AgentProtocol\V1\AgentCommand::class);
        $this->agent_cmds = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string default_agent_cmd = 14;</code>
     * @return RepeatedField<string>
     */
    public function getDefaultAgentCmd()
    {
        return $this->default_agent_cmd;
    }

    /**
     * Generated from protobuf field <code>repeated string default_agent_cmd = 14;</code>
     * @param string[] $var
     * @return $this
     */
    public function setDefaultAgentCmd($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->default_agent_cmd = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .monarchic.agent_protocol.v1.AgentProfile agent_profiles = 15;</code>
     * @return RepeatedField<\Monarchic\AgentProtocol\V1\AgentProfile>
     */
    public function getAgentProfiles()
    {
        return $this->agent_profiles;
    }

    /**
     * Generated from protobuf field <code>repeated .monarchic.agent_protocol.v1.AgentProfile agent_profiles = 15;</code>
     * @param \Monarchic\AgentProtocol\V1\AgentProfile[] $var
     * @return $this
     */
    public function setAgentProfiles($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Monarchic\AgentProtocol\V1\AgentProfile::class);
        $this->agent_profiles = $arr;

        return $this;
    }

}
