<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: monarchic_agent_protocol.proto

namespace Monarchic\AgentProtocol\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>monarchic.agent_protocol.v1.EnsureControlPlaneWorkerResponse</code>
 */
class EnsureControlPlaneWorkerResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string contract_version = 1;</code>
     */
    protected $contract_version = '';
    /**
     * Generated from protobuf field <code>string project_key = 2;</code>
     */
    protected $project_key = '';
    /**
     * Generated from protobuf field <code>bool accepted = 3;</code>
     */
    protected $accepted = false;
    /**
     * Generated from protobuf field <code>optional string worker_id = 4;</code>
     */
    protected $worker_id = null;
    /**
     * Generated from protobuf field <code>optional string message = 5;</code>
     */
    protected $message = null;
    /**
     * Generated from protobuf field <code>.google.protobuf.Struct extensions = 6;</code>
     */
    protected $extensions = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $contract_version
     *     @type string $project_key
     *     @type bool $accepted
     *     @type string $worker_id
     *     @type string $message
     *     @type \Google\Protobuf\Struct $extensions
     * }
     */
    public function __construct($data = NULL) {
        \Monarchic\AgentProtocol\V1\Metadata\MonarchicAgentProtocol::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string contract_version = 1;</code>
     * @return string
     */
    public function getContractVersion()
    {
        return $this->contract_version;
    }

    /**
     * Generated from protobuf field <code>string contract_version = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setContractVersion($var)
    {
        GPBUtil::checkString($var, True);
        $this->contract_version = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string project_key = 2;</code>
     * @return string
     */
    public function getProjectKey()
    {
        return $this->project_key;
    }

    /**
     * Generated from protobuf field <code>string project_key = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setProjectKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->project_key = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool accepted = 3;</code>
     * @return bool
     */
    public function getAccepted()
    {
        return $this->accepted;
    }

    /**
     * Generated from protobuf field <code>bool accepted = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setAccepted($var)
    {
        GPBUtil::checkBool($var);
        $this->accepted = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string worker_id = 4;</code>
     * @return string
     */
    public function getWorkerId()
    {
        return isset($this->worker_id) ? $this->worker_id : '';
    }

    public function hasWorkerId()
    {
        return isset($this->worker_id);
    }

    public function clearWorkerId()
    {
        unset($this->worker_id);
    }

    /**
     * Generated from protobuf field <code>optional string worker_id = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setWorkerId($var)
    {
        GPBUtil::checkString($var, True);
        $this->worker_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string message = 5;</code>
     * @return string
     */
    public function getMessage()
    {
        return isset($this->message) ? $this->message : '';
    }

    public function hasMessage()
    {
        return isset($this->message);
    }

    public function clearMessage()
    {
        unset($this->message);
    }

    /**
     * Generated from protobuf field <code>optional string message = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setMessage($var)
    {
        GPBUtil::checkString($var, True);
        $this->message = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Struct extensions = 6;</code>
     * @return \Google\Protobuf\Struct|null
     */
    public function getExtensions()
    {
        return $this->extensions;
    }

    public function hasExtensions()
    {
        return isset($this->extensions);
    }

    public function clearExtensions()
    {
        unset($this->extensions);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Struct extensions = 6;</code>
     * @param \Google\Protobuf\Struct $var
     * @return $this
     */
    public function setExtensions($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Struct::class);
        $this->extensions = $var;

        return $this;
    }

}
