<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: monarchic_agent_protocol.proto

namespace Monarchic\AgentProtocol\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * RunnerCapabilities declares the stable machine-facing features a runner can
 * advertise when joining the control plane.
 *
 * Generated from protobuf message <code>monarchic.agent_protocol.v1.RunnerCapabilities</code>
 */
class RunnerCapabilities extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string platform = 1;</code>
     */
    protected $platform = '';
    /**
     * Generated from protobuf field <code>string runtime = 2;</code>
     */
    protected $runtime = '';
    /**
     * Generated from protobuf field <code>repeated .monarchic.agent_protocol.v1.AgentRole supported_roles = 3;</code>
     */
    private $supported_roles;
    /**
     * Generated from protobuf field <code>repeated string supported_task_versions = 4;</code>
     */
    private $supported_task_versions;
    /**
     * Generated from protobuf field <code>repeated string labels = 5;</code>
     */
    private $labels;
    /**
     * Generated from protobuf field <code>bool supports_interactive_pty = 6;</code>
     */
    protected $supports_interactive_pty = false;
    /**
     * Generated from protobuf field <code>bool supports_resume = 7;</code>
     */
    protected $supports_resume = false;
    /**
     * Generated from protobuf field <code>.google.protobuf.Struct extensions = 8;</code>
     */
    protected $extensions = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $platform
     *     @type string $runtime
     *     @type int[] $supported_roles
     *     @type string[] $supported_task_versions
     *     @type string[] $labels
     *     @type bool $supports_interactive_pty
     *     @type bool $supports_resume
     *     @type \Google\Protobuf\Struct $extensions
     * }
     */
    public function __construct($data = NULL) {
        \Monarchic\AgentProtocol\V1\Metadata\MonarchicAgentProtocol::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string platform = 1;</code>
     * @return string
     */
    public function getPlatform()
    {
        return $this->platform;
    }

    /**
     * Generated from protobuf field <code>string platform = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setPlatform($var)
    {
        GPBUtil::checkString($var, True);
        $this->platform = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string runtime = 2;</code>
     * @return string
     */
    public function getRuntime()
    {
        return $this->runtime;
    }

    /**
     * Generated from protobuf field <code>string runtime = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setRuntime($var)
    {
        GPBUtil::checkString($var, True);
        $this->runtime = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .monarchic.agent_protocol.v1.AgentRole supported_roles = 3;</code>
     * @return RepeatedField<int>
     */
    public function getSupportedRoles()
    {
        return $this->supported_roles;
    }

    /**
     * Generated from protobuf field <code>repeated .monarchic.agent_protocol.v1.AgentRole supported_roles = 3;</code>
     * @param int[] $var
     * @return $this
     */
    public function setSupportedRoles($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::ENUM, \Monarchic\AgentProtocol\V1\AgentRole::class);
        $this->supported_roles = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string supported_task_versions = 4;</code>
     * @return RepeatedField<string>
     */
    public function getSupportedTaskVersions()
    {
        return $this->supported_task_versions;
    }

    /**
     * Generated from protobuf field <code>repeated string supported_task_versions = 4;</code>
     * @param string[] $var
     * @return $this
     */
    public function setSupportedTaskVersions($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->supported_task_versions = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string labels = 5;</code>
     * @return RepeatedField<string>
     */
    public function getLabels()
    {
        return $this->labels;
    }

    /**
     * Generated from protobuf field <code>repeated string labels = 5;</code>
     * @param string[] $var
     * @return $this
     */
    public function setLabels($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->labels = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool supports_interactive_pty = 6;</code>
     * @return bool
     */
    public function getSupportsInteractivePty()
    {
        return $this->supports_interactive_pty;
    }

    /**
     * Generated from protobuf field <code>bool supports_interactive_pty = 6;</code>
     * @param bool $var
     * @return $this
     */
    public function setSupportsInteractivePty($var)
    {
        GPBUtil::checkBool($var);
        $this->supports_interactive_pty = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool supports_resume = 7;</code>
     * @return bool
     */
    public function getSupportsResume()
    {
        return $this->supports_resume;
    }

    /**
     * Generated from protobuf field <code>bool supports_resume = 7;</code>
     * @param bool $var
     * @return $this
     */
    public function setSupportsResume($var)
    {
        GPBUtil::checkBool($var);
        $this->supports_resume = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Struct extensions = 8;</code>
     * @return \Google\Protobuf\Struct|null
     */
    public function getExtensions()
    {
        return $this->extensions;
    }

    public function hasExtensions()
    {
        return isset($this->extensions);
    }

    public function clearExtensions()
    {
        unset($this->extensions);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Struct extensions = 8;</code>
     * @param \Google\Protobuf\Struct $var
     * @return $this
     */
    public function setExtensions($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Struct::class);
        $this->extensions = $var;

        return $this;
    }

}

