name: Nix CI

on:
  push:
    branches:
      - main
  merge_group:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

concurrency:
  group: nix-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  nix-ci:
    uses: monarchic-ai/.github/.github/workflows/nix-ci.yml@main
    with:
      publish_cache: ${{ github.ref == 'refs/heads/main' }}
    secrets:
      MONARCHIC_GITHUB_PAT: ${{ secrets.MONARCHIC_GITHUB_PAT }}
